### ISSUE TITLE
[Feature request] Config update without restart

### ISSUE THREAD

**Issue by vkosilko** [toni-moreno/snmpcollector#10]
First initialisation of snmp devices take large time for big envirenment.
Need a feature to update snmp device list without collector restarting.

**Comment by vkosilko** [comment]
@toni-moreno are there any time ranges for feature requests? Can we hope to get new release with this feature this year?

**Comment by toni-moreno** [comment]
Yes , I hope this feature will be ready soon.
How big is your environtment ? How long it takes for all your devices?

**Comment by vkosilko** [comment]
@toni-moreno our environment is about 600 devices.
Now we use snmpcollector for 15 devices and it takes several minutes to initialize.

**Comment by toni-moreno** [comment]
@vkosilko I've released a new version today whitch does major initialization in concurrent mode better than sequencial .Now the restart

**Comment by vkosilko** [comment]
@toni-moreno concurrent mode works fine and fast enough, but config update feature without restart will be more usefull.

**Comment by toni-moreno** [comment]
@vkosilko yes sure!! Is only a workaround until a complete functional WebUI was released ( now is 80% usable, some errors still does complicate do all things online but close to release) 

 
![image](https://cloud.githubusercontent.com/assets/5883405/19731059/7328077e-9b9c-11e6-9e8d-00ce40cdee42.png)

**Comment by toni-moreno** [comment]
Hi @vkosilko , With last commit you can now reload configuration from web ui , and also control current runtime for all your devices.

![image](https://cloud.githubusercontent.com/assets/5883405/20682423/4b8bf326-b5a8-11e6-9410-9c50f6ce93fe.png)

Let me know if can I close this issue.
