### ISSUE TITLE
[Bug] Reload filters can cause time shift on some metrics depending on polling time

### ISSUE THREAD

**Issue by sbengo** [toni-moreno/snmpcollector#100]
Hi,

As the SNMPCollector works, it is sending a SNMP poll on every N secs depending on device ```Freq``` parameter.

When the time spent on reloading filter is too high or starts near to finish the next ```Freq``` cycle, can produce a time gap on the metric fields.

Let me explain it better with an example:

**Conf**:
```Freq : 60s```
```Polling cycle at XX:50```
```Polling time elapsed: 5s```
```Filter time elapsed: 12s```

**Runtime**:
```
-> Polling start...
-> !! Not poll, filter must be reloaded
-> Reloading filter at 00:50
-> Finish filter reloading at 01:02
-> Starting poll: 01:02
-> Writing metrics with TS : 01:14
-------------> !! Metric gap on TS: XX!
````

As you can  see, the point on TS ```XX``` will be missed!

**Comment by toni-moreno** [comment]
This error is because we are first computing filter changes and after gathering data, we can easily fix by changing the order.
