### ISSUE TITLE
Out of order failure

### ISSUE THREAD

**Issue by vkosilko** [toni-moreno/snmpcollector#11]
If I add some specific devices to configuration, snmpcollector stops working with such error:
```
FATA[0856] SNMP bulkwalk error Out of order response    
``` 
To avoid such error in net-snmp commands can be used key "-Cc":
http://www.net-snmp.org/docs/man/snmpbulkwalk.html

**Comment by toni-moreno** [comment]
Hi @vkosilko This error seems to be related to the snmp protocol itself and this other reported error

https://github.com/soniah/gosnmp/issues/69

I will try to investigate about it.

does the collector a crash after this error?

**Comment by vkosilko** [comment]
@toni-moreno yes, collector crashes.

**Comment by toni-moreno** [comment]
Hi @vkosilko can you turn on the snmpdebug option in the device?

You can do it with direct SQL
```
#cd conf
#sqlite3 snmpcollector.db

UPDATE snmp_device_cfg SET snmpdebug=1 where id='yourdeviceid';
```
After can you restart the collector and look for a debug file in your log/ dir after the device stop looking data? Could you make a git with it?

Thank you very much

**Comment by toni-moreno** [comment]
Can you send us also the output when it crashes? ( stacktrace, panic message, log ,etc?)

Thank you very much.

**Comment by toni-moreno** [comment]
Hi @vkosilko, how many seconds have you set as  your device Timeout ?

**Comment by toni-moreno** [comment]
Hi @vkosilko while doing a more detailed investigation on the out of order and how to fix, I've built a fix to avoid the complete crash of the collector at https://github.com/toni-moreno/snmpcollector/commit/6c9e068daee2945ce5679c0c49f5adf8c6a8cb81

I hope you can continue working with the snmpcollector until the out of order problem could be completely fixed.

**Comment by vkosilko** [comment]
Hi, @toni-moreno 

Answering your questions:

Debug logs:
https://goo.gl/HD7iAa
R127 and R129 are identical switches, but only R127 give "out of order" error.

Partial fix don't prevent collector's shutdown. Log_2_127.tgz is for collector after applying [partial fix](https://github.com/toni-moreno/snmpcollector/commit/6c9e068daee2945ce5679c0c49f5adf8c6a8cb81) 

Console debug output you can see in console.log.

**Comment by toni-moreno** [comment]
Hi @vkosilko I'm looking your logs but I'm also confused on the exact point where your snmpcollector is chrashing.

So I will need some more info.

1.- Golang version are you building the snmpcollector.
2.- System version where are you running the snmpcollector.
3.- Can you show me your configuration  ?
you can easily copy from sql tool (feel free to change names/ip's or other sensible data)
```
#cd conf
#sqlite3 snmpcollector.db
#.dump
``` 
3.- I need the device log also in debug mode ( not only snmpdebug for debugging snmp protocol ), you can change the device log just in your device configuration.

```
#cd conf
#sqlite3 snmpcollector.db

UPDATE snmp_device_cfg SET loglevel='debug' where id='yourdeviceid';
````
restart snmpcollector and send me the log directory again. Thank you very much

**Comment by vkosilko** [comment]
Hi, @toni-moreno 

go version go1.6.2 linux/amd64
system version Debian 8.5
Copied debug files for selected device (R127) from archive to root folder of google drive: https://goo.gl/HD7iAa

**Comment by vkosilko** [comment]
snmpcollector.db file was uploaded to google drive too.

**Comment by toni-moreno** [comment]
HI @vkosilko I've been working last hours on a big refactor to improve code quality and also reviewing all  posible issues afecting you in the "out of order" problem.

Indeed I've changed two things thigs.
* removed all log.Fatal() messages ( it causes direct exit(1)  of the hole process when invoked).
* changed the first indexation function from BulkWalkAll() to BulkWalk() possible cause of out of order problem

I would like you can test again and I hope the out of order problem has been finally fixed, feel free to send us any other suggestion

**Comment by toni-moreno** [comment]
Hi @vkosilko have you tested last days improvements?

**Comment by vkosilko** [comment]
Hi, @toni-moreno, I have tested new release. "Out of order error" disappeared, but there is new problem that we didn't have before. Described in #22 issue.
