### ISSUE TITLE
[Feature Request] Add regex on tag format

### ISSUE THREAD

**Issue by sbengo** [toni-moreno/snmpcollector#125]
Would be interesting to add the feat to use regex on tag format.

As an example, an A10 table is formatted by double index: cpuIndex and periodIndex, as it shows the following screenshot, trying to get the cpuUsage:

![image](https://cloud.githubusercontent.com/assets/13196237/22739037/2e06720a-ee0a-11e6-8bd4-956c73b42a6f.png)

The metric must be set up on index measurement, with the same index oid. To clean the output influx point, the format tag has been set with `cpu-$IDX1`

Applying the following filter, we only obtain the values which period is 60secs (same as our polling time).

![image](https://cloud.githubusercontent.com/assets/13196237/22739105/779548ec-ee0a-11e6-9b20-e82543e17898.png)

As you can see, it appears with the double index. It would be interesting to add some regex feature to only get, as i.e, the first index value, so the results would include the cpuIndex and not with periodIndex. Mockup:

![image](https://cloud.githubusercontent.com/assets/13196237/22739263/379bc9a4-ee0b-11e6-914e-9906bb353420.png)

**Comment by toni-moreno** [comment]
Now we can do that with ${IDX1|DOT[0:0]|}
