### ISSUE TITLE
Browser Refresh Triggers 404 Error

### ISSUE THREAD

**Issue by henworth** [toni-moreno/snmpcollector#126]
When doing a browser refresh of any page, only the message "404 page not found" is then displayed in the body.

In http_access.log these lines are shown, even with debug enabled nothing else seems to be displayed.

```
[Macaron] 2017-02-08 10:50:12: Started GET /home for 10.10.42.58
[Macaron] 2017-02-08 10:50:12: Completed /home 404 Not Found in 113.925µs
[Macaron] 2017-02-08 10:50:13: Started GET /favicon.ico for 10.10.42.58
[Macaron] [Static] Serving /favicon.ico
[Macaron] 2017-02-08 10:50:13: Completed /favicon.ico 304 Not Modified in 126.711µs
```

**Comment by toni-moreno** [comment]
Hi @henworth  .

how have you installed snmpcollector? , from source code? from rpm / deb ?

**Comment by henworth** [comment]
Installed from rpm, version 0.6.4.

**Comment by toni-moreno** [comment]
Hi @henworth , this it is a known behaviour,  but we have no plans to change it . 

IMHO You don't need  use the  browser refresh to work with snmpcollector . 

The  runtime view reload itself to refresh current gathered data. 

Can you give me a good reason to keep this issue opened ?

**Comment by henworth** [comment]
I would consider it a very normal operation to refresh pages, being that it's a fairly common action that's become muscle memory at this point. It wouldn't be so bad if it didn't require a new login session. As it stands, if you erroneously hit refresh, you must manually remove /home from the url and then this prompts to login again. It just seems really cumbersome. 

I really like the tool but this would be a really nice quality of life improvement. 

I'm curious, are there no plans because this is expected/desired behavior or because it's not a priority against other tasks? I can understand the if it's latter.

**Comment by toni-moreno** [comment]
It's not a priority but we'll keep opened until we can fix it.

**Comment by sbengo** [comment]
Hi @henworth it should be fixed on the last commit! Closing this in favor #129
