### ISSUE TITLE
[Feature Request] Cooked Type STRINGCONCAT

### ISSUE THREAD

**Issue by topranks** [toni-moreno/snmpcollector#150]
Hi,

Perhaps this is already possible but I'm not sure.  I am parsing the standard IF-MIB:ifTable table in a similar way to show in your wiki tutorial on a Catalyst switch.

I am reading both ifName (interface identifier) and ifAlias (interface description) and saving as tags.  So for instance I might get tag values like this on a measurement:

ifName: Gi0/1
ifAlias:   Link to Switch2 Gi0/0

What would be great is if there was a way to concatenate the strings returned in each of the above metrics into a new one.  So in the above case the new cooked metric would be "Gi0/1 - Link to Switch2 Gi0/0" or similar.  Similar to the STRINGEVAL cooked type, but performing simple text processing rather than math.

This would be very nice for templating in Grafana, giving graphs good titles automatically etc.  For instance I've a dashboard that you select a 'device' and it lists all the interfaces on it and draws the graphs for them with a row repeat:

http://imgur.com/a/Bxv3k

If the 'Interface' could be a combined interface ID and description it would make this dashboard a lot more useful.

Thanks again for the amazing tool!

Cathal.

**Comment by toni-moreno** [comment]
Yes you would be able  to do it with STRINGEVAL type . 

With this type you can  also concatenate STRINGS with "+" operator and a lot of other things , all what the base library used can  (govaluate) .

This manual will show you all what you can  do with STRINGEVAL

https://github.com/Knetic/govaluate/blob/master/MANUAL.md

https://github.com/Knetic/govaluate/blob/master/MANUAL.md#addition-concatenation-

I also suggest you configure "IsTag" as true in this new STRINGEVAL snmpmetric

**Comment by topranks** [comment]
Wow!  Ok great thanks Toni I will get on this right away, cheers for the info and pointer to the govaluate function.

I guess this should be closed feature is implemented!
http://imgur.com/a/Z8XAN


Amazing work once again thanks.
