### ISSUE TITLE
[Feature Request] SMIv2 and 'non-accessible' index 

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#152]
Hello,

As per SMIv2 definition of the MIB , the INDEX of the table must be '_not-accessible_' unless there are no other objects than the Auxiliary object itself in the table. This way index cannot be retrived (via snmpget etc.) and then used for the query but it's included as suffix part of the retrived OID itself. Are you planning to implement the feature to extract the index from the part of OID itself to follow SMIv2 convention strictly?

Regards,
PaVliK

**Comment by toni-moreno** [comment]
Hi @pavleec.

SnmpCollector can use as Index the remaining part of the OID from any of the rows of the table. To do that you should only use it in the IndexOID configuration in the measurement section (https://github.com/toni-moreno/snmpcollector/wiki#3--defining-measurements) , and the values of this row will be sent also as Tag.

I hope this answer can help you.   Sorry if I did not understand your question. In this case I suggest to show us a use case or example of a table with this kind of 'not-accesible' index.

**Comment by pavleec** [comment]
Hi @toni-moreno 

That's exactly what I was trying to achive - thanks for the explanation :). The only thing which is missing is the possibility to convert this fancy looking numbers in tags now, to some key-value text mapping like:
```
12 -> ABC
13 -> DEF
```
However the best it would be to implement the MIB files translation (guess it's on the roadmap?) or basic DEC to ASCII convertion so something like this:
.1.3.6.1.4.1.**82.97.100.105.117.115**
will be changed to:
SOME-MIB::SomeStatistic.**Radius**

**Comment by toni-moreno** [comment]
Hi @pavleec we would like to add a autocomplete measurement/snmpmetric ID's name from a mib database lookup and after a automatic autocomplete for the other form fields from the data of the MIB database. But this process will be only in configuration time . OID's will be finally stored as you are doing now. 
I will close this issue now . Feel free to reopen if needed
