### ISSUE TITLE
[Feature Request] InfluxDB write precision parameter

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#159]
Hi, 

I've just stumbled upon the problem of time precision that is used in timestamps during InfluxDB writes. It would be great if you could add support for **precision=[n,u,ms,s,m,h]** option for InfluxDB servers which sets the precision of the supplied Unix time values. I guess now it's set to default in nanoseconds which becomes problematic when you're using queries that are based on GROUP BY time () clause.

**Comment by toni-moreno** [comment]
Hi @pavleec , yes!!
I've added in https://github.com/toni-moreno/snmpcollector/commit/b940f38277be6e7738b16145ff157a6497e51fca

 You will be able to configure precision from next released version , anyway we have set "seconds" as default precision as SNMP gathering process is not much more precise than that.

 Thank you for your request.
