### ISSUE TITLE
"No measurements associated with the device. Couldn't retrieve metric runtime info"

### ISSUE THREAD

**Issue by tardoe** [toni-moreno/snmpcollector#161]
I have duplicated other devices to create the device in question and all testing / troubleshooting shows that the application can connect to the device, load the index then can't go any further.

A manual SNMPWalk is fine on the device from the host of snmpwalk.

The message: "No measurements associated with the device. Couldn't retrieve metric runtime info." is showing in the runtime screen for this device. I have tried removing and re-adding etc. but nothing changes this.

Excepts from the debug log are attached.

`time="2017-03-31 13:42:02" level=info msg="Beginning gather process for device <device_name> (10.6.1.1)" 
time="2017-03-31 13:42:02" level=info msg="First SNMP connection to host  10.6.1.1 stablished" 
time="2017-03-31 13:42:02" level=debug msg="DEBUG pdu:{Name:.1.3.6.1.2.1.1.1.0 Type:4 Value:[69 120 116 114 101 109 101 88 79 83 32 40 88 54 55 48 86 45 52 56 120 41 32 118 101 114 115 105 111 110 32 49 53 46 53 46 52 46 50 32 118 49 53 53 52 98 50 45 112 97 116 99 104 49 45 50 32 98 121 32 114 101 108 101 97 115 101 45 109 97 110 97 103 101 114 32 111 110 32 84 117 101 32 74 117 110 32 57 32 49 50 58 48 49 58 52 53 32 69 68 84 32 50 48 49 53] Logger:0xc820388460}" 
time="2017-03-31 13:42:02" level=debug msg="DEBUG pdu:{Name:.1.3.6.1.2.1.1.3.0 Type:67 Value:1177858804 Logger:0xc820388460}" 
time="2017-03-31 13:42:02" level=debug msg="DEBUG pdu:{Name:.1.3.6.1.2.1.1.4.0 Type:4 Value:[110 111 99 64 105 120 46 97 115 110 46 97 117] Logger:0xc820388460}" 
time="2017-03-31 13:42:02" level=debug msg="DEBUG pdu:{Name:.1.3.6.1.2.1.1.5.0 Type:4 Value:[112 101 49 46 112 101 114 49] Logger:0xc820388460}" 
time="2017-03-31 13:42:02" level=debug msg="DEBUG pdu:{Name:.1.3.6.1.2.1.1.6.0 Type:4 Value:[87 65 73 88 32 82 111 111 109 32 81 86 49 44 32 80 101 114 116 104] Logger:0xc820388460}" 
time="2017-03-31 13:42:02" level=info msg="Got basic system info <REDACTED> 
time="2017-03-31 13:42:02" level=info msg="SNMP connection stablished Successfully" 
time="2017-03-31 13:42:02" level=debug msg="-----------------Init device measurements from groups 10.6.1.1------------------" 
time="2017-03-31 13:42:02" level=debug msg="SNMP device <REDACTED> has this SELECTED GROUPS: map[Extreme-Peering-Switch:0xc82037dd40]" 
time="2017-03-31 13:42:02" level=debug msg="Selecting from group Extreme-Peering-Switch" 
time="2017-03-31 13:42:02" level=debug msg="Selecting measurements network_interface_counter from group Extreme-Peering-Switch" 
time="2017-03-31 13:42:02" level=debug msg="DEVICE MEASUREMENT:  Extreme-Peering-Switch HOST:  10.6.1.1" 
time="2017-03-31 13:42:02" level=debug msg="MEASUREMENT CFG KEY: network_interface_counter  VALUE  network_interface_counter" 
time="2017-03-31 13:42:02" level=info msg="Loading Indexed values in : network_interface_counter" 
time="2017-03-31 13:42:02" level=debug msg="Looking up column names .1.3.6.1.2.1.31.1.1.1.1 " 
time="2017-03-31 13:42:02" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1001 Type:4 Value:[49 58 49] Logger:0xc820388460}" 
time="2017-03-31 13:42:02" level=debug msg="Got the following OctetString index for [1001/1:1]" 
time="2017-03-31 13:42:02" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1002 Type:4 Value:[49 58 50] Logger:0xc820388460}" 
time="2017-03-31 13:42:02" level=debug msg="Got the following OctetString index for [1002/1:2]" 
time="2017-03-31 13:42:02" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1003 Type:4 Value:[49 58 51] Logger:0xc820388460}" 
time="2017-03-31 13:42:02" level=debug msg="Got the following OctetString index for [1003/1:3]" 
time="2017-03-31 13:42:02" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1004 Type:4 Value:[49 58 52] Logger:0xc820388460}" 
time="2017-03-31 13:42:02" level=debug msg="Got the following OctetString index for [1004/1:4]" 
time="2017-03-31 13:42:02" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1005 Type:4 Value:[49 58 53] Logger:0xc820388460}" 
...
...
time="2017-03-31 13:42:02" level=debug msg="Got the following OctetString index for [1049/1:49]" 
time="2017-03-31 13:42:02" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1050 Type:4 Value:[49 58 53 48] Logger:0xc820388460}" 
time="2017-03-31 13:42:02" level=debug msg="Got the following OctetString index for [1050/1:50]" 
time="2017-03-31 13:42:22" level=error msg="SNMP WALK error: Request timeout (after 5 retries)" 
time="2017-03-31 13:42:22" level=error msg="Error while trying to load Indexed Labels on for measurement network_interface_counter for baseOid .1.3.6.1.2.1.31.1.1.1.1 : ERROR: Request timeout (after 5 retries)" 
time="2017-03-31 13:42:22" level=error msg="Error on measurement initialization on host <REDACTED>: Error: Request timeout (after 5 retries)" 
time="2017-03-31 13:42:22" level=info msg="snmpdevice [<REDACTED>] snmp INIT runtime measurements/filters took [20.245403554s] " 
time="2017-03-31 13:42:22" level=info msg="Waiting 7.477984712s to round until nearest interval... (Cicle = 10 seconds)" 
time="2017-03-31 13:42:30" level=info msg="Init gather cicle" 
time="2017-03-31 13:42:30" level=info msg="snmpdevice [<REDACTED>] snmp pooling took [345ns] SNMP: Gets [0] Errors [0]" 
time="2017-03-31 13:42:30" level=info msg="snmpdevice [<REDACTED>] influx send took [2.242µs]" 
time="2017-03-31 13:42:40" level=info msg="Init gather cicle" 
time="2017-03-31 13:42:40" level=info msg="snmpdevice [<REDACTED>] snmp pooling took [211ns] SNMP: Gets [0] Errors [0]" 
time="2017-03-31 13:42:40" level=info msg="snmpdevice [<REDACTED>] influx send took [1.779µs]" 
time="2017-03-31 13:42:50" level=info msg="Init gather cicle" 
time="2017-03-31 13:42:50" level=info msg="snmpdevice [<REDACTED>] snmp pooling took [274ns] SNMP: Gets [0] Errors [0]" 
time="2017-03-31 13:42:50" level=info msg="snmpdevice [<REDACTED>] influx send took [5.463µs]" 
time="2017-03-31 13:43:00" level=info msg="Init gather cicle" 
`

**Comment by toni-moreno** [comment]
snmpollector is loossing connection while indexing first time.

````
"Error while trying to load Indexed Labels on for measurement network_interface_counter for baseOid .1.3.6.1.2.1.31.1.1.1.1 : ERROR: Request timeout (after 5 retries)"
````
Can you try  increasing the timeout ?.
Which snmp version is the device configured (2c,3?)

 If loosing conection anyway you can activate snmp debug to review snmp connection issues.It will generate a new  snmpdebug  file with lots of exgra data. can you review and/or send us ?

**Comment by tardoe** [comment]
That is using v2c and I do have the debug log level enabled (see above log messages with level=debug).

I further, it appears to be pulling index values just fine, just not grabbing measurements:

`time="2017-04-02 16:50:06" level=debug msg="-----------------Init device measurements from groups <REDACTED>------------------" 
time="2017-04-02 16:50:06" level=debug msg="SNMP device <REDACTED> has this SELECTED GROUPS: map[Extreme-Peering-Switch:0xc8204ca980]" 
time="2017-04-02 16:50:06" level=debug msg="Selecting from group Extreme-Peering-Switch" 
time="2017-04-02 16:50:06" level=debug msg="Selecting measurements network_interface_counter from group Extreme-Peering-Switch" 
time="2017-04-02 16:50:06" level=debug msg="DEVICE MEASUREMENT:  Extreme-Peering-Switch HOST: <REDACTED>" 
time="2017-04-02 16:50:06" level=debug msg="MEASUREMENT CFG KEY: network_interface_counter  VALUE  network_interface_counter" 
time="2017-04-02 16:50:06" level=info msg="Loading Indexed values in : network_interface_counter" 
time="2017-04-02 16:50:06" level=debug msg="Looking up column names .1.3.6.1.2.1.31.1.1.1.1 " 
time="2017-04-02 16:50:06" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1001 Type:4 Value:[49 58 49] Logger:0xc8203f45f0}" 
time="2017-04-02 16:50:06" level=debug msg="Got the following OctetString index for [1001/1:1]" 
time="2017-04-02 16:50:06" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1002 Type:4 Value:[49 58 50] Logger:0xc8203f45f0}" 
time="2017-04-02 16:50:06" level=debug msg="Got the following OctetString index for [1002/1:2]" 
time="2017-04-02 16:50:06" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1003 Type:4 Value:[49 58 51] Logger:0xc8203f45f0}" 
time="2017-04-02 16:50:06" level=debug msg="Got the following OctetString index for [1003/1:3]" 
time="2017-04-02 16:50:06" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1004 Type:4 Value:[49 58 52] Logger:0xc8203f45f0}" 
time="2017-04-02 16:50:06" level=debug msg="Got the following OctetString index for [1004/1:4]" 
time="2017-04-02 16:50:06" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1005 Type:4 Value:[49 58 53] Logger:0xc8203f45f0}" 
time="2017-04-02 16:50:06" level=debug msg="Got the following OctetString index for [1005/1:5]" 
...
...
...
time="2017-04-02 16:50:06" level=debug msg="Got the following OctetString index for [1046/1:46]" 
time="2017-04-02 16:50:06" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1047 Type:4 Value:[49 58 52 55] Logger:0xc8203f45f0}" 
time="2017-04-02 16:50:06" level=debug msg="Got the following OctetString index for [1047/1:47]" 
time="2017-04-02 16:50:06" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1048 Type:4 Value:[49 58 52 56] Logger:0xc8203f45f0}" 
time="2017-04-02 16:50:06" level=debug msg="Got the following OctetString index for [1048/1:48]" 
time="2017-04-02 16:50:06" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1049 Type:4 Value:[49 58 52 57] Logger:0xc8203f45f0}" 
time="2017-04-02 16:50:06" level=debug msg="Got the following OctetString index for [1049/1:49]" 
time="2017-04-02 16:50:06" level=debug msg="received SNMP  pdu:{Name:.1.3.6.1.2.1.31.1.1.1.1.1050 Type:4 Value:[49 58 53 48] Logger:0xc8203f45f0}" 
time="2017-04-02 16:50:06" level=debug msg="Got the following OctetString index for [1050/1:50]" 
t**ime="2017-04-02 16:50:36" level=error msg="SNMP WALK error: Request timeout (after 5 retries)" 
time="2017-04-02 16:50:36" level=error msg="Error while trying to load Indexed Labels on for measurement network_interface_counter for baseOid .1.3.6.1.2.1.31.1.1.1.1 : ERROR: Request timeout (after 5 retries)"** 
time="2017-04-02 16:50:36" level=error msg="Error on measurement initialization on host <REDACTED>: Error: Request timeout (after 5 retries)" 
time="2017-04-02 16:50:36" level=info msg="snmpdevice [<REDACTED>] snmp INIT runtime measurements/filters took [30.235524795s] " 
time="2017-04-02 16:50:36" level=info msg="Waiting 3.687072827s to round until nearest interval... (Cicle = 10 seconds)" 
time="2017-04-02 16:50:40" level=info msg="Init gather cicle" 
time="2017-04-02 16:50:40" level=info msg="snmpdevice [<REDACTED>] snmp pooling took [223ns] SNMP: Gets [0] Errors [0]" 
time="2017-04-02 16:50:40" level=info msg="snmpdevice [pe1.per1] influx send took [7.813µs]" 
time="2017-04-02 16:50:40" level=info msg="DEBUG  ACTIVE <REDACTED> [true] " 
time="2017-04-02 16:50:40" level=info msg="Activating snmp debug for this device" 
time="2017-04-02 16:50:50" level=info msg="Init gather cicle" 
time="2017-04-02 16:50:50" level=info msg="snmpdevice [pe1.per1] snmp pooling took [253ns] SNMP: Gets [0] Errors [0]" 
time="2017-04-02 16:50:50" level=info msg="snmpdevice [pe1.per1] influx send took [4.555µs]" 
time="2017-04-02 16:51:00" level=info msg="Init gather cicle" 
time="2017-04-02 16:51:00" level=info msg="snmpdevice [pe1.per1] snmp pooling took [226ns] SNMP: Gets [0] Errors [0]" 
time="2017-04-02 16:51:00" level=info msg="snmpdevice [pe1.per1] influx send took [4.581µs]"  
`

**Comment by toni-moreno** [comment]
Hi again @tardoe.

Snmp debug is not the same property than device debug log level. It generates another file with only snmp protocol debug that could help us to understand what is happening.

**Comment by tardoe** [comment]
Okay, here we go:

> OID: [.1.3.6.1.2.1.31.1.1.1.1.1044]
> [decodeValue: type is OctetString]
> decodeValue: value is []interface {}{[]uint8{0x31, 0x3a, 0x34, 0x34}}
> OID: [.1.3.6.1.2.1.31.1.1.1.1.1045]
> [decodeValue: type is OctetString]
> decodeValue: value is []interface {}{[]uint8{0x31, 0x3a, 0x34, 0x35}}
> OID: [.1.3.6.1.2.1.31.1.1.1.1.1046]
> [decodeValue: type is OctetString]
> decodeValue: value is []interface {}{[]uint8{0x31, 0x3a, 0x34, 0x36}}
> OID: [.1.3.6.1.2.1.31.1.1.1.1.1047]
> [decodeValue: type is OctetString]
> decodeValue: value is []interface {}{[]uint8{0x31, 0x3a, 0x34, 0x37}}
> OID: [.1.3.6.1.2.1.31.1.1.1.1.1048]
> [decodeValue: type is OctetString]
> decodeValue: value is []interface {}{[]uint8{0x31, 0x3a, 0x34, 0x38}}
> OID: [.1.3.6.1.2.1.31.1.1.1.1.1049]
> [decodeValue: type is OctetString]
> decodeValue: value is []interface {}{[]uint8{0x31, 0x3a, 0x34, 0x39}}
> OID: [.1.3.6.1.2.1.31.1.1.1.1.1050]
> [decodeValue: type is OctetString]
> decodeValue: value is []interface {}{[]uint8{0x31, 0x3a, 0x35, 0x30}}
> Packet sanity verified, we got all the bytes ([36])
> Parsed version [1]
> Parsed community [REDACTED]
> getResponseLength: [16]
> requestID: [1078517674]
> errorStatus: [1]
> error-index: [0]
> vblLength: [2]
> Retry number [1 859531907984]. Last error was: %!v(MISSING)
> Packet sanity verified, we got all the bytes ([36])
> Parsed version [1]
> Parsed community [REDACTED]
> getResponseLength: [16]
> requestID: [1078517675]
> errorStatus: [1]
> error-index: [0]
> vblLength: [2]
> Retry number [2 859531151936]. Last error was: %!v(MISSING)
> Packet sanity verified, we got all the bytes ([36])
> Parsed version [1]
> Parsed community [REDACTED]
> getResponseLength: [16]
> requestID: [1078517676]
> errorStatus: [1]
> error-index: [0]
> vblLength: [2]
> Retry number [3 859533557280]. Last error was: %!v(MISSING)
> Packet sanity verified, we got all the bytes ([36])
> Parsed version [1]
> Parsed community [REDACTED]
> getResponseLength: [16]
> requestID: [1078517677]
> errorStatus: [1]
> error-index: [0]
> vblLength: [2]

Then it continues to do the 5th retry and stops. What exactly is it complaining about?

**Comment by tardoe** [comment]
With SNMP version 2 configured. I have this device working with Cacti currently with no issue.

**Comment by toni-moreno** [comment]
Do you have cacti on the same host than snmpcollector ? 

It seems like something is making  loose the connection when doing bulk walking... we'll try to investigate a little bit more.

Can you paste the output for the  "snmpbulkwalk" response ?

Can you also give us two  tcpdump captures filtering destination host ?"dst host xxxxxxx"
- fist with snmpcollector.
- and the second ona with snmpbulkwalk  tool ?

**Comment by toni-moreno** [comment]
Hi @tardoe any news  on this issue.

 did you test connection with snmpbulkwalk and trace  it with tcpdump ?

**Comment by tardoe** [comment]
Yes, Cacti is on the same host but I have 5 other devices also being collected by snmpcollector that are also being collected by Cacti.

user@host# snmpbulkwalk -v2c -c <REDACTED> 10.6.1.1 .1.3.6.1.2.1.31.1.1.1.1
> IF-MIB::ifName.1001 = STRING: 1:1
> IF-MIB::ifName.1002 = STRING: 1:2
> IF-MIB::ifName.1003 = STRING: 1:3
> IF-MIB::ifName.1004 = STRING: 1:4
> IF-MIB::ifName.1005 = STRING: 1:5
> IF-MIB::ifName.1006 = STRING: 1:6
> IF-MIB::ifName.1007 = STRING: 1:7
> IF-MIB::ifName.1008 = STRING: 1:8
> IF-MIB::ifName.1009 = STRING: 1:9
> IF-MIB::ifName.1010 = STRING: 1:10
> IF-MIB::ifName.1011 = STRING: 1:11
> IF-MIB::ifName.1012 = STRING: 1:12
> IF-MIB::ifName.1013 = STRING: 1:13
> IF-MIB::ifName.1014 = STRING: 1:14
> IF-MIB::ifName.1015 = STRING: 1:15
> IF-MIB::ifName.1016 = STRING: 1:16
> IF-MIB::ifName.1017 = STRING: 1:17
> IF-MIB::ifName.1018 = STRING: 1:18
> IF-MIB::ifName.1019 = STRING: 1:19
> IF-MIB::ifName.1020 = STRING: 1:20
> IF-MIB::ifName.1021 = STRING: 1:21
> IF-MIB::ifName.1022 = STRING: 1:22
> IF-MIB::ifName.1023 = STRING: 1:23
> IF-MIB::ifName.1024 = STRING: 1:24
> IF-MIB::ifName.1025 = STRING: 1:25
> IF-MIB::ifName.1026 = STRING: 1:26
> IF-MIB::ifName.1027 = STRING: 1:27
> IF-MIB::ifName.1028 = STRING: 1:28
> IF-MIB::ifName.1029 = STRING: 1:29
> IF-MIB::ifName.1030 = STRING: 1:30
> IF-MIB::ifName.1031 = STRING: 1:31
> IF-MIB::ifName.1032 = STRING: 1:32
> IF-MIB::ifName.1033 = STRING: 1:33
> IF-MIB::ifName.1034 = STRING: 1:34
> IF-MIB::ifName.1035 = STRING: 1:35
> IF-MIB::ifName.1036 = STRING: 1:36
> IF-MIB::ifName.1037 = STRING: 1:37
> IF-MIB::ifName.1038 = STRING: 1:38
> IF-MIB::ifName.1039 = STRING: 1:39
> IF-MIB::ifName.1040 = STRING: 1:40
> IF-MIB::ifName.1041 = STRING: 1:41
> IF-MIB::ifName.1042 = STRING: 1:42
> IF-MIB::ifName.1043 = STRING: 1:43
> IF-MIB::ifName.1044 = STRING: 1:44
> IF-MIB::ifName.1045 = STRING: 1:45
> IF-MIB::ifName.1046 = STRING: 1:46
> IF-MIB::ifName.1047 = STRING: 1:47
> IF-MIB::ifName.1048 = STRING: 1:48
> IF-MIB::ifName.1049 = STRING: 1:49
> IF-MIB::ifName.1050 = STRING: 1:50
> IF-MIB::ifName.1051 = STRING: 1:51
> IF-MIB::ifName.1052 = STRING: 1:52
> IF-MIB::ifName.1053 = STRING: 1:53
> IF-MIB::ifName.1054 = STRING: 1:54
> IF-MIB::ifName.1055 = STRING: 1:55
> IF-MIB::ifName.1056 = STRING: 1:56
> IF-MIB::ifName.1057 = STRING: 1:57
> IF-MIB::ifName.1058 = STRING: 1:58
> IF-MIB::ifName.1059 = STRING: 1:59
> IF-MIB::ifName.1060 = STRING: 1:60
> IF-MIB::ifName.1061 = STRING: 1:61
> IF-MIB::ifName.1062 = STRING: 1:62
> IF-MIB::ifName.1063 = STRING: 1:63
> IF-MIB::ifName.1064 = STRING: 1:64
> IF-MIB::ifName.1065 = STRING: Management
> IF-MIB::ifName.1000001 = STRING: VirtualRouter0
> IF-MIB::ifName.1000002 = STRING: VirtualRouter1
> IF-MIB::ifName.1000003 = STRING: VirtualRouter2
> IF-MIB::ifName.1000004 = STRING: Default
> IF-MIB::ifName.1000005 = STRING: Mgmt
> IF-MIB::ifName.1000006 = STRING: l0
> IF-MIB::ifName.1000007 = STRING: <REDACTED>
> IF-MIB::ifName.1000008 = STRING: <REDACTED>
> IF-MIB::ifName.1000009 = STRING: <REDACTED>
> IF-MIB::ifName.1000010 = STRING: <REDACTED>
> IF-MIB::ifName.1000011 = STRING: <REDACTED>
> IF-MIB::ifName.1000012 = STRING: <REDACTED>
> IF-MIB::ifName.1000013 = STRING: <REDACTED>
> IF-MIB::ifName.1000014 = STRING: <REDACTED>
> IF-MIB::ifName.1000017 = STRING: <REDACTED>
> IF-MIB::ifName.1000019 = STRING: <REDACTED>
> IF-MIB::ifName.1000021 = STRING: <REDACTED>
> etc.

TCPDumps to come after I test this on another host not running Cacti.
I had a few other things to do to, I'll get back to you in the next few days.

**Comment by tardoe** [comment]
I have the packet captures you're after.
Email me at the email address on my profile and I'll share.

A normal SNMPBulkGet appears to work fine, request for the index ID returns the max configured number of OIDs. This was the command run:
`snmpbulkget -Cr50 -v2c -c <community> 10.6.1.1 .1.3.6.1.2.1.31.1.1.1.1`

The SNMPCollector on the other hand, does the same request, gets all the indexes and then attempts to grab 1050 and returns the error code "tooBig". 

Thoughts?

**Comment by tardoe** [comment]
So, resolution:

Extreme Networks devices won't fragment SNMP packets by default. Apply the below to ensure that frames with payload >1500 bytes are fragmented rather than returning a tooBig error.
```
configure snmp compatibility get-bulk reply-too-big-action standard
configure snmp compatibility ip-fragmentation allow
```

As a side question, to further improve performance on devices with lots of interfaces (I have a device with 8 slots with 48x10Gbit interfaces in each), can there please be a tuneable option for the SNMPBulkGet batch size? It appears that the library defaults to 50 but I think performance would be be improved if this was increased for devices with lots of interfaces (according to my rudimentary testing with `snmpbulkget` and `time`).

**Comment by toni-moreno** [comment]
The tuneable parameter is "MaxRepetitions" that is 50 in snmpcollector and 10 in net-nsmp tools.
Could you reproduce the error message if you add this parameter "-Cr50" to your snmpbulkwalk query ?

**Comment by tardoe** [comment]
Sure can.

Without the tuned options on the device, it generates payloads too large. 

Thanks for that!

Regards,

Tim Raphael

**Comment by toni-moreno** [comment]
I  we can  be sure the default MaxRepetitions is the source of the problem we  will  add a new option to the device configuration to tune it.

I will also open an issue to the gosnmp developers because of there is  no error and no log in the debug output that point us to this problem.  IMHO "Request timeout (after 5 retries)" is not a good message error and doesn't give us any hint on the source problem.

**Comment by tardoe** [comment]
Nice.

Thanks for the help! Now I've got this going, a puppet module is next up. Had anyone use puppet against snmpcollector before?

Regards,

Tim Raphael

**Comment by toni-moreno** [comment]
Hi @tardoe I've added this new option. I expect we can release new version next week.   About puppet... nobody did before , sure! But you are welcome to do it first.

**Comment by tardoe** [comment]
Excellent!

Thank you very much! 

Regards,

Tim Raphael

**Comment by toni-moreno** [comment]
Hi @tardoe I've released a new version with the MaxRepetitions config option.  Thank you very much for your great analysis on this problem.

**Comment by tardoe** [comment]
Reopening with some new comments. I have a device that polls 4700 metrics in 22 seconds with max-repetitions set to the default (50). After changing to 100, I don't see any change in this performance (where I do when running the same snmpbulkwalk from net-snmp - about a 30% improvement). I have looked through debug logs and I can't find anywhere to confirm that max-repetitions=100 is actually being used.

**Comment by toni-moreno** [comment]
Hi @tardoe I've just added the ability to change max repetitions online from the webui. Now you can test different setups for different devices without  needs to restart

**Comment by toni-moreno** [comment]
Hi @tardoe , I would like to add documentation about snmpcollector automation capabilities. have you published your  snmpcollector puppet module anywhere as opensource project? we would like to add a link on our online wiki?

**Comment by tardoe** [comment]
As I built this for my employer, we're just sorting out the organisational side of publishing it. We still fully intend to do so.

Regards,

Tim Raphael
