### ISSUE TITLE
[Feature Request] New data source cooked type DEC > ASCII for IndexOID

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#163]
Hi,

It woulld be great if you could add new cooked type for the datasource which would convert IndexOID decimal values to ASCII characters like below.
OID:
`1.3.6.1.4.1.12345.1.100.101.102.97.117.108.116`
IndexOID:
`1.3.6.1.4.1.12345.1`
and index part where:
`100.101.102.97.117.108.116` get's translated (with the dots skipped) to "**default**" which is then saved as the tag value. 

I guess that implementation of the MIB file processing will be far more complicated and time consuming then the above. What do you think about implementing this?

**Comment by toni-moreno** [comment]
this FR is related to this other https://github.com/toni-moreno/snmpcollector/issues/125 where we need to do a TAGNAME transformation.

Anyway I suggest review your MIB device looking for an Index OID . 
We have solved a situation like that with a DNS box with Indexes defined as dot separated ASCII  values. But we could get the correct tag name (the zone name in  the DNS) from another OID witch has exactly the name as the Index is.

following your example, are you sure there is not a Field (X) where you can get  that?
````
1.3.6.1.4.1.12345.X.100.101.102.97.117.108.116 = "default"
 ````
???

**Comment by pavleec** [comment]
Unfortunately in my case there is no separate index field which I would like to use instead. The mentioned MIB is fully SMIv2 strict thus all indexes are declared as not-accessible. Now I'm storing **$IDX1** as the regular OID index part for tag values, but it would be great to have for example **$DEC_TO_ASCII_IDX1** that would be able to convert them to ASCII string.

**Comment by toni-moreno** [comment]
Hi @pavleec I will try to add transformation capability on the variable ,  Suppose 
You have in your OID 1.3.6.1.4.1.12345.1.100.101.102.97.117.108.116  with "100.101.102.97.117.108.116" as Index and stored in $IDX1

`${IDX1:DEC2ASCII}`  will return the string  "default" as you suggested
or
`${IDX1/[^.*].*/\1}` will return "100" (regex)
or 
`${IDX2:DOT[2:3]}` will return "102.97" (dot separated fields) 

with this syntax we can also solve (https://github.com/toni-moreno/snmpcollector/issues/125) and perhaps add other interesting index/values trasformation tool over indexes/value in order  to create out tags.
Do you have another  good suggestion related to this  ?

**Comment by pavleec** [comment]
I think that's even more I/we can think of :) Especially regex with capturing groups support would be very flexible. Actually today I just came across exactly the same usage as your example where I'm getting idexes such as `15.1.0`, `15.2.0` (and so on) and I would like to extract only the second digit which is the slot number. Both regex and dot option would solve it perfectly. Can't wait to test it then 👍

**Comment by toni-moreno** [comment]
Hi @pavleec after reviewing some other special snmp tables with "extrange" indexes I've changed a little how to define a custom  format.

From now it will be

### variable definition format

`${VAR|SELECTOR|TRANSFORMATOR}`

* VAR : the variable source, could be referenced several times in the same definition
* SELECTOR: (by default the complete variable string) will select a bit of the VARIABLE, could be void string and the default value will be selected
* TRANSFORMATOR (by default STRING) will apply a transformation on the previously selected bit of variable, could be void string and the default value will be selected

$VAR will be equivalent to ${VAR|ALL|STRING} and also to ${VAR||}

#### defined selectors 
* ALL: complete string
* DOT[X:Y] : splits variable in an array of numbers and select only from the Xth to the Yth value, if X is omitted 0 will be chosen , if  Y is omitted the last element on the splitted array will be chosen , in this mode DOT[0:] is equivalent to ALL. Counter always begins from 0 and both X and Y position will be included in the final selection

#### Defined transformations 

* STRING : return the selected value as an string
* DEC2ASCII: decode a doted separated string with numbers as ascii bytes of a string ("100.101.102.97.117.108.116" will be "default")
 
### Example

We can use inetCidrRouteIfIndex as example:
The following is the ouput from one row of the table with "snmpwalk".
````
IP-FORWARD-MIB::inetCidrRouteIfIndex.ipv4."0.0.0.0".0.2.0.0.ipv4."10.0.2.2" = INTEGER: 2
````
equivament to that.(I've separteade baseOID from Index)
````
BaseOID[1.3.6.1.2.1.4.24.7.1.7]+ INDEX[.1.4.0.0.0.0.0.2.0.0.1.4.10.0.2.2] = INTEGER: 2
````
when looking for index info here inetCidrRouteEntry (http://oid-info.com/get/1.3.6.1.2.1.4.24.7.1), we have found the following
```
INDEX {
inetCidrRouteDestType, ipv4(1), ipv6(2), ipv4z(3), ipv6z(4)) = 1
inetCidrRouteDest,	= 4 - 0.0.0.0
inetCidrRoutePfxLen,    = 0.2
inetCidrRoutePolicy,    = 0.0
inetCidrRouteNextHopType = 1
inetCidrRouteNextHop  = 4 -> 10.0.2.2
}
````
In this case we would like by example take RouteDest and RouteNextHop as IndexTAG with

```
${IDX1|DOT[2:5]|STRING} -> ${IDX1|DOT[12:15]|STRING}
````
this will equivalent to 
````
${IDX1|DOT[2:5]|} -> ${IDX1|DOT[12:15]|}
````
And the output result will be
````
0.0.0.0 -> 10.0.2.2
````

**Comment by toni-moreno** [comment]
We can now do that!!

 The previously example with selector in inetCidrRouteIfIndex is not correct because DOT[X:Y] depends on the IP version defined in the route. (ivp4 vs ipv6 ) but I hope it can be a good example on how to use this new feature.

**Comment by toni-moreno** [comment]
@pavleec @sbengo , it is pending document this new feature in our wiky

**Comment by pavleec** [comment]
Great job and thanks for a quick implementation. I've already tested both DOT[X:X] with ASCII2DEC and both are working properly.
