### ISSUE TITLE
SNMP v3 not working?

### ISSUE THREAD

**Issue by TeraHz** [toni-moreno/snmpcollector#167]
I can't get SNMP v3 to talk to my devices. What does the _%!v(MISSING)_ message mean?

> Packet sanity verified, we got all the bytes ([108])
> Parsed version [3]
> Parsed message ID [2052823398]
> parsed msg flags []
> Parsed security model [3]
> Parsed authoritativeEngineID 
>                              !ݞÀ
> Parsed authoritativeEngineBoots 33
> Parsed authoritativeEngineTime 70414894
> Parsed userName 
> Parsed authenticationParameters 
> Parsed privacyParameters 
> Parsed contextEngineID [
>                         !ݞÀ]
> Parsed contextName []
> getResponseLength: [34]
> requestID: [1774551833]
> errorStatus: [0]
> error-index: [0]
> vblLength: [20]
> OID: [.1.3.6.1.6.3.15.1.1.4.0]
> [decodeValue: type is Counter32]
> decodeValue: value is []interface {}{0x4163}
> Retry number [1 842356327920]. Last error was: %!v(MISSING)
> Retry number [2 842355568656]. Last error was: %!v(MISSING)
> Retry number [3 842353819744]. Last error was: %!v(MISSING)
> Retry number [4 842357037968]. Last error was: %!v(MISSING)
> Retry number [5 842358043200]. Last error was: %!v(MISSING)

**Comment by toni-moreno** [comment]
Hi @TeraHz , snmpcollector is currently working with snmp v1 v2 and v3 . But I can not say you what is happening with your device, but it seems like connection is closed. Perhaps it is a very slow device and it is spend in its response more than timeout seconds . could you test again with a greater timeout ? 

Anyway if you want recompile yourself I've updated the main snmp library "gosnmp" with latest fixes . Perhaps you will see more debug info in your snmp debug file.

You can also get  net dump with tcpdump and let me review with wireshark to see what is happening with the snmp protocol.

**Comment by TeraHz** [comment]
Hi @toni-moreno,
I tried to recompile, but when I copy snmpcollector to the docker container, it fails with `/start.sh: line 2: ./bin/snmpcollector: not found`. Very odd. I can run it on the host but not inside the container. Tried compiling with CGO_ENABLED=0 but go_sqlite3 fails (as it requires CGO_ENABLED=1).
Do I need to run `build-static` for docker?

**Comment by TeraHz** [comment]
Static linking mystery. I'm new to go, as you can tell:

>  go build --ldflags '-extldflags "-static"' main.go
> command-line-arguments
> /usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
> /usr/bin/ld: cannot find -ldl
> /usr/bin/ld: cannot find -lpthread
> /usr/bin/ld: cannot find -lc
> collect2: error: ld returned 1 exit status

**Comment by TeraHz** [comment]
Well, I found the only switch we have that doesn't have snmp v3 enabled... the collector works just fine, thanks for the time!
