### ISSUE TITLE
[Bug] MySQL backend not working

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#169]
Hi,

I've tried to switch from sqlite3 to mysql backand but it's not working and probably hasn't been tested yet.
Here is what I've identified so far:

Configuration file show the following example:
`host = 127.0.0.1:3306`
When it's configured like this snmpcollector reports an error message during startup:
`snmpcollector[9638]: time="2017-04-10 11:15:57" level=fatal msg="Fail to sync database InfluxCfg: Default addr for network '127.0.0.1:3306' unknown\n"`

After little debugging and checking what's used in `database.go` I've found the the proper syntax for go-sql-driver/mysql should look like below:
`user:password@tcp(localhost:port)/dbname?`
and when I've changed the host to:
`host = "tcp(localhost:3306)`
it went one step furter but wasn't able to connect due to lack of the password (which is defined in config)
`time="2017-04-10 12:28:43" level=fatal msg="Fail to sync database InfluxCfg: Error 1045: Access denied for user 'snmpcollector'@'localhost' (using password: NO)\n"`

Moreover in the `/config/snmpcollector_schema.sql` when indexes don't contain a key length:
``CREATE UNIQUE INDEX `UQE_meas_filter_cfg_id` ON `meas_filter_cfg` (`id`);``
 mysql reports an error:
``BLOB/TEXT column 'id' used in key specification without a key length ``
It's ok when defined like below:
``CREATE UNIQUE INDEX `UQE_meas_filter_cfg_id` ON `meas_filter_cfg` (`id`(255));``

**Comment by toni-moreno** [comment]
Hi @pavleec , you are rigth we wrote code but never tested before. I will  try to fix in  next days.

About SQL, perhaps we should add two different sql files one for each db if  mysql "SQL" syntax is not full compatible with sqlite3.

Thank you for reporting this.
