### ISSUE TITLE
[Bug] Inconsisent API Usage - GET vs PUT

### ISSUE THREAD

**Issue by tardoe** [toni-moreno/snmpcollector#170]
When reading and writing to the API, I get null configuration applied when I do the following:

`GET /api/cfg/snmpdevice/<device_name>`

The returned JSON contains parametres such as SNMPv3 options that are not in use (set to zero or ""). Once I change part of the configuration (e.g. change the description) and do the following:

`PUT /api/cfg/snmpdevice/<device_name>`

I get a blank configuration created for <device_name> requiring a manual delete from the SQLite DB.

Inspecting how the frontend does this, it conditionally sends JSON with the SNMPv3 params (and a few others) if they're in use. Otherwise, it doesn't send them. A JSON diff is below showing what the web interface POSTs back vs what I'm attempting:

`
2.4.0 :043 > diff = JsonDiff.diff from_device_get,web_interface
2.4.0 :045 > PP.pp diff
[{"op"=>"remove", "path"=>"/Repeat"},
 {"op"=>"remove", "path"=>"/V3SecLevel"},
 {"op"=>"remove", "path"=>"/V3AuthUser"},
 {"op"=>"remove", "path"=>"/V3AuthPass"},
 {"op"=>"remove", "path"=>"/V3AuthProt"},
 {"op"=>"remove", "path"=>"/V3PrivPass"},
 {"op"=>"remove", "path"=>"/V3PrivProt"},
 {"op"=>"remove", "path"=>"/MaxRepetitions"},
 {"op"=>"remove", "path"=>"/ConcurrentGather"},
 {"op"=>"remove", "path"=>"/LogFile"}]
`

The field above are all set to their default when pulling from the API.

Given the conditional logic required to talk to the API correctly isn't exposed as part of the API, I would recommend that it would be better design practise to allow updating of all device parametres in a PUT.

**Comment by toni-moreno** [comment]
Hi @tardoe , I'm sorry there is not enougth documentation on the API  REST. ( and we have pending implement a nuew  a token authentication to simplify API operations).

As you can see in the following code  ( https://github.com/toni-moreno/snmpcollector/blob/master/pkg/webui/webserver.go#L236-L243 ) updates should be done with a PUT HTTP Query.

Operation on each object configuration type are usually:

* __list all objects :__  GET /
* __get config for object with id =ID:__ GET /"ID"
*  __ADD new object with id= ID :__ POST "/ID" ( and attach config in json format)
* __Update object with id= ID :__ PUT /"ID" ( and attach config in json format)
* __Delete object with id=ID :__ DELETE /"ID"

I hope you can continue working with our API.

Remember we have plans to add a new token based authentication.

**Comment by tardoe** [comment]
Thanks Toni,

I am doing a PUT to update but I’ve just edited my Issue to correctly reflect the behaviour.

I do a GET on a device then turn the JSON right back around as a PUT and the device is removed (nullified in the DB leaving an empty record).

Regards,

Tim

**Comment by toni-moreno** [comment]
Can you send us snmpcollector.log and http_access.log after configure them in debug mode in your config.toml and reproduce the problem  please?

**Comment by tardoe** [comment]
Right, so I figured out my issue but uncovered some potentially unwanted behaviour...

I wasn't sending my payload as JSON but as form encoded values (incorrect). This resulted in an empty body that would overwrite all fields and create an empty record. I would suggest that you validate for a valid JSON body and send a 400 if not found. To rectify the result of this bad request, you need to issue "DELETE from snmp_device_cfg WHERE ID IS NULL;" on the database to clean the null / blank device record.
