### ISSUE TITLE
I cound not set mysql backend 

### ISSUE THREAD

**Issue by khanga6tm** [toni-moreno/snmpcollector#179]
Here is my config for mysql 
_[database]

 type = "mysql"

 host = "localhost:3306"
 user = "snmpcoluser"
 password = "snmpcolpass"
 name = "snmpcollector"
 debug = false_

and when I run the command: snmpcollector -config /etc/snmpcollector/config.toml
It return to me an error: Fail to sync database InfluxCfg: Default addr for network 'localhost:3306' unknown

anyone please help me to solve it?

**Comment by toni-moreno** [comment]
hi @khanga6tm . Could you tell us which version are you running? We have fixed mysql issues some days ago , and perhaps you are working with an old version

you could see your binary version  with ./snmpcollector -version

**Comment by pavleec** [comment]
Hi @khanga6tm. Please check #169 . The recent v.0.6.6 will only accept host defined as below:
`host = "tcp(localhost:3306)"`
Need to wait for the 0.7.0 build to have it fixed.

**Comment by khanga6tm** [comment]
First, I would like to thank all of you to support me. 

My version is: snmpcollector v0.6.6 (git: a018a9a ) built at [2017-04-08 12:56:36]

And I try the WA as Pavleec, It pass my issue but it face to new issue. 

system response: Fail to sync database InfluxCfg: Error 1045: Access denied for user 'root'@'localhost' (using password: NO)

snmpcollector could not get the password field on config file.

**Comment by sbengo** [comment]
Hi @khanga6tm , we are really sorry, but as @pavleec says on the related issue #169 you will keep having more problems accessing MySQL db...

We recommend you to wait until the next release (very soon) or try to compile yourself the code (wait until tomorrow, we have some fixes to do!).

Thanks and sorry!

**Comment by toni-moreno** [comment]
As @sbengo  told you this problem has been fixed and will be available on the next release
