### ISSUE TITLE
[Feature request] InfluxDB timestamp = starttime even interval?

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#180]
Hi,

For some use cases (when dynamic GROUP BY interval is used in Grafana for InfluxDB queries) it might be very usefull to have an option which would allow to use even intervals for timestamp value instead of real end of polling timestamps? For instance if device polling interval is set to 30s we would use:

`1. cycle 14:58:00 - 1492700280`
`2. cycle 14:58:30 - 1492700310`
`3. cycle 14:59:00 - 1492700340`
`4. and so on...`

What do you think about implementing such feature per InfluxDB server destination or per device? It could be a checkbox option like "Use equal intervals for timestamp".

**Comment by toni-moreno** [comment]
let me know if I've understand you request.

As I  see , you are requesting for timestamp alignment to the polling interval?  

We are already doing this alignment here (https://github.com/toni-moreno/snmpcollector/blob/master/pkg/agent/device/snmpdevice.go#L502-L503)

Or perhaps you are requesting force the timestamp for measurements prior to getting related measurement  data after aligned ? Why do you need that ? are you viewing holes in your grafana panels? with what interval ?

**Comment by pavleec** [comment]
Sorry Toni. Everything's fine with the snmpcollector timestamp alignment. I've just set by mistake different time intervals for the devices which I then used to create aggregated traffic graph. That caused an discrapency  and above issue.  Please close this issue.

**Comment by toni-moreno** [comment]
Ok @pavleec thank you!
