### ISSUE TITLE
[Bug] WebUI SNMP devices

### ISSUE THREAD

**Issue by Smenon10** [toni-moreno/snmpcollector#186]
Small bug in the SNMP devices in the WebUI.
I noticed that if I import data from a json file that looks like below, I'm unable to click "edit item" under SNMP devices. "view item", "export item", "remove item" works fine just edit item that's unable to be clicked. 

{
"Info": {},
  "Objects": [
    {
      "ObjectTypeID": "snmpdevicecfg",
      "ObjectID": "msr-a5a-as11",
      "Options": null,
      "ObjectCfg": {
        "ID": "msr-a5a-as11",
        "Host": "msr-a5a-as11.xxx.xxx",
        "Port": 161,
        "Retries": 5,
        "Timeout": 20,
        "Repeat": 0,
        "Active": true,
        "SnmpVersion": "2c",
        "Community": "xxxxx",
        "DisableBulk": false,
        "MaxRepetitions": 50,
        "Freq": 20,
        "UpdateFltFreq": 60,
        "ConcurrentGather": true,
        "OutDB": "influx1",
        "LogLevel": "info",
        "SnmpDebug": false,
        "DeviceTagName": "switch",
        "DeviceTagValue": "id",
        "MeasurementGroups": [
          "MG_network32bits"
        ]
      }
    }
}

It seems like you cant remove certain empty fields from the json file. If i use a full option file, it works.

{
  "Info": {},
  "Objects": [
    {
      "ObjectTypeID": "snmpdevicecfg",
      "ObjectID": "msr-a5a-as02",
      "Options": null,
      "ObjectCfg": {
        "ID": "msr-a5a-as02",
        "Host": "msr-a5a-as02.xxx.xxx",
        "Port": 161,
        "Retries": 5,
        "Timeout": 20,
        "Repeat": 0,
        "Active": true,
        "SnmpVersion": "2c",
        "Community": "piuSh0Wa",
        "V3SecLevel": "",
        "V3AuthUser": "",
        "V3AuthPass": "",
        "V3AuthProt": "",
        "V3PrivPass": "",
        "V3PrivProt": "",
        "DisableBulk": false,
        "MaxRepetitions": 50,
        "Freq": 20,
        "UpdateFltFreq": 60,
        "ConcurrentGather": true,
        "OutDB": "influx1",
        "LogLevel": "info",
        "LogFile": "",
        "SnmpDebug": false,
        "DeviceTagName": "switch",
        "DeviceTagValue": "id",
        "ExtraTags": [
          ""
        ],
        "Description": "",
        "MeasurementGroups": [
          "MG_network32bits"
        ],
        "MeasFilters": null
      }
    }
  ]
}

**Comment by sbengo** [comment]
Hi, thanks for reporting this.

I will review this later, meantime, can you provide us more information?

- Is there any exception when you load SNMPDevices section? (Chrome dev tools)

- Can you attach snmpcollector.log and sql.log when you are importing the device with deleted files?

- What does it mean that you are unable to click on `edit`? If you click nothing happens? Can you attach web console, snmpcollector.log and sql.log output when you click on edit?

Thank you!!!

**Comment by Smenon10** [comment]
Hello,
I will gather the information and provide you with what I can. The workaround is the import the full json file without removing any empty fields. 

For the edit part, I'm able to click on it however nothing happens. On the web console, it shows nothing abnormal meaning if I click on view or edit there is no difference in the web console error wise.

**Comment by Smenon10** [comment]
console log:

ID:  msr-a5a-as01
influxservercfg.service.ts:42 MAP SERVICE [Object]
influxservercfg.service.ts:46 FOREACH LOOP Object {ID: "influx1", Host: "10.129.10.95", Port: 8086, DB: "snmpcollector", User: "snmp"…} influx1
snmpdevicecfg.component.ts:443 Object {ID: "influx1", Host: "10.129.10.95", Port: 8086, DB: "snmpcollector", User: "snmp"…}
snmpdevicecfg.component.ts:448 DONE
measgroupcfg.service.ts:37 MAP SERVICE [Object, Object, Object, Object]
measgroupcfg.service.ts:41 FOREACH LOOP Object {ID: "MG_network32bits", Measurements: Array(1), Description: ""} MG_network32bits
measgroupcfg.service.ts:41 FOREACH LOOP Object {ID: "netscaler_vserver", Measurements: Array(1), Description: ""} netscaler_vserver
measgroupcfg.service.ts:41 FOREACH LOOP Object {ID: "netscaler_cspolicy", Measurements: Array(1), Description: ""} netscaler_cspolicy
measgroupcfg.service.ts:41 FOREACH LOOP Object {ID: "ipsla", Measurements: Array(1), Description: ""} ipsla
snmpdevicecfg.component.ts:426 Object {ID: "MG_network32bits", Measurements: Array(1), Description: ""}
snmpdevicecfg.component.ts:426 Object {ID: "netscaler_vserver", Measurements: Array(1), Description: ""}
snmpdevicecfg.component.ts:426 Object {ID: "netscaler_cspolicy", Measurements: Array(1), Description: ""}
snmpdevicecfg.component.ts:426 Object {ID: "ipsla", Measurements: Array(1), Description: ""}
snmpdevicecfg.component.ts:431 DONE
measfiltercfg.service.ts:45 MAP SERVICE null
snmpdevicecfg.component.ts:464 DONE

sql/snmpcollector log below

[logs.zip](https://github.com/toni-moreno/snmpcollector/files/947366/logs.zip)

**Comment by sbengo** [comment]
Hi @Smenon10 , sorry that I couldn't solve it yesterday.

It seems that if `ExtraTags` field is not set when importing, the SNMPCollector sets a `null` value on the configuration DB. The front end was crashing when, on `Edit` device, tries to do a `join()` of a `null` value.
