### ISSUE TITLE
[Bug] Getting logged out only when clicking SNMP Devices

### ISSUE THREAD

**Issue by Smenon10** [toni-moreno/snmpcollector#191]
Hello,
I'm running into another bug where when I click on SNMP devices, it logs me out. The process isn't crashing this time!
I've attached logs below.
[logs.zip](https://github.com/toni-moreno/snmpcollector/files/955135/logs.zip)

**Comment by sbengo** [comment]
Hi @Smenon10 , quite strange, its giving you a `403 Forbidden` when you try to get `SNMPdevices` but `Runtime` is loading okey.

So to get more information:
- Did you do something before this behaviour?

- Can you see if there is some error on `stderr.log`? Can you attach it?

- Can you open `Chrome Devs` and activate the option `Preseve Log` on `Console` tab and `Network` tab and see if there are any exception when you click on "SNMPDevice from menu"?
Example:
![image](https://cloud.githubusercontent.com/assets/13196237/25389776/cb1807b8-29d1-11e7-8323-7a46055dab94.png)

![image](https://cloud.githubusercontent.com/assets/13196237/25389800/d5614fea-29d1-11e7-8968-a1f840c060aa.png)

After get all requested information, try to restart the agent and  see you have still the problem.

Sorry and thank you!

**Comment by Smenon10** [comment]
I tried to fix some OID metrics but that's it. 
the stderr.log is the snmpcollector.log in the zip file
No weird exception other than the 403 forbidden in the console/network tab.

**Comment by toni-moreno** [comment]
Can you review in your browser you are getting the session  cookie after your login request?

**Comment by Smenon10** [comment]
After login

Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,fr;q=0.6
Connection:keep-alive
Cookie:snmpcollector-sess-my_instance_cookie=a43876157b017e86

After I click the snmpdevices

Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,fr;q=0.6
Connection:keep-alive
Cookie:snmpcollector-sess-my_instance_cookie=e34a6bb76f3f0427; snmpcollector-sess-my_instance_cookie=a43876157b017e86

**Comment by toni-moreno** [comment]
It is not getting the cookie and it is sending it again.

Are you accesing to the collector thought a proxy?

Can you test change "my_instance_cookie" in the config.toml by something shorter like "01" and restart the collector?

**Comment by Smenon10** [comment]
Changing "my_instance_cookie" to "01" and restart snmpcollector, it seems to have fixed the issue. Not sure how or why though!

**Comment by toni-moreno** [comment]
I've tested the same configuration  with "my_instance_cookie" and It is working ok for me. Perhaps a "hidden" forbidden character was configured in a mistake. 

I will close this issue
