### ISSUE TITLE
SNMPv1 - Community is Missing

### ISSUE THREAD

**Issue by jackson-tim** [toni-moreno/snmpcollector#193]
When SNMP v1 is used, no community is passed to GoSNMP, and the admin UI does not let you configure one. 

Starting at Line 401: 
https://github.com/toni-moreno/snmpcollector/blob/e1cfe9faaeba7cc950e6d4456a39b681061fd7d7/pkg/data/snmp/snmp.go

Starting @ Line 119: 
https://github.com/toni-moreno/snmpcollector/blob/5faea76eb050f630862bb362cf81f9d60c27e08b/src/snmpdevice/snmpdeviceeditor.html

**Comment by toni-moreno** [comment]
Hi @jackson-tim thank you to report this bug. 

We will fix ASAP.
