### ISSUE TITLE
I could not add new device

### ISSUE THREAD

**Issue by khanga6tm** [toni-moreno/snmpcollector#195]
Hi all,

I face a new issue when add a device to snmpcollector. Pls help me to solve it.
![image](https://cloud.githubusercontent.com/assets/27798807/25475890/7b72e150-2b62-11e7-9030-e59cb271424f.png)

and here is my version on Centos server
![image](https://cloud.githubusercontent.com/assets/27798807/25475978/c2fd06e0-2b62-11e7-9989-9ed130e38388.png)

Thanks

**Comment by toni-moreno** [comment]
Hi @khanga6tm ,  this message means you are configuring MaxRepetitions out of its range  (1-255).

Can you confirm us you can configure this feature with its default value = 50 ?

**Comment by khanga6tm** [comment]
Thanks for your support. 

I realized a situation about your web form. Your web form will accept the first value on textbox. 

Tip: submit the form and open it again to change.
