### ISSUE TITLE
I could not get create a new custom filter,

### ISSUE THREAD

**Issue by khanga6tm** [toni-moreno/snmpcollector#197]
Hi Authors,

Your tool is great and it is a very important piece in my total solution. I help me to solve about management problem with network devices. But It is so hard to use. I research it a few days to control it. 
Sorry to bother you, but it took a lot of my time to setup the 1st gathering information of network device and send to Influxdb. 

Here is my configuration and my issue. Pls help me to pass it, I was here 2 days. 
First: I declared a connection to my Influxdb
![image](https://cloud.githubusercontent.com/assets/27798807/25521303/3e42461e-2c29-11e7-8cca-3fb09ada88e4.png)

Second: I connect to a Cisco network device
![image](https://cloud.githubusercontent.com/assets/27798807/25521352/6429a412-2c29-11e7-9054-fd61a0dc0f51.png)

Third: Created a new IOD condition, Metric
![image](https://cloud.githubusercontent.com/assets/27798807/25521394/8f6568b4-2c29-11e7-8d81-d5178ff28e92.png)
![image](https://cloud.githubusercontent.com/assets/27798807/25521437/b74c5b1c-2c29-11e7-9e16-ab5db79d8aaa.png)

4th: Created a Influx measurement,
![image](https://cloud.githubusercontent.com/assets/27798807/25521446/c4465796-2c29-11e7-89fc-91851f6beeae.png)

5th: Created a group Cisco and snmp measurement to it
![image](https://cloud.githubusercontent.com/assets/27798807/25521457/dc6829e4-2c29-11e7-998a-2e4e11b224af.png)

6th: created a mueasument filter with all value above
![image](https://cloud.githubusercontent.com/assets/27798807/25521475/f7a654ba-2c29-11e7-8c96-335cd755869c.png)

7: create a new customer filer and face to error

![image](https://cloud.githubusercontent.com/assets/27798807/25521695/d7f693e0-2c2a-11e7-9eac-a4a1a1a9fecb.png)

**Comment by sbengo** [comment]
Hi @khanga6tm , thanks for the detailed explanation.

`Custom Filters` are the way to create a filter with custom items whom are selected by a query or set by the user. In order to do that, those filters must be defined on a related device with some measurement group associated.

- Did you add the Measurement Group `Cisco` to your device with ID: `VHT_T8_SW02.ho.vpb.com.vn`?

I know it is so basic info... but we have an example in our wiki which may be useful for you: [Cisco Catalyst basic example](https://github.com/toni-moreno/snmpcollector/wiki/Example:-Configuring-Cisco-Catalyst-Switch)

Thanks,
Greetings!

**Comment by khanga6tm** [comment]
Thanks for your support, sorry for delay. I fixed it yesterday. 

Now I got data from Cisco device but I had 3 value and I tried to find out what is it 2 days, the result is nothing from Internet.

anyone could help me to explain its meaning
![image](https://cloud.githubusercontent.com/assets/27798807/25560953/7ffdbc86-2d15-11e7-8285-4529d0d05445.png)

**Comment by sbengo** [comment]
Hi @khanga6tm , I'm glad you could configure your `Custom Filter`!

I suppose that "blue area" means the blue square that you marked on your screenshot.

Cisco is able to return you information about different memoryPools. The different values are under the OID entry:  `1.3.6.1.4.1.9.9.48.1.1.1.5`, which belongs to the table `ciscoMemoryPoolEntry (1.3.6.1.4.1.9.9.48.1.1.1)`

The values that you marked on the `blue square` are the indexes given by cisco to allow you to query those different values in all the `ciscoMemoryPoolEntry` table entries.

For example, if you a snmpwalk over the entry: `ciscoMemoryPoolName (1.3.6.1.4.1.9.9.48.1.1.1.2)` you will obtain the following values:

Base OID | CisoMemPool index | Value
-----------| ----------------------| -------
 1.3.6.1.4.1.9.9.48.1.1.1.2 | 1 | myCiscoMemPool 1
1.3.6.1.4.1.9.9.48.1.1.1.2 | 2 | myCiscoMemPool 2
1.3.6.1.4.1.9.9.48.1.1.1.2 | 20 | myCiscoMemPool 3

So with those Names in mind, your given query will show you the bytes used by every memoryPool:

MemoryPool Name | Base OID | CisoMemPool index | Value | 
----------------------| -----------| -----------------------|-------
myCiscoMemPool 1 | 1.3.6.1.4.1.9.9.48.1.1.1.5 | 1 | 18984652 
myCiscoMemPool 2 | 1.3.6.1.4.1.9.9.48.1.1.1.5 | 2 | 2385708
myCiscoMemPool 3 | 1.3.6.1.4.1.9.9.48.1.1.1.5 | 20 | 40


Regards!

**Comment by khanga6tm** [comment]
Thanks for all your help!
