### ISSUE TITLE
[Question] Is there a way through API to update multiple SNMP devices at once?

### ISSUE THREAD

**Issue by Smenon10** [toni-moreno/snmpcollector#198]
I'll elaborate a bit. 

I added a new measurement group that I want to add to multiple devices. I know I can add a PUT for a single device but is there a way for multiple devices?

Thanks

**Comment by toni-moreno** [comment]
Hi @Smenon10  rigth now @sbengo is already working in improve the WEBUI to make the same change over several objects at once.

But we have not plans to modify the REST API  to add this new feature IMHO REST API should be used  together  with a  orchestration/automation system. And I'm sure all automation systems ( or a simple shell script with curl ) has the ability to add iterations on any config change. ( a `do while` in bash will runs ok).

let me know if  you can do it in your use case.  

Thank you very much.

**Comment by Smenon10** [comment]
Yep, this is fine, thanks!
