### ISSUE TITLE
Could not edit or delete SNMP Devices item

### ISSUE THREAD

**Issue by khanga6tm** [toni-moreno/snmpcollector#201]
Hi Authors,

I could not edit or delete a SNMP Device item. Could you pls help me to solve it. Here is my screenshot when I try to open edit form.
![image](https://cloud.githubusercontent.com/assets/27798807/25602894/6adb92a2-2f21-11e7-9d60-9f44a01e593f.png)

**Comment by toni-moreno** [comment]
Hi @khanga6tm perhaps your issue could be related with this one. (https://github.com/toni-moreno/snmpcollector/issues/168)

You can check it on the sql database, with this query.
```bash
sqlite3 ./conf/snmpcollector.db
select id,active from snmp_device_cfg where id like '%FPT_Partner_RT%';
````
Anyway I've released the 0.7 version with this error fixed. You can also upgrade

**Comment by toni-moreno** [comment]
Hi @khanga6tm can you give us some feedback about this issue?

**Comment by toni-moreno** [comment]
Hi @khanga6tm  any update on this?
