### ISSUE TITLE
Cannot Create OID Condition

### ISSUE THREAD

**Issue by tardoe** [toni-moreno/snmpcollector#208]
Here is some debug from the Puppet module I've been working on and since upgrading to 0.7, I've seen that OIDCondition input from the web interface or GUI looks to break. Can you replicate this?

```
Debug: POST to create oidcond2
Debug: Resource to API: {"ID"=>"oidcond2", "IsMultiple"=>false, "OIDCond"=>".1.3.5.7.9", "CondType"=>"match", "CondValue"=>"1", "Description"=>"MANAGED BY PUPPET"}
Debug: Exception: [{"fieldNames":["IsMultiple"],"classification":"RequiredError","message":"Required"}]
```

**Comment by sbengo** [comment]
Hi @tardoe , thanks for reporting this!

The behaivour is a quite unexpected... we used the `Binding` feature of go-macaron which provides more validations on API calls. It seems that "Required" binding throws invalid when boolean is set to "false" cases...

We already opened an issue https://github.com/go-macaron/macaron/issues/130

**Comment by tardoe** [comment]
I assume I'll need to roll back a version as this is currently broken in the API and UI of 0.7?

**Comment by toni-moreno** [comment]
Hi @tardoe if you can wait a little i have planned release 0.7.1 with the fix this weekend.

Sorry and thank you very much for report and your patience

**Comment by tardoe** [comment]
Excellent,

I really appreciate your prompt feedback! 

Also, I’m 99% of the way through a Puppet module that will control 100% of Snmpcollector functionality.
The only small thing I’m missing is allowing the user to control the package version. I can’t walk your S3 bucket to check file names but I assume you keep past versions?

Do you have a standard file naming scheme for past versions?

Regards,

Tim

**Comment by toni-moreno** [comment]
Hi @tardoe I've just updated to 0.7.1 , I hope you can enjoy it.

About s3 naming versions, packages are always uploaded as:

* __rpm__: snmpcollector-X.X.X-1.x86_64.rpm
* __deb__: snmpcollector_X.X.X_amd64.deb
* __tgz__: snmpcollector-X.X.X-`<commitid>`.tar.gz

These are today uploaded files ( packages and sha1 signatures)
```
s3://snmpcollector-rel/builds/snmpcollector-0.7.1-1.x86_64.rpm
s3://snmpcollector-rel/builds/snmpcollector-0.7.1-1.x86_64.rpm.sha1
s3://snmpcollector-rel/builds/snmpcollector-0.7.1-4780b0f.tar.gz
s3://snmpcollector-rel/builds/snmpcollector-0.7.1-4780b0f.tar.gz.sha1
s3://snmpcollector-rel/builds/snmpcollector_0.7.1_amd64.deb
s3://snmpcollector-rel/builds/snmpcollector_0.7.1_amd64.deb.sha1
s3://snmpcollector-rel/builds/snmpcollector-latest-1.x86_64.rpm
s3://snmpcollector-rel/builds/snmpcollector-latest-1.x86_64.rpm.sha1
s3://snmpcollector-rel/builds/snmpcollector_latest_amd64.deb
s3://snmpcollector-rel/builds/snmpcollector_latest_amd64.deb.sha1
```
