### ISSUE TITLE
No web interface

### ISSUE THREAD

**Issue by AL7DS** [toni-moreno/snmpcollector#212]
Installed from the .deb file, built mysql database as directed.  No web interface running at 8090.

**Comment by toni-moreno** [comment]
Hi @AL7DS is something strage . I've just instaled last deb package and after install and start all seems ok.

````
root@dockerdev01:~# dpkg -i ./snmpcollector_latest_amd64.deb
Seleccionando el paquete snmpcollector previamente no seleccionado.
(Leyendo la base de datos ... 40251 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../snmpcollector_latest_amd64.deb ...
Desempaquetando snmpcollector (0.7.1) ...
Configurando snmpcollector (0.7.1) ...
Añadiendo el usuario del sistema `snmpcol' (UID 108) ...
Añadiendo un nuevo usuario `snmpcol' (UID 108) con grupo `snmpcol' ...
No se crea el directorio personal `/usr/share/snmpcollector'.
### NOT starting on installation, please execute the following statements to configure snmpcollector to start automatically using systemd
 sudo /bin/systemctl daemon-reload
 sudo /bin/systemctl enable snmpcollector
### You can start snmpcollector by executing
 sudo /bin/systemctl start snmpcollector
Procesando disparadores para systemd (215-17+deb8u6) ...
root@dockerdev01:~# systemctl start snmpcollector
root@dockerdev01:~# ps -ef |grep snmpcollector
snmpcol  24737     1  0 06:19 ?        00:00:00 /usr/sbin/snmpcollector --pidfile= --config=/etc/snmpcollector/config.toml --logs=/var/log/snmpcollector --home= --data=/var/lib/snmpcollector
root     24749  5306  0 06:19 pts/0    00:00:00 grep snmpcollector
root@dockerdev01:~# lsof -p 24737 |grep -i listen
snmpcolle 24737 snmpcol    5u  IPv6            1320683      0t0     TCP *:8090 (LISTEN)
root@dockerdev01:~#
```` 

![image](https://cloud.githubusercontent.com/assets/5883405/26272948/2d1e5f28-3d25-11e7-9bd8-9004df552c6f.png)

Can you test again and give some feedback please?

**Comment by AL7DS** [comment]
I get this when I do sudo /bin/systemctl start snmpcollector

May 23 14:42:19 Chicago-SNMP systemd[1]: snmpcollector.service: Start request repeated too quickly.
May 23 14:42:19 Chicago-SNMP systemd[1]: Failed to start SnmpCollector Agent.

#! /usr/bin/env bash

# chkconfig: 2345 80 05
# description: SnmpCollector web server & backend
# processname: snmpcollector
# config: /etc/snmpcollector/config.toml
# pidfile: /var/run/snmpcollector.pid

### BEGIN INIT INFO
# Provides:          snmpcollector
# Required-Start:    $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start snmpcollector at boot time
### END INIT INFO

#  tested on
#  1. New lsb that define start-stop-daemon
#  3. Centos with initscripts package installed

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=snmpcollector
DESC="SnmpCollector Agent"
DEFAULT=/etc/default/$NAME

SNMPCOL_USER=snmpcol
SNMOCOL_GROUP=snmpcol
SNMPCOL_HOME=/usr/share/snmpcollector
CONF_DIR=/etc/snmpcollector
WORK_DIR=$SNMPCOL_HOME
DATA_DIR=/var/lib/snmpcollector
LOG_DIR=/var/log/snmpcollector
CONF_FILE=$CONF_DIR/config.toml
MAX_OPEN_FILES=10000
PID_FILE=/var/run/$NAME.pid
DAEMON=/usr/sbin/$NAME


umask 0027

if [ `id -u` -ne 0 ]; then
	echo "You need root privileges to run this script"
	exit 4
fi

if [ ! -x $DAEMON ]; then
  echo "Program not installed or not executable"
  exit 5
fi

. /lib/lsb/init-functions

if [ -r /etc/default/rcS ]; then
	. /etc/default/rcS
fi

# overwrite settings from default file
if [ -f "$DEFAULT" ]; then
	. "$DEFAULT"
fi

DAEMON_OPTS="--pidfile=${PID_FILE} --config=${CONF_FILE}  --logs=${LOG_DIR} --home=${SNMPCOL_HOME} --data=${DATA_DIR} "

case "$1" in
  start)

	log_daemon_msg "Starting $DESC"

	pid=`pidofproc -p $PID_FILE snmpcollector`
	if [ -n "$pid" ] ; then
		log_begin_msg "Already running."
		log_end_msg 0
		exit 0
	fi

	# Prepare environment
	mkdir -p "$LOG_DIR" "$DATA_DIR" && chown "$SNMPCOL_USER":"$SNMPCOL_GROUP" "$LOG_DIR" "$DATA_DIR"
	touch "$PID_FILE" && chown "$SNMPCOL_USER":"$SNMPCOL_GROUP" "$PID_FILE"

  if [ -n "$MAX_OPEN_FILES" ]; then
		ulimit -n $MAX_OPEN_FILES
	fi

	# Start Daemon
	start-stop-daemon --start -b --chdir "$WORK_DIR" --user "$SNMPCOL_USER" -c "$SNMPCOL_USER" --pidfile "$PID_FILE" --exec $DAEMON -- $DAEMON_OPTS
	return=$?
	if [ $return -eq 0 ]
	then
	  sleep 1

    # check if pid file has been written two
	  if ! [[ -s $PID_FILE ]]; then
	    log_end_msg 1
	    exit 1
	  fi

		i=0
		timeout=10
		# Wait for the process to be properly started before exiting
		until { cat "$PID_FILE" | xargs kill -0; } >/dev/null 2>&1
		do
			sleep 1
			i=$(($i + 1))
      if [ $i -gt $timeout ]; then
			  log_end_msg 1
			  exit 1
			fi
		done
  fi
  log_end_msg $return
	;;
  stop)
	log_daemon_msg "Stopping $DESC"

	if [ -f "$PID_FILE" ]; then
		start-stop-daemon --stop --pidfile "$PID_FILE" \
			--user "$SNMPCOL_USER" \
			--retry=TERM/20/KILL/5 >/dev/null
		if [ $? -eq 1 ]; then
			log_progress_msg "$DESC is not running but pid file exists, cleaning up"
		elif [ $? -eq 3 ]; then
			PID="`cat $PID_FILE`"
			log_failure_msg "Failed to stop $DESC (pid $PID)"
			exit 1
		fi
		rm -f "$PID_FILE"
	else
		log_progress_msg "(not running)"
	fi
	log_end_msg 0
	;;
  status)
	status_of_proc -p $PID_FILE snmpcollector snmpcollector && exit 0 || exit $?
    ;;
  restart|force-reload)
	if [ -f "$PID_FILE" ]; then
		$0 stop
		sleep 1
	fi
	$0 start
	;;
  *)
	log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"
	exit 3
	;;
esac

**Comment by AL7DS** [comment]
did a complete reinstall.  Still getting this...

snmpcollector.service - SnmpCollector Agent
   Loaded: loaded (/usr/lib/systemd/system/snmpcollector.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2017-05-23 15:49:44 CDT; 50s ago
     Docs: http://github.com/toni-moreno/snmpcollector
  Process: 2038 ExecStart=/usr/sbin/snmpcollector --pidfile=${PID_FILE} --config=${CONF_FILE} --logs=${LOG_DIR} --home=${HOME_DIR} --data=${DATA_DIR} (code=exited, status=1/FAILURE)
 Main PID: 2038 (code=exited, status=1/FAILURE)

May 23 15:49:44 Chicago-SNMP systemd[1]: snmpcollector.service: Unit entered failed state.
May 23 15:49:44 Chicago-SNMP systemd[1]: snmpcollector.service: Failed with result 'exit-code'.
May 23 15:49:44 Chicago-SNMP systemd[1]: snmpcollector.service: Service hold-off time over, scheduling restart.
May 23 15:49:44 Chicago-SNMP systemd[1]: Stopped SnmpCollector Agent.
May 23 15:49:44 Chicago-SNMP systemd[1]: snmpcollector.service: Start request repeated too quickly.
May 23 15:49:44 Chicago-SNMP systemd[1]: Failed to start SnmpCollector Agent.

**Comment by toni-moreno** [comment]
I assume you are trying to run snmpcollector with mysql as config database. I suggest to test first with the default sqlite3 only to check all is ok with the executable in your environment.

After reconfigure mysql again , can you change the default loglevel config to debug  (logLevel = "debug") in general section and also (debug = true) in the database section in the main config file at /etc/snmpcollector/config.toml ?

run a restart again and show us the output generated in the log dir (should be in /var/log/snmpcollector/ ).

Thank you very much to report this issue.

**Comment by AL7DS** [comment]
It works with sqlite3, but as soon as I put it back to mysql, it errors out.  Got to be a config error, but I haven't found it yet.

**Comment by toni-moreno** [comment]
If you can share with us your logfiles after config in debug mode ,  we can help you look for the error.

**Comment by AL7DS** [comment]
I just elected to use the sqlite3 DB for the program, and point to my existing mysql DB for data.
Having issues now pulling a number out of a string so I can convert it to an integer.  I am new to regex, and tried the samples in your docs with no luck.  
string returned from get is "198:Encoding OK:Channel Pair Status is Good"
I need to get the number 198 and pass that along to the DB as an integer.

**Comment by toni-moreno** [comment]
You can use some online tools to test regex , like https://regex101.com/
in  your case  you can use `([0-9]*):.*` as your regex . 

let me know if this works for you.

**Comment by AL7DS** [comment]
Yes that worked.
I tried to use [0-9]{3} which checked out as reading the integer on regex101, but the program still errored out.  Thanks for holding my hand.  I am not a programmer, but an RF and audio engineer.

**Comment by toni-moreno** [comment]
Ok don't worry!! I hope this tool will be able  to get data from all your devices easily !!
