### ISSUE TITLE
Multiple OIDCondition - Device Testing Modal

### ISSUE THREAD

**Issue by tardoe** [toni-moreno/snmpcollector#215]
You can't use a multiple OID Condition in the device testing modal, returns 404.

`"marshal: Unable to parse OID: strconv.Atoi: parsing \"MatchPortsOnly \u0026\u0026 UpInterfacesOnly\": invalid syntax\n"`

https://www.dropbox.com/s/2j1ygmuzt51k74a/Screenshot%202017-05-24%2006.24.16.png?dl=0

**Comment by toni-moreno** [comment]
Hi @tardoe , You are right, we will filter single oid conditions in this testing modal. It has no sense do a snmp get or walk over something different than an OID.

**Comment by tardoe** [comment]
Perhaps it's not a bad idea then to filter out conditions in that dropdown that have is_multiple set to true?

**Comment by toni-moreno** [comment]
yes we will do exactly what you have suggested. :)
