### ISSUE TITLE
[Feature Request] Allow sending to 2 databases

### ISSUE THREAD

**Issue by Smenon10** [toni-moreno/snmpcollector#216]
Hey guys,

We're at a situation where ideally, we'd want to send the snmpcollector metrics to 2 different influxDBs (actually 1 influx, 1 opentsdb). Is there a possibility of adding this feature? 

Thanks

**Comment by toni-moreno** [comment]
Hi @Smenon10 , I don't understand your request.

Are you requesting the ability to send to other backends different than influxdb? like graphite/prometeus/opentsdb ?

Are you requesting to duplicate and sent data to 2 different backends at once?

Can you be more specific?

Thank you very much!

**Comment by Smenon10** [comment]
Just to send to 2 different influxdb

**Comment by toni-moreno** [comment]
I suggest you to test this other tool for this purposes https://github.com/influxdata/influxdb-relay

Sorry but right now we have not time enough to code all what we would like , and we would like priorice other things  if you have an alternative for this feature.

Anyway let me know any other request that you consider a good feature for the collector

**Comment by Smenon10** [comment]
No worries, it's what we are doing now (using influxdb-relay)
