### ISSUE TITLE
[Feature Request] Export metric collection statistics to backend

### ISSUE THREAD

**Issue by tardoe** [toni-moreno/snmpcollector#217]
It would be great to export the statistics shown on the Device Status page to the InfluxDB backend. I'm currently troubleshooting an issue with a device taking a long time to collect metrics and having this information available historically would be useful.

**Comment by toni-moreno** [comment]
Hi @tardoe  snmpcollector already can do this  you should only configure it  read at ( https://github.com/toni-moreno/snmpcollector/wiki/Troubleshooting )  We are also updated the Wiki with a Grafana dashboard that you can import  to see data .

Let me know if this is enough for you.

**Comment by tardoe** [comment]
Wow, how did I miss that!

Thanks!

Tim Raphael

**Comment by toni-moreno** [comment]
We are also uploaded a Golang VM statistics Dashboard .. !! both should be improved ( could have some minor mistakes) but will be a good way to check the healh of your snmp gathering system.
