### ISSUE TITLE
Device has obsolete data

### ISSUE THREAD

**Issue by tardoe** [toni-moreno/snmpcollector#223]
I'm seeing some large polling times on some of my devices that exceed the current polling interval and appear to be causing bad rate values to be exported to influx.

This is a grafana graph that I hope illustrates the issue isolated to a single device.
https://www.dropbox.com/s/leeygt1bj8aupvg/Screenshot%202017-05-30%2008.40.20.png?dl=0

This is the logs that are in the device log file around the time the 08:18 spike occures:
```
time="2017-05-30 08:18:20" level=warning msg="MEASUREMENT [ifmib] Warning METRIC ID [ifHCOutUcastPkts] from MEASUREMENT[ ifmib ] with TAGS [map[device:pe2.syd1]] has obsolete data => See Metric Runtime [ &{cfg:0xc4208d5100 ID:ifHCOutUcastPkts FieldName:out.packets.rate Valid:false CookedValue:151675.56565230087 CurValue:1795460874389 LastValue:1795456324154 CurTime:2017-05-30 08:17:00.001497451 +1000 AEST LastTime:2017-05-30 08:16:30.001708227 +1000 AEST ElapsedTime:29.999789224 Compute:0x9428f0 Scale:0x941740 SetRawData:0x942530 RealOID:.1.3.6.1.2.1.31.1.1.1.11.2008 Report:1 re:<nil> expr:<nil> condflt:<nil> log:0xc42086eff0} ]"
time="2017-05-30 08:18:20" level=warning msg="MEASUREMENT [ifmib] Warning METRIC ID [ifHCOutUcastPkts] from MEASUREMENT[ ifmib ] with TAGS [map[device:pe2.syd1]] has obsolete data => See Metric Runtime [ &{cfg:0xc4208d5100 ID:ifHCOutUcastPkts FieldName:out.packets.rate Valid:false CookedValue:148508.37673338715 CurValue:1136727176036 LastValue:1136722720816 CurTime:2017-05-30 08:17:00.001497451 +1000 AEST LastTime:2017-05-30 08:16:30.001708227 +1000 AEST ElapsedTime:29.999789224 Compute:0x9428f0 Scale:0x941740 SetRawData:0x942530 RealOID:.1.3.6.1.2.1.31.1.1.1.11.3005 Report:1 re:<nil> expr:<nil> condflt:<nil> log:0xc42086eff0} ]"
time="2017-05-30 08:18:20" level=warning msg="MEASUREMENT [ifmib] Warning METRIC ID [ifHCOutUcastPkts] from MEASUREMENT[ ifmib ] with TAGS [map[device:pe2.syd1]] has obsolete data => See Metric Runtime [ &{cfg:0xc4208d5100 ID:ifHCOutUcastPkts FieldName:out.packets.rate Valid:false CookedValue:194.73470151338154 CurValue:60290449199 LastValue:60290443357 CurTime:2017-05-30 08:17:00.001497451 +1000 AEST LastTime:2017-05-30 08:16:30.001708227 +1000 AEST ElapsedTime:29.999789224 Compute:0x9428f0 Scale:0x941740 SetRawData:0x942530 RealOID:.1.3.6.1.2.1.31.1.1.1.11.2006 Report:1 re:<nil> expr:<nil> condflt:<nil> log:0xc42086eff0} ]"
time="2017-05-30 08:18:20" level=warning msg="MEASUREMENT [ifmib] Warning METRIC ID [ifHCOutUcastPkts] from MEASUREMENT[ ifmib ] with TAGS [map[device:pe2.syd1]] has obsolete data => See Metric Runtime [ &{cfg:0xc4208d5100 ID:ifHCOutUcastPkts FieldName:out.packets.rate Valid:false CookedValue:201909.45192222128 CurValue:2360168200210 LastValue:2360162142969 CurTime:2017-05-30 08:17:00.001497451 +1000 AEST LastTime:2017-05-30 08:16:30.001708227 +1000 AEST ElapsedTime:29.999789224 Compute:0x9428f0 Scale:0x941740 SetRawData:0x942530 RealOID:.1.3.6.1.2.1.31.1.1.1.11.1041 Report:1 re:<nil> expr:<nil> condflt:<nil> log:0xc42086eff0} ]"
```

This appears to be happening at very regular intervals that don't appear to link up with filter update cycles. I want to know if this might be an snmp bug on my device or if snmpcollector is to blame? My only other option is to blow my collection interval out to 60 seconds which I would prefer not to do.

**Comment by toni-moreno** [comment]
Hi @tardoe , "Invalid data" means there are snmpmetrics that  has not been updated on the last gather polling process.

This could happens when .
* there is some timeouts (  perhaps some snmp ie udp packets lost)
* device has any kind of problem with snmp protocol on the related OID
* the base library of the snmpcollector (gosnmp) or the device could have some problem

In order to debug the problem you could start the snmpdebug mode on the device in the runtime before you expect to have the next peak time  and stop after it happens. And share with us the generated snmpdebug_<deviceid>_<measurementid>.log file under the $LOGDIR directory (whatever it was).

I will try to help you to debug the origin of these bad request time.

Thank you very much

**Comment by toni-moreno** [comment]
@tardoe sometimes these times are the result of timeouts , as a bad workaround you can change the Timeout and Repeat parameters from the default 20seconds/5times  to 3seconds/2times. 

It will definitely will reduce the polling time , but won't be able to get correct data..

I will wait to see the snmpdebug logs

**Comment by tardoe** [comment]
Thanks Toni,

I’ve also logged a bug report with my vendor as I believe the device might be at fault as well.
I’ll get those debugs going and see what my vendor comes up with.

- Tim

**Comment by toni-moreno** [comment]
Hi @tardoe I would like to close this issue if you suspect that problem was on the remote devices.

**Comment by tardoe** [comment]
I suspect it is the case though I've had no confirmation. 

Please close.

Regards,

Tim Raphael
