### ISSUE TITLE
STRINGEVAL Not working after upgrade

### ISSUE THREAD

**Issue by topranks** [toni-moreno/snmpcollector#225]
I just upgraded from version 0.6.6 to 0.7.2.

Most everything is working apart from one STRINGEVAL measurement I had set up.  I have not changed anything but now the measurement isn't working, I get the following in the logs:

    "Warning in metric ifNameAlias On EVAL string: (ifName + " - " + ifAlias) : Value has not a valid format "

    time="2017-06-01 11:49:00" level=warning msg="MEASUREMENT [ifMIB] Warning METRIC ID [ifNameAlias] from MEASUREMENT[ ifMIB ] with TAGS [map[hostname:CI-IXDUB1-01 ifIndex:436396538 ifName:Ethernet1/47.506]] has no valid data => See Metric Runtime [ &{cfg:0xc422327900 ID:ifNameAlias FieldName:ifNameAlias Valid:false CookedValue:<nil> CurValue:<nil> LastValue:<nil> CurTime:0001-01-01 00:00:00 +0000 UTC LastTime:0001-01-01 00:00:00 +0000 UTC ElapsedTime:0 Compute:0x944350 Scale:0x941740 SetRawData:<nil> RealOID:ifMIB.ifNameAlias.436396538 Report:1 re:<nil> expr:0xc421986410 condflt:<nil> log:0xc4223b5090} ]" 

The measurement is fairly simple.  I've two stanard measurements to pull the ifName and ifAlias values from the IF-MIB, and the STRINGEVAL measurement should simply combine these:

![image](https://cloud.githubusercontent.com/assets/4465905/26676720/dd7dd750-46c0-11e7-866b-cba0959567a4.png)

Not sure if there has been a change to the STRINGEVAL syntax?

The ifName and ifAlias values are still being recorded correctly:

![image](https://cloud.githubusercontent.com/assets/4465905/26676773/2037f7ba-46c1-11e7-9168-6dc617452870.png)

I had a look around but couldn't find an exact syntax definition for STRINGEVAL, does one exist?

Other (maths rather than text based,) STRINGEVAL measurements are still working fine for me.

**Comment by toni-moreno** [comment]
Hi @topranks thank  you to open this issue, I've review the code and I could notice that we have removed the evaluated strings erroneously (https://github.com/toni-moreno/snmpcollector/blob/master/pkg/data/metric/snmpmetric.go#L392-L401) .  we will fix ASAP .

**Comment by topranks** [comment]
Ok Tony no problem I appreciate the quick reply!

It is not a major problem to go without this until it is fixed.  Thanks again for all the great work on the project!
