### ISSUE TITLE
UI JS Exception - Cannot Read Property 'bits' of Undefined 

### ISSUE THREAD

**Issue by tardoe** [toni-moreno/snmpcollector#233]
When opening an index tab on a device runtime status page.

Version 0.7.2

https://www.dropbox.com/s/yxcywa9sdc80lu3/Screenshot%202017-06-08%2008.37.30.png?dl=0

**Comment by sbengo** [comment]
Hi @tardoe 

We already fix that issue on merged PR #224 . It is caused when some Metric.FieldName contains a `.` on its definition.

We will release the next version on the next week!

Sorry and thanks for reporting this!

**Comment by toni-moreno** [comment]
@tardoe the new 0.7.3 version has been released., feel free to test it. 

Thank you very much
