### ISSUE TITLE
[Bug] Adding entries in ExtraTags yields HTTP 200 'OK', but they're not taken into account

### ISSUE THREAD

**Issue by gradew** [toni-moreno/snmpcollector#245]
Hi :)

We're trying to set up several tags to our nexus switches, which already have "type=nexus".
We would like to have something like "type=nexus" and "type=router".

In order to do that, we're appending "type=router" to ExtraTags and PUTting it back through the API, which returns status code 200.
But when looking via the GUI, the changes aren't taken into account.

Is what we're trying to achieve even possible? :)

Cheers,
Julien Derivière

**Comment by sbengo** [comment]
Hi @gradew 

You can't set 2 tags with the same key, `type=nexus` and `type=router`, the InfluxDB written point will only be sent with `timestamp - tagSet + fieldSet`. The tag with they key `type` will only allow 1 value, it won't be appended to it

The ExtraTags field allow you to set several tags to be sent on the device; ie: `device=router,type=nexus`

I'm sorry I don't understand your "append" operation trough API. You can define a `SNMPDevice` through API and then set the ExtraTag property with your desired tags. 

Can you attach your request?

Thanks!

**Comment by toni-moreno** [comment]
Hi @gradew can you  give us more feedback please? If not we will close this issue and you will be able to reopen when you can review it.

**Comment by toni-moreno** [comment]
@gradew reopen it when needed. Thank  you very much

**Comment by gradew** [comment]
Hi @toni-moreno,

My apologies for the delayed response. Your solution to use "device=router,type=nexus" worked perfectly.

Thank you very much!
Julien
