### ISSUE TITLE
[Feature Request] New SNMP Metric Type

### ISSUE THREAD

**Issue by SnDsound** [toni-moreno/snmpcollector#253]
Hi Guys,

I want to extract some card name from full sting like this below. I want to have, for example: "SRX3k SFB 12GE" as TAG, for future use. 
```
.1.3.6.1.4.1.2636.3.1.13.1.5.7.1.0.0 = STRING: "node0 FPC: SRX3k SFB 12GE @ 0/*/*"
.1.3.6.1.4.1.2636.3.1.13.1.5.7.2.0.0 = STRING: "node0 FPC: SRX3k 16xGE SFP @ 1/*/*"
.1.3.6.1.4.1.2636.3.1.13.1.5.7.4.0.0 = STRING: "node0 FPC: SRX3k 2x10GE XFP @ 3/*/*"
```
This type below, can be useful, but right now it expect only numbers
(Cooked type) STRINGPARSER [ Compute values from Regex ]
Can you change this or add new type, to extract something from string, like names? 

Best regards,
Peter

**Comment by toni-moreno** [comment]
Hi @SnDsound , As you has could check , the STRINGPARSER has been designed to do translation from  a bit of a STRING to a  NUMBER.

I'm not sure if this request would add a really important feature. If you can get  the complete string as index of your snmp table , you will be able to query filtering with any string on your influxDB backend with regular expressions (https://docs.influxdata.com/influxdb/v1.3/query_language/spec/#regular-expressions) .

In your previous example you will be able to search what you need by doing the following IQL query. ( only last minute of data for each serie)

````
SELECT * from your_measurement where time > now()  - 1m and index =~  /.*SRX3k SFB 12GE.*/
````

Are you agree?

**Comment by pavleec** [comment]
Hello Toni,

I think that @SnDsound would like to extract only selected strings from the above using regexp capturing groups the same way like you've mentioned in #51 (for fan name and it's RPM speed). Where we should define the following mapping then?
TAG["fan_number"];FIELD["GAUGE"]

**Comment by toni-moreno** [comment]
Hi @SnDsound , @pavleec could you tell me if this issue could be like this other https://github.com/toni-moreno/snmpcollector/issues/276 or this other https://github.com/toni-moreno/snmpcollector/issues/269

**Comment by pavleec** [comment]
Hello @toni-moreno. Yes, it's kind of similar with the only difference that in #269 the same OID returns both values and field names where in #276 and #253 we only deal with multiple capturing groups regexp tag values matching

**Comment by toni-moreno** [comment]
Hi @SnDsound as explained before in the thread there is currently a way to do what you need , please reopen a new issue if not.
