### ISSUE TITLE
[Feature request] SNMP Device context support

### ISSUE THREAD

**Issue by johnmca** [toni-moreno/snmpcollector#257]
Please include this information:
- What SnmpCollector version are you using? latest docker image 0.7.3 commit b0322cd

I have some virtual devices that require I pass an snmp context to access the virtual instance of the device. Similar to "snmpwalk -n"

Having this feature would help with more virtual devices becoming available.

Thanks

**Comment by toni-moreno** [comment]
Hi @johnmca This would be an excellent idea. I will review code for a while, and will check how difficult would be implementation of this.

**Comment by johnmca** [comment]
Let me know if you need help testing.

**Comment by toni-moreno** [comment]
Hi @johnmca I've added ContexName and also ContextEngineID when needed, but I couldn't test as I have no access to any device with context definitions.  I would like delegate this test you but we can not release a new 0.7.4 , as there is not enougth new features and fixes as you can see (https://github.com/toni-moreno/snmpcollector/blob/master/CHANGELOG.md)  . 

Have you the ability to build yourself from sources?

**Comment by johnmca** [comment]
Thanks @toni-moreno ! I'll get setup to do a build and test this out.

**Comment by johnmca** [comment]
Finally got a build system working to test out the change. Initially all looks good. I can connect to a device using the new snmp context fields and metrics are coming in.

**Comment by johnmca** [comment]
Ran 10 devices over over the long weekend with the new snmp context setting. No issues encountered.
Thanks for the quick turn around!

**Comment by toni-moreno** [comment]
Hi @johnmca nice to hear good news! Closing now!
