### ISSUE TITLE
[Bug] Importing of configuration data doesn't work in FF browser (Chrome OK)

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#258]
Please include this information:
- What SnmpCollector version are you using? **0.7.3** 
- What OS are you running snmpcollector on? Debian Linux
- What did you do? Import the configuration data
- What was the expected result? Possibility to import configuration data
- What happened instead? After selecting previously exported config file, the Import button is always unaccessible (cursor with prohibition sign) in Firefox browser (v52.1.1). However it works works properly in Chrome browser.

Regards
PaVliK

**Comment by toni-moreno** [comment]
Hi @pavleec , thank you to report this issue, we usually work with Chrome so we didn't realise about that. @sbengo will test and review this issue when he comes back from his holidays.

**Comment by sbengo** [comment]
Hi, thanks for reporting this!

Tried with FF and it is throwing an exception when trying to use the event.srcElement property to get the file. As it seems, event.srcElement is not supported on [Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement)

Will try using [event.target property](https://developer.mozilla.org/en-US/docs/Web/API/Event/target)

Quite sorry, I will fix this ASAP!
