### ISSUE TITLE
snmpcollector high socket usage 

### ISSUE THREAD

**Issue by pchytla** [toni-moreno/snmpcollector#259]
Hello,

I've 200 snmp devices (switches/routers)  in single snmpcollector and it seems that that produce lot of udp sockets, more than 5 sockets per IP

All udp established connections :

root@coll_core:~# netstat -nap|grep -i estab|grep :161|wc -l
1017

For single IP:
root@coll_core:~# netstat -nap|grep -i 161|grep 172.28.0.22
udp        0      0 192.168.255.6:49580     172.28.0.22:161         ESTABLISHED 297/snmpcollector
udp        0      0 192.168.255.6:35080     172.28.0.22:161         ESTABLISHED 297/snmpcollector
udp        0      0 192.168.255.6:52527     172.28.0.22:161         ESTABLISHED 297/snmpcollector
udp        0      0 192.168.255.6:37800     172.28.0.22:161         ESTABLISHED 297/snmpcollector
udp        0      0 192.168.255.6:32948     172.28.0.22:161         ESTABLISHED 297/snmpcollector

Running 2000 snmp devices produce around 7-8k udp sockets , I've change openfiles  
to 20000  but lot of devices can't be resolved to IP - to many open files . 

time="2017-08-30 13:05:00" level=error msg="Error on Name Lookup for host: sw2s21  ERROR: lookup sw2s21 on 172.28.255.29:53: dial udp 172.28.255.29:53: socket: too many open files"

/pch

**Comment by toni-moreno** [comment]
hi @pchytla  SnmpCollector by default opens multiple snmp connections over the same device one for each  measurements defined on each device. this is done trying to run multiple concurrent connections to minimise the gathering time for each device.

You can deactivate concurrent Gathering from the device configuration form if you wish.

![image](https://user-images.githubusercontent.com/5883405/29914662-a95dfaa2-8e39-11e7-9fc7-a752b8c0a9c6.png)

Anyway , we have a snmpcollector running with 658 devices and we have 4366 open sockets. I suggest to change your open files to unlimited or something greater than 30x num devices, to be sure you won't have problems anymore.

I will close this issue , feel free to reopen if you need.

**Comment by pchytla** [comment]
@toni-moreno Ok but It seems that disabling "ConcurrentGather" don't have any impact to 
created udp connections 

From logs:
time="2017-08-31 11:09:23" level=info msg="SNMPDEVICE [router] Beginning SNMP connection"
time="2017-08-31 11:09:23" level=info msg="First SNMP connection to host  router established with MaxRepetitions set to 50"
time="2017-08-31 11:09:23" level=info msg="Got basic system info snmp.SysInfo{SysDescr:"TiMOS-C-14.0.R3 cpm/hops64 ALCATEL SR 7750 Copyright (c) 2000-2016 Alcatel-Lucent.\r\nAll rights reserved. All use subject to applicable license agreements.\r\nBuilt on Wed May 25 17:45:36 PDT 2016 by builder in /rel14.0/b1/R3/panos/main\r\n", SysUptime:20079995000000000, SysContact:"", SysName:"", SysLocation:""} "
time="2017-08-31 11:09:23" level=info msg="SNMPDEVICE [router] SNMP connection stablished Successfully for device  and measurement init"
time="2017-08-31 11:09:23" level=info msg="SNMPDEVICE [router] Beginning SNMP connection"
time="2017-08-31 11:09:24" level=info msg="First SNMP connection to host  router stablished with MaxRepetitions set to 50"
time="2017-08-31 11:09:24" level=info msg="Got basic system info snmp.SysInfo{SysDescr:"TiMOS-C-14.0.R3 cpm/hops64 ALCATEL SR 7750 Copyright (c) 2000-2016 Alcatel-Lucent.\r\nAll rights reserved. All use subject to applicable license agreements.\r\nBuilt on Wed May 25 17:45:36 PDT 2016 by builder in /rel14.0/b1/R3/panos/main\r\n", SysUptime:20079995000000000, SysContact:"", SysName:"router", SysLocation:""} "
time="2017-08-31 11:09:24" level=info msg="SNMPDEVICE [router] SNMP connection stablished Successfully for device  and measurement IFMIB-Octets64"
time="2017-08-31 11:09:24" level=info msg="MEASUREMENT [IFMIB-Octets64] Loading Indexed values"
time="2017-08-31 11:09:24" level=info msg="SNMPDEVICE [router] Beginning SNMP connection"
time="2017-08-31 11:09:24" level=info msg="First SNMP connection to host  router stablished with MaxRepetitions set to 50"
time="2017-08-31 11:09:24" level=info msg="Got basic system info snmp.SysInfo{SysDescr:"TiMOS-C-14.0.R3 cpm/hops64 ALCATEL SR 7750 Copyright (c) 2000-2016 Alcatel-Lucent.\r\nAll rights reserved. All use subject to applicable license agreements.\r\nBuilt on Wed May 25 17:45:36 PDT 2016 by builder in /rel14.0/b1/R3/panos/main\r\n", SysUptime:20079996000000000, SysContact:"", SysName:"router", SysLocation:""} "
time="2017-08-31 11:09:24" level=info msg="SNMPDEVICE [router] SNMP connection stablished Successfully for device  and measurement IFMIB-Packets64"
time="2017-08-31 11:09:24" level=info msg="MEASUREMENT [IFMIB-Packets64] Loading Indexed values"
time="2017-08-31 11:09:25" level=info msg="SNMPDEVICE [router] Beginning SNMP connection"
time="2017-08-31 11:09:25" level=info msg="First SNMP connection to host  router stablished with MaxRepetitions set to 50"
time="2017-08-31 11:09:25" level=info msg="Got basic system info snmp.SysInfo{SysDescr:"TiMOS-C-14.0.R3 cpm/hops64 ALCATEL SR 7750 Copyright (c) 2000-2016 Alcatel-Lucent.\r\nAll rights reserved. All use subject to applicable license agreements.\r\nBuilt on Wed May 25 17:45:36 PDT 2016 by builder in /rel14.0/b1/R3/panos/main\r\n", SysUptime:20079997000000000, SysContact:"", SysName:"router", SysLocation:""} "
time="2017-08-31 11:09:25" level=info msg="SNMPDEVICE [router] SNMP connection stablished Successfully for device  and measurement IFMIB-Errors"
time="2017-08-31 11:09:25" level=info msg="MEASUREMENT [IFMIB-Errors] Loading Indexed values"
time="2017-08-31 11:09:25" level=info msg="SNMPDEVICE [router] Beginning SNMP connection"
time="2017-08-31 11:09:25" level=info msg="First SNMP connection to host  router stablished with MaxRepetitions set to 50"
time="2017-08-31 11:09:25" level=info msg="Got basic system info snmp.SysInfo{SysDescr:"TiMOS-C-14.0.R3 cpm/hops64 ALCATEL SR 7750 Copyright (c) 2000-2016 Alcatel-Lucent.\r\nAll rights reserved. All use subject to applicable license agreements.\r\nBuilt on Wed May 25 17:45:36 PDT 2016 by builder in /rel14.0/b1/R3/panos/main\r\n", SysUptime:20079997000000000, SysContact:"", SysName:"router", SysLocation:""} "
time="2017-08-31 11:09:25" level=info msg="SNMPDEVICE [router] SNMP connection stablished Successfully for device  and measurement IFMIB-Discard"
time="2017-08-31 11:09:25" level=info msg="MEASUREMENT [IFMIB-Discard] Loading Indexed values"
time="2017-08-31 11:09:30" level=info msg="SNMPDEVICE [router] snmp INIT runtime measurements/filters took [6.056488653s] "

I've four measurements  IFMIB-Discard/IFMIB-Errors/IFMIB-Octets64/IFMIB-Packets64/ and 5 active
udp connections

root@coll_core:~# netstat -an|grep 185.2.36.31
udp        0      0 192.168.255.6:35977     192.168.36.31:161         ESTABLISHED
udp        0      0 192.168.255.6:36663     192.168.36.31:161         ESTABLISHED
udp        0      0 192.168.255.6:45798     192.168.36.31:161         ESTABLISHED
udp        0      0 192.168.255.6:47322     192.168.36.31:161         ESTABLISHED
udp        0      0 192.168.255.6:55561     192.168.36.31:161         ESTABLISHED

Connection count with "ConcurrentGather" disabled and enabled is the same.

root@coll_core:~# netstat -an|grep :161|wc -l
1017

/pch

**Comment by toni-moreno** [comment]
@pchytla Ok, I will review this ASAP

**Comment by toni-moreno** [comment]
Hi @pchytla . After review the code. I've found that thus when doing queries sequentially we are opening one connection per measurement + 1 ( this last is used  only to check snmp connectivity ).

I'will fix this issue ASAP.
