### ISSUE TITLE
[Feature request]  Device Status - search for  "Not Connected"

### ISSUE THREAD

**Issue by pchytla** [toni-moreno/snmpcollector#260]
It woud be nice in "Runtime / Device Status" to search only for "Not Connected" devices.

/pch

**Comment by toni-moreno** [comment]
@pchytla  we will evaluate the need for this feature. In the meanwhile, you can order by #num of measurements or metrics and those with 0 measurements will be unconnected.

![image](https://user-images.githubusercontent.com/5883405/29922372-99b3f6c6-8e55-11e7-9ce8-9ee62497658c.png)

**Comment by pchytla** [comment]
@toni-moreno ok thx this is helpfull

/pch
