### ISSUE TITLE
[Feature Request] Influx HTTPS Support

### ISSUE THREAD

**Issue by mikemrm** [toni-moreno/snmpcollector#262]
Would it be possible to support HTTPS connection to write to influx? I plan on using this to send data to a central influx server, and would prefer the connection go over HTTPS.

Thanks!

**Comment by toni-moreno** [comment]
Hi @mikemrm , we can try to add this new feature for the next release. Thank you to report this new need

**Comment by chappi6** [comment]
I would also be very happy to have this feature!

**Comment by dago158** [comment]
same here, happy to use snmpcollector privately,
but would require https to use it in prod systems

**Comment by toni-moreno** [comment]
I've added support for HTTPS but still need to upload certificate files to the snmpcollector host before doing the configuration   . 
These related files should be configured with the full path on the snmpcollector running host. and should be readables for the snmpcollector process.

@dago158 @chappi6 @mikemrm , let me know if all working fine, if any error happens I will reopen this FR

**Comment by dago158** [comment]
Tested and it worked. Thanks a lot for this quick (perpesctive) change.
