### ISSUE TITLE
[Bug] No value for IP Address DataSrcType 

### ISSUE THREAD

**Issue by johnmca** [toni-moreno/snmpcollector#263]
Please include this information:
- What SnmpCollector version are you using? 0.7.3 commit db0a653
- What OS are you running snmpcollector on? Centos 6
- What did you do? Adding new SNMP Metric with DataSrcType = IP Address
- What was the expected result? IP Address value should be reported as either tag or field
- What happened instead?
As a tag there is no value
As a field the value is quotes

I created a measurement for the ipRouteTable (http://oid-info.com/get/1.3.6.1.2.1.4.21.1) and unable to add ipRouteNextHop(1.3.6.1.2.1.4.21.1.7) as either a tag and field. Other OIDs (ipRouteAge, ipRouteProto, ipRouteType) work for tags\fields. I have the same issue on a Citrix Netscaler device where no IP is reported.

**snmp debug LOG for the device show type is IPAddress**
[decodeValue: type is IPAddress]
decodeValue: value is []interface {}{"10.xxx.xxx.xx"}
OID: [.1.3.6.1.2.1.4.21.1.7.10.xxx.0.0]
[decodeValue: type is IPAddress]
decodeValue: value is []interface {}{"0.0.0.0"}
OID: [.1.3.6.1.2.1.4.21.1.7.172.xx.0.0]

**Device debug log when metric is a field**
time="2017-09-11 20:23:00" level=debug msg="MEASUREMENT [cisco_iproute] generating field for Metric: ipRouteNextHop : value """
time="2017-09-11 20:23:00" level=debug msg="MEASUREMENT [cisco_iproute] DEBUG METRIC &{cfg:0xc4209def30 ID:cisco_ipRouteNextHop FieldName:ipRouteNextHop Valid:true CookedValue: CurValue:<nil> LastValue:<nil> CurTime:2017-09-11 20:23:00.001098579 -0700 PDT LastTime:0001-01-01 00:00:00 +0000 UTC ElapsedTime:0 Compute:<nil> Scale:0x9405d0 SetRawData:0x9430e0 RealOID:.1.3.6.1.2.1.4.21.1.7.10.x.xxx.0 Report:1 re:<nil> expr:<nil> condflt:<nil> log:0xc4201d6870}"

**Device debug log when metrics is a tag**
time="2017-09-11 20:30:00" level=debug msg="DEBUG METRIC  CONFIG &{ID:cisco_ipRouteNextHop FieldName:ipRouteNextHop Description: BaseOID:.1.3.6.1.2.1.4.21.1.7 DataSrcType:IpAddress GetRate:false Scale:0 Shift:0 IsTag:true ExtraData: Names:map[]}"
time="2017-09-11 20:30:00" level=debug msg="MEASUREMENT [cisco_iproute] generating Tag for Metric: ipRouteNextHop : tagname: "

Let me know if you need any more logs or information.

Thanks

**Comment by toni-moreno** [comment]
Hi @johnmca let us review your issue in next days. Sorry for the late response

**Comment by toni-moreno** [comment]
Hi @johnmca we have found the bug and I've uploaded a fix. Could you  test please this fix ?

**Comment by johnmca** [comment]
The IPAddress DataSrcType now works as both a field and tag!

**Comment by jchristopher327** [comment]
Can I get a little guidance on how I would push this change to my snmpcollector instance?
