### ISSUE TITLE
Config help for Netscaler vserverTable.

### ISSUE THREAD

**Issue by jchristopher327** [toni-moreno/snmpcollector#264]
[bulkexport_2017812.txt](https://github.com/toni-moreno/snmpcollector/files/1297026/bulkexport_2017812.txt)

Please include this information:
- What SnmpCollector version are you using?
 `snmpcollector v0.7.3 (git: b0322cd ) built at [2017-06-26 13:36:47]`
- What OS are you running snmpcollector on?
`CentOS Linux release 7.3.1611 (Core) `
- What did you do?
Added a measurement for vserver VIPs.
- What was the expected result?
Expected result is to have the vserver indexed, and for additional metrics to be associated e.g. vsvrIpAddress, vsvrPort, etc.
- What happened instead?
I do see the VIP name in the device runtime but the vsvrIpAddress column is empty. 

Attached is the exported config (as a txt file) for the snmp metric, influx measurement and measurement group. Below is a link with some SNMP info for the Netscalers (scroll up just a bit).

http://docs.citrix.com/content/dam/docs/en-us/netscaler/10/downloads/ctx132381.htm#vsvrName
<img width="1485" alt="lb runtime" src="https://user-images.githubusercontent.com/17171652/30342384-9713da5a-97ae-11e7-8d31-ffcfa9919040.png">

**Comment by toni-moreno** [comment]
Hi @jchristopher327 this  issue seems to be the same as in #263 ,  your metric defined as IPAddress is returning an empty string. I will review ASAP

**Comment by jchristopher327** [comment]
Thanks! Sorry that I didn't realize that they were related. I added more metrics and worked just fine. Will close out the ticket.
