### ISSUE TITLE
Support for Linux/arm

### ISSUE THREAD

**Issue by janchrillesen** [toni-moreno/snmpcollector#268]
I have build version 0.7.4 on Linux/arm

$ /usr/local/go/bin/go version
go version go1.8.3 linux/arm

$ uname -a
Linux blackie 4.11.6-sunxi #6 SMP Fri Jun 23 19:56:18 CEST 2017 armv7l GNU/Linux

During build I defined

GOARM=7
GOARCH=arm

When I start snmpcollector I see:

Sep 26 12:35:17 blackie snmpcollector[647]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 26 12:35:17 blackie snmpcollector[647]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1a0e0]
Sep 26 12:35:17 blackie snmpcollector[647]: goroutine 1 [running]:
Sep 26 12:35:17 blackie snmpcollector[647]: sync/atomic.storeUint64(0x977d14, 0x0, 0x0)
Sep 26 12:35:17 blackie snmpcollector[647]: /usr/local/go/src/sync/atomic/64bit_arm.go:20 +0x3c
Sep 26 12:35:17 blackie snmpcollector[647]: github.com/toni-moreno/snmpcollector/pkg/config.(*DatabaseCfg).resetChanges(0x977cd8)
Sep 26 12:35:17 blackie snmpcollector[647]: /home/chrille/.go/src/github.com/toni-moreno/snmpcollector/pkg/config/database.go:17 +0x34
Sep 26 12:35:17 blackie snmpcollector[647]: github.com/toni-moreno/snmpcollector/pkg/config.(*DatabaseCfg).LoadDbConfig(0x977cd8, 0x9777d8)
Sep 26 12:35:17 blackie snmpcollector[647]: /home/chrille/.go/src/github.com/toni-moreno/snmpcollector/pkg/config/database.go:161 +0x3f4
Sep 26 12:35:17 blackie snmpcollector[647]: github.com/toni-moreno/snmpcollector/pkg/agent.LoadConf()
Sep 26 12:35:17 blackie snmpcollector[647]: /home/chrille/.go/src/github.com/toni-moreno/snmpcollector/pkg/agent/agent.go:236 +0x24
Sep 26 12:35:17 blackie snmpcollector[647]: main.main()
Sep 26 12:35:17 blackie snmpcollector[647]: /home/chrille/.go/src/github.com/toni-moreno/snmpcollector/pkg/main.go:181 +0x8c
Sep 26 12:35:17 blackie systemd[1]: snmpcollector.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 26 12:35:17 blackie systemd[1]: Unit snmpcollector.service entered failed state.

I have no experience with Go and have no idea how to debug this

**Comment by toni-moreno** [comment]
Hi @janchrillesen sorry but  right now, I  have not time enough to dedicate to help you. I will try to review this issue in next two weeks. Sorry and Thank you.

**Comment by toni-moreno** [comment]
Hi @janchrillesen It seems like ARM needs for aligned variables on atomic operations as explained at the end of this document. https://golang.org/pkg/sync/atomic/

**Comment by toni-moreno** [comment]
Hi @janchrillesen can you test your build again?

**Comment by janchrillesen** [comment]
Thanks @toni-moreno - I can confirm that 309df8d fixed my issue and I now have snmpcollector running on by arm7 board
