### ISSUE TITLE
[Feature Request] STRINGPARSER capturing group and uniqe OID limit

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#269]
Hi,

Due to the limited number of custom OIDs that are possible to be configured on some of my devices multiple statistics are published on the same OID as colon separated values. It looks like below:

`1.3.6.1.4.1.7234.1.1.1.4 = 45:123:51:<value_n>:<value_n+1>`

I've tried to use multiple capturing groups for STRINGPARSER but only the first match is supported. I've also tried to define separate snmp metrics with single STRINGPARSER group but I'm not able to add them after that in the Influx Measurement due the unique OID limit. 
Is there some way to solve it?

**Comment by toni-moreno** [comment]
Hi @pavleec , We can add a new MULTI_STRINGPARSER type to set more than one Field or Tag , from Regex Capturing groups. Although this change could be complex as it breaks a lot of design assumptions

In your example you should configure Extradata with 

`F:"field_name_1", F:"field_name_2",T:"tag_name1" '([^;]*);([^;]*);([^;]*);'`

And each capturing group will be assigned in order to a tar or field .

Type|Name|Assigned value
-------|------|------
Field| "field_name_1"|45
Field| "field_name_2"|123
Tag|"tag_name1"|51

**Comment by pavleec** [comment]
It would be great :-)

sob., 30.09.2017, 06:57 użytkownik Toni Moreno <notifications@github.com>
napisał:

**Comment by toni-moreno** [comment]
Hi @pavleec , @sbengo I've been reviewing how to  implement in a flexible way the new MULTI_STRINGPARSER type to set more than one Field or Tag. 

The first proposal was.

`F:"field_name_1", F:"field_name_2",T:"tag_name1" '([^;]*);([^;]*);([^;]*);'`

But this has a lot of limitations.

1) we are assuming the response got from the snmp device is a  "readable string"
2) we are assuming that we will add fields again as a readable string ( without data transformation) 

A New Approach could be done by doing 2 new types MULTI_STRINGPARSER / MULTI_BYTESPARSER 


## MULTI_STRINGPARSER  Type

We well parse data with regex with capturing groups and each capture group will be attached to a definition  ITEM

````
REGEX_WITH_CAPTURING_GROUPS => F|field_name_1|CONV1, F|field_name_2|CONV2,T|tag_name1|CONV3
````

This configuration could be placed in:


- FieldName `F|field_name_1|CONV1, F|field_name_2|CONV2,T|tag_name1|CONV3`
- ExtraData `'([^;]*);([^;]*);([^;]*);' <-regexp`

Each ITEM  in  the FieldName needs for 3 parameters before to be sent.

1) What type of value  ? F = Field , T = Tag
=> this parameter invalidates the use of isTag flag in the metric definition
2) Field/Tag Name will be sent to the InfluxDB
3) How should I evaluate the value?

Fields/Tag definitions will be evaluated as:

CONVERSORS |  Conversion type (from String)
--------|---------------------------------------
STR | to maintain as string ( no conversion will be done)
INT| to convert as and 64bits integer
FP| to convert as and 64 bits floating point
BL| to convert as a bolean

Conversors does a STRING to ANYTHING conversion.
Index Transformators the inverse conversión a ANYTHING to STRING ( conversion is done to send tags .. ie strings)


##  MULTI_BYTESPARSER type

This type should cover any bytearray value structured in a SNMP Pdu

We can follow previous work on the [IndexTagFormat](https://github.com/toni-moreno/snmpcollector/wiki/Component:-Measurements#indextagformat-definition), with already defined selectors/transformators.

In this case there is no variables (as in indextagformat) , only the snmp Pdu Value so al selector apply to the complete value got in the SnmpMetric struct

````
F|f_name_1|SELECTOR1|TRANSFORMATOR1|CONV1,
F|f_name_2|SELECTOR2|TRANSFORMATOR2|CONV2,
T|t_name_3|SELECTOR3|TRANSFORMATOR3|CONV3,
````

This configuration could be placed in:


- FieldName `F|f_name_1,F|f_name_2,T|t_name_3`
- ExtraData `SELECTOR1|TRANSFORMATOR1|CONV1,SELECTOR2|TRANSFORMATOR2|CONV2,SELECTOR3|TRANSFORMATOR3|CONV3`

Here Apply the TRANSFORMATION item but after perhaps we'll need to apply a conversion.. to non strings values... It depends on how often integer/floating point values could be coded inside an Pdu value in snmp MIB's.

#### Current Available SELECTORS

SELECTOR | DESCRIPTION
---------|------------
ALL| complete string
DOT[X:Y] | splits value in an array of numbers and select only from the Xth to the Yth value, if X is omitted 0 will be chosen , if Y is omitted the last element on the splitted array will be chosen , in this mode DOT[0:] is equivalent to ALL. Counter always begins from 0 and both X and Y position will be included in the final selection
REGEX/regex-expression/substitution-expression/| Regex based Substitution pattern , each section is described in the following table

#### Available TRANSFORMATORS ARE

TRANSFORMATOR| DESCRIPTION
---------|------------
 STRING |return the selected value as an string
DEC2ASCII| decode a dotted separated string with numbers as ascii bytes of a string ("100.101.102.97.117.108.116" will be "default")


#### Available CONVERSORS ARE

CONVERSORS |  Conversion type (from String)
--------|---------------------------------------
STR | to maintain as string ( no conversion will be done)
INT| to convert as and 64bits integer
FP| to convert as and 64 bits floating point
BL| to convert as a boolean
 
### Next Steps.

I need think about this a little more , once defined a lot of code rewrite will be needed and I  would like to have defined a robust and flexible way to parse single PduValues to multiple data.

@sbengo @pavleec , what do you think about

**Comment by sbengo** [comment]
Closing this as it is already implemented
