### ISSUE TITLE
[Bug] Previous SNMP connection found error message and interrupted polling

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#270]
Hello,

This night one of my devices was upgraded and restarted and after that snmpcollector stopped collecting the SNMP data. In the device log file for every poller cycle the following error message appeared "Previous SNMP connection found". Restart of snmpcollector (at 09:25) has fixed the problem whats also visible in the log. Any ideas what might blocked the polling?

```
time="2017-10-18 09:24:20" level=info msg="SNMPDEVICE [xx-xx01] Previous SNMP connection found"
time="2017-10-18 09:24:20" level=info msg="MEASUREMENT [Interface_Traffic] Loading Indexed values"
time="2017-10-18 09:24:46" level=info msg="OIDMULTIPLEFILTER [Interface_Skip_Dummy && Interface_Up_Only] getting condition Interface_Skip_Dummy"
time="2017-10-18 09:24:46" level=info msg="OIDMULTIPLEFILTER [Interface_Skip_Dummy && Interface_Up_Only] getting condition Interface_Up_Only"
time="2017-10-18 09:25:03" level=info msg="SNMPDEVICE [xx-xx01] snmp INIT runtime measurements/filters took [43.286130851s] "
time="2017-10-18 09:25:03" level=info msg="Waiting 56.359260842s to round until nearest interval... (Cicle = 60 seconds)"
time="2017-10-18 09:26:00" level=info msg="SNMPDEVICE [xx-xx01] Init gather cicle mode Concurrent [ false ]"
```

- What SnmpCollector version are you using? 0.7.4
- What OS are you running snmpcollector on? Debian 8

**Comment by pavleec** [comment]
I've also tried to execute SnmpReset on the affected devices and reloaded the config, both with no success :( Moreover reloading of config hanged the whole snmpcollector and only service restart fixed the issue.

**Comment by pavleec** [comment]
Toni where are you? We're missing you and your active development ;)

**Comment by toni-moreno** [comment]
Hi @pavleec next weeks we have plans to spend some time in fix this and  other issues and also add new features. Sorry for the delay in the answer

**Comment by pavleec** [comment]
Great and thanks for quick response

**Comment by toni-moreno** [comment]
Hi @pavleec 

In the last commit I've added a new Hard snmp reset option. This option does 2 things.

1.- Remap again all internal measurements and filter options.
2.- Release old snmp connections and restart new ones.

This option is the same that if you restart the full collector but only affects one device.

![image](https://user-images.githubusercontent.com/5883405/32981539-02ade4f2-cc77-11e7-9ce8-cdeeb34b7d77.png)

I hope this workaround could help you in next device upgrades.

**Comment by pavleec** [comment]
Hello @toni-moreno, ok I will check this but the problem is that it still requires manual intervention. In case when we had network connectivity problems for some devices, snmpcollector was not able to recover itself even when devices went reachable again.

**Comment by toni-moreno** [comment]
Hi @pavleec 
You are right , an automatic periodic hard reset could be a solution. This could be done before an UpdateFilter action, and could be  an option for the device.  

what do you think about?

**Comment by pavleec** [comment]
Wouldn't it be possible to jest detect when some device is not responding and try to perform hard reset on each polling cycle until it starts responding?

**Comment by pavleec** [comment]
@toni-moreno - what do you think about the above then?

**Comment by pavleec** [comment]
I've upgraded and tested the newest v0.7.5 for the above and here are my conclusions:

- snmpcollector is not able to restore snmpolling after device restart
- SNMP device reset button also didn't help
![bez tytulu](https://user-images.githubusercontent.com/12551929/34262817-c2e34770-e66d-11e7-82b3-0bba8167f979.png)

- only whole service restart has fixed the polling 

Here's the log output - device was restarted at (04:19)

time="2017-12-21 04:18:02" level=info msg="STATS SNMP GET: snmp pooling took [3.031162 seconds] SNMP: Gets [583] , Processed [379], Errors [0]"
time="2017-12-21 04:18:02" level=info msg="STATS SNMP FILTER: filter pooling took [0.000000 seconds] "
time="2017-12-21 04:18:02" level=info msg="STATS INFLUX: influx send took [0.000001 seconds]"
time="2017-12-21 04:18:59" level=info msg="SNMPDEVICE [xxx-xx02] Init gather cicle mode Concurrent [ false ]"
time="2017-12-21 04:19:19" level=error msg="MEASUREMENT [EPC_CPU_Resources] SNMP WALK (10.10.32.196) for OID (.1.3.6.1.4.1.8164.1.10.1.1.14) get error: Request timeout (after 5 retries)
time="2017-12-21 04:19:39" level=error msg="MEASUREMENT [EPC_CPU_Resources] SNMP WALK (10.10.32.196) for OID (.1.3.6.1.4.1.8164.1.10.1.1.15) get error: Request timeout (after 5 retries)
time="2017-12-21 04:19:59" level=error msg="MEASUREMENT [EPC_CPU_Resources] SNMP WALK (10.10.32.196) for OID (.1.3.6.1.4.1.8164.1.10.1.1.3) get error: Request timeout (after 5 retries)
time="2017-12-21 04:20:19" level=error msg="MEASUREMENT [EPC_CPU_Resources] SNMP WALK (10.10.32.196) for OID (.1.3.6.1.4.1.8164.1.10.1.1.4) get error: Request timeout (after 5 retries)
time="2017-12-21 04:20:39" level=error msg="MEASUREMENT [EPC_CPU_Resources] SNMP WALK (10.10.32.196) for OID (.1.3.6.1.4.1.8164.1.10.1.1.6) get error: Request timeout (after 5 retries)

after which it started reporting "Previous SNMP connection found"

time="2017-12-21 04:23:39" level=info msg="STATS SNMP GET: snmp pooling took [280.025313 seconds] SNMP: Gets [0] , Processed [0], Errors [379]"
time="2017-12-21 04:23:39" level=info msg="STATS SNMP FILTER: filter pooling took [0.000000 seconds] "
time="2017-12-21 04:23:39" level=info msg="STATS INFLUX: influx send took [0.000013 seconds]"
time="2017-12-21 04:23:39" level=info msg="SNMPDEVICE [xxx-xx02] Previous SNMP connection found"
time="2017-12-21 04:23:39" level=info msg="SNMPDEVICE [xxx-xx02] Previous SNMP connection found"
.. and when snmpcollector got restarted at 08:33:
time="2017-12-21 08:33:00" level=info msg="MEASUREMENT [EPC_Interface_Traffic] Loading Indexed values"
time="2017-12-21 08:33:01" level=info msg="OIDMULTIPLEFILTER [Interface_Skip_Dummy && Interface_Up_Only] getting condition Interface_Skip_Dummy"
time="2017-12-21 08:33:01" level=info msg="OIDMULTIPLEFILTER [Interface_Skip_Dummy && Interface_Up_Only] getting condition Interface_Up_Only"
time="2017-12-21 08:33:06" level=info msg="SNMPDEVICE [xx-xx02] snmp INIT runtime measurements/filters took [6.649478475s] "
time="2017-12-21 08:33:06" level=info msg="Waiting 53.350298419s to round until nearest interval... (Cicle = 60 seconds)"
time="2017-12-21 08:33:49" level=warning msg="SNMPDEVICE [xx-xx02] No Custom Variables detected in device"
time="2017-12-21 08:33:49" level=info msg="SNMPDEVICE [xx-xx02] Can not initialize this device: Is Active: true  |  Connection Active: true "
time="2017-12-21 08:33:49" level=info msg="SNMPDEVICE [xx-xx02] Beginning gather process for device on host (10.10.32.196)"
time="2017-12-21 08:33:49" level=info msg="SNMPDEVICE [xx-xx02] Beginning SNMP connection Sequential"
time="2017-12-21 08:33:49" level=info msg="First SNMP connection to host  10.10.32.196 stablished with MaxRepetitions set to 25"

Are you planing to fix it?

**Comment by toni-moreno** [comment]
@pavleec There is 2 ways to do reset.

*  __soft reset__: only restarts snmp connection for current established measurements and  with current indexed states an filter states.
* __hard reset__: stop all snmp communications and restart them again, remap again all measurement map, indexes in the same way a restart is done.

Have you tested the hard reset?

![image](https://user-images.githubusercontent.com/5883405/34293832-5cbabff2-e706-11e7-987a-240480438827.png)

We have plans also in a few weeks  also to add a automatic periodic hard reset in the same way there is now a periodic filter and re-index update.

**Comment by pavleec** [comment]
I was not able to do Hard Reset because the runtime page for the affected device wasn't opening. Only the whirling dots logo was looping endlessly :|

**Comment by sbengo** [comment]
Hello @pavleec !
I'm quite sorry, I didn't think about if the device is not answering, obviously it will take a lot to access on its runtime detail view...

We will add the `Hard Reset` button on the global runtime!

Meanwhile remember that you can do request via API to do the hard reset!

In this case:
`GET  <URL>/api/rt/device/snmpreset/<ID_DEVICE>/hard`

Thanks,
Greetings!

**Comment by toni-moreno** [comment]
Hi @pavleec  next version you will have ability to do a hard reset from the main runtime view. ( or with the API as @sbengo told you some days ago).

I've reviewed your logs and the "Previous SNMP connection found" appears only in Devices in  Concurrent Mode = false ( could you confirm me that you have your device configured in non concurrent mode?).

I think this bug will not appear in concurrent mode..  I'm still reviewing  and testing  the code... but you can also test if you want

**Comment by toni-moreno** [comment]
Hi @pavleec I can confirm that this  was a bug and was affected only on sequential mode devices. 
I hope you can test ASAP on the next release or building  from sources yourself.

Thank you very much and sorry !!

**Comment by pavleec** [comment]
Hi @toni-moreno. You're right I've completely disabled Concurrent Gather in #246. I will re-enable it and let you how it looks right now.
