### ISSUE TITLE
[Feature Request] Mass change for Update Filter (Cicles)

### ISSUE THREAD

**Issue by SnDsound** [toni-moreno/snmpcollector#272]
Hi,

Could you add option to change Update Filter (Cicles) via mass change?

![obraz](https://user-images.githubusercontent.com/12694268/31819386-b987fb14-b59c-11e7-8162-a6d496416d21.png)

Regards,
Peter

**Comment by sbengo** [comment]
Hi @SnDsound,

My apologies, seems I forgot this one!
I will add Update Filter as a option on Table available actions

Thanks for reporting this,
Greetings!!

**Comment by SnDsound** [comment]
@sbengo no problem. Thanks :-)
