### ISSUE TITLE
[Feature Request] Add version/ID info into the login page

### ISSUE THREAD

**Issue by toni-moreno** [toni-moreno/snmpcollector#274]
Could be an interesting feature having the versión and the instance ID in the login Page/Box. This could be important on systems with several instances running.

![image](https://user-images.githubusercontent.com/5883405/32651824-88d5278c-c602-11e7-89b5-b5359ea9519a.png)

**Comment by sbengo** [comment]
@toni-moreno , I added the version info on login page on PR #281 , but remember that we need to change the API to allow non-logged users do the request:

https://github.com/toni-moreno/snmpcollector/blob/b25cb93d7e9d648c62fa954ad89bddceb199ccea/pkg/webui/apirt-agent.go#L20

**Comment by toni-moreno** [comment]
Done!
