### ISSUE TITLE
[Feature request] Collect "now" and "choose" which device to collect from

### ISSUE THREAD

**Issue by bk-khaled** [toni-moreno/snmpcollector#275]
Hello, 

I would like to make a Feature Request about 2 possibilitys we could add to the web-ui that can be helpful :
- An action that allow snmpcollector to force the collection of metrics, i explai myself : 
 what if i have a daily interval for collecting metrics, let's say evry day at 3pm. And at 9am i want to see the stats of my devices but i don't want to change the regular intervall time (3pm). It would be great to add the possibility to collect now ! 
-The second request is related to the first one and is as much important i think. if we can make action like : "collect now" , it would be great to choose which devices are going to be concerned by this action ! like a check box near each device so we can choose to test only one device for exemple or a groupe of them by collecting now.

Cheers, 
PS : 
- What SnmpCollector version are you using? snmpcollector v0.7.4
- What OS are you running snmpcollector on? Ubuntu 16.04.3 LTS

**Comment by toni-moreno** [comment]
Hi @bk-khaled I'm happy to see different  ways to use the snmpcollector , the usual way is collecting metrics with a high frequency  ( 1 minute period or less ) , in this context this new feature IMHO is not needed. In your case could be useful due to the low frequency ( once a day) . 

Could be certainly a new option , we will have in mind in next releases. 

Thank you very much for your suggestion @bk-khaled

**Comment by bk-khaled** [comment]
We may use SnmpCollector for both cases so it would be cool to have it this feature  :)

Thank you for your consideration  @toni-moreno !

**Comment by toni-moreno** [comment]
Hi @bk-khaled I've implemented a new option to force data gathering even if the device is not active, you could already do, but should wait to next release to test it if you can not build yourself.

![image](https://user-images.githubusercontent.com/5883405/32981480-bfcbe56c-cc76-11e7-833b-32da20a15c12.png)

**Comment by bk-khaled** [comment]
Great ! thanks for being so reactive @toni-moreno !
