### ISSUE TITLE
Ability to count values

### ISSUE THREAD

**Issue by jasonyates** [toni-moreno/snmpcollector#277]
I'm trying to poll an Aruba wireless LAN controller and count the number of users connected to a given controller. The only way you can get an accurate count from Aruba is via the OID .1.3.6.1.4.1.14823.2.2.1.5.2.2.1.1.12 which presents you with an indexed list of users and the SSID they are connected to.

Is it possible to get a count of the number of users connected?

SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.0.205.254.213.78.160 = STRING: "Guest"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.16.2.181.191.204.165 = STRING: "Corp"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.52.2.134.32.14.134 = STRING: "Corp"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.68.133.0.65.47.28 = STRING: "Corp"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.72.75.170.147.18.152 = STRING: "Guest"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.84.159.19.66.76.26 = STRING: "Corp"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.96.248.29.107.85.212 = STRING: "Corp"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.108.114.231.163.21.2 = STRING: "Corp"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.120.79.67.101.89.220 = STRING: "Corp"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.120.79.67.118.151.197 = STRING: "Guest"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.2.1.1.12.120.123.138.61.204.49 = STRING: "Guest"

**Comment by toni-moreno** [comment]
You should first create an OID condition with a RegExp which matches all posible SSID ".*"

![image](https://user-images.githubusercontent.com/5883405/32984728-3e0ab2d4-ccac-11e7-8182-f1d4fca4a4e5.png)
After  you should define a SnmpMetric type CONDITIONEVAL which reports the number of "trues" on the selected condition.

![image](https://user-images.githubusercontent.com/5883405/32984740-8c2be4ec-ccac-11e7-90a5-5203825b6268.png)

You can also create as many OID conditions as SSID you have to count users per SSID if you wish.

I hope this can help you
