### ISSUE TITLE
Bulk import of devices

### ISSUE THREAD

**Issue by gavmckee80** [toni-moreno/snmpcollector#280]
- What SnmpCollector version are you using?
snmpcollector v0.7.4 (git: 304bb8d ) built at [2017-09-23 02:23:30]

- What OS are you running snmpcollector on?
CentOS

- What did you do?
Tried to do a bulk import of devices from a file or connect directly to the sqlite db

- What was the expected result?
Device import using the JSON structure just hangs.  Can't do a CSV import I think

 {
  "ID": "lab-db9-eng-acc01x",
  "Host": "lab-db9-eng-acc01x",
  "Port": 161,
  "SystemOIDs": [
    ""
  ],
  "Retries": 5,
  "Timeout": 20,
  "Repeat": 0,
  "Active": true,
  "SnmpVersion": "2c",
  "Community": "publ1cr0",
  "V3SecLevel": "",
  "V3AuthUser": "",
  "V3AuthPass": "",
  "V3AuthProt": "",
  "V3PrivPass": "",
  "V3PrivProt": "",
  "V3ContextEngineID": "",
  "V3ContextName": "",
  "DisableBulk": false,
  "MaxRepetitions": 50,
  "Freq": 60,
  "UpdateFltFreq": 60,
  "ConcurrentGather": true,
  "OutDB": "1",
  "LogLevel": "info",
  "LogFile": "",
  "SnmpDebug": false,
  "DeviceTagName": "hostname",
  "DeviceTagValue": "id",
  "ExtraTags": [
    ""
  ],
  "Description": "",
  "MeasurementGroups": [
    "foo"
  ],
  "MeasFilters": null
} 

- What happened instead?

- If related with process panics.
  - Include the related log files indicated in the troubleshooting guide.(snmpcollector.log `<deviceid>.log`)
[Macaron] 2017-11-20 16:02:15: Completed /api/rt/device/info 200 OK in 545.686µs
[Macaron] 2017-11-20 16:02:30: Started POST /api/cfg/import/ for 10.16.228.181
[Macaron] 2017-11-20 16:02:30: Completed /api/cfg/import/ 404 Not Found in 3.053764ms
[Macaron] 2017-11-20 16:03:18: Started POST /api/cfg/import/ for 10.16.228.181
[Macaron] 2017-11-20 16:03:18: Completed /api/cfg/import/ 404 Not Found in 844.058µs
[Macaron] 2017-11-21 07:37:11: Started GET /api/cfg/snmpdevice for 10.16.228.181
[Macaron] 2017-11-21 07:37:11: Completed /api/cfg/snmpdevice 403 Forbidden in 373.173µs

Can anyone advise if its possible to do a bulk import ?

**Comment by sbengo** [comment]
Hello @gavmckee80 
First of  all:
- Are you using the UI?
- Are you trying to import the JSON you had attached on the issue?
- Can you set up on debug log level the snmpcollector (config.toml) and attach the snmpcollector.log?

The import format must follow a specific format. This format is automatically generated by the "Export" button/menu item.

Remember that object order is important if you trying to import some component on "recursive=true" mode.

As an example, this is the generated JSON from a simple device export:

![image](https://user-images.githubusercontent.com/13196237/33123362-44857984-cf7a-11e7-937f-312daa04837e.png)

````
{
	"Info": {
		"FileName": "localhost_snmpdevicecfg.json",
		"Description": "Autogenerated",
		"Author": "snmpcollector",
		"Tags": "",
		"AgentVersion": "0.7.4",
		"ExportVersion": "1.0",
		"CreationDate": "..."
	},
	"Objects": [{
		"ObjectTypeID": "snmpdevicecfg",
		"ObjectID": "localhost",
		"Options": null,
		"ObjectCfg": {
			"ID": "localhost",
			"Host": "localhost",
			"Port": 161,
			"SystemOIDs": [""],
			"Retries": 5,
			"Timeout": 20,
			"Repeat": 0,
			"Active": true,
			"SnmpVersion": "2c",
			"Community": "public",
			"V3SecLevel": "",
			"V3AuthUser": "",
			"V3AuthPass": "",
			"V3AuthProt": "",
			"V3PrivPass": "",
			"V3PrivProt": "",
			"V3ContextEngineID": "",
			"V3ContextName": "",
			"DisableBulk": false,
			"MaxRepetitions": 50,
			"Freq": 60,
			"UpdateFltFreq": 60,
			"ConcurrentGather": true,
			"OutDB": "foo_influxdb",
			"LogLevel": "info",
			"LogFile": "",
			"SnmpDebug": false,
			"DeviceTagName": "device",
			"DeviceTagValue": "id",
			"ExtraTags": [""],
			"Description": "",
			"MeasurementGroups": ["foo_mg",
			"bar_mg"],
			"MeasFilters": ["foo_mf",
			"bar_mf"]
		},
		"Error": ""
	}]
}
````

**Comment by toni-moreno** [comment]
Hi @gavmckee80 have you reviewed the correct way to import/export data that @sbengo  sent you  6 days ago?

**Comment by gavmckee80** [comment]
Hi @toni-moreno ,

Thanks for following up and apologies for the delay in the response.  I tested this yesterday using the import format you provided above and was able to bulk import 1500 devices.

Gav
