### ISSUE TITLE
SnmpCollector hangs on Influx error

### ISSUE THREAD

**Issue by jasonyates** [toni-moreno/snmpcollector#282]
I have an issue with snmpCollector whereby the whole app appears to hang / grind to a halt when it receives an error from InfluxDB. I made a change to consolidate two of my measurements in to one table that resulted in trying to write an int and a float to the same measurement value. When snmpcollector got an error back from Influx on a write attempt the whole app hung and it stopped trying to poll any devices.

Nov 27 08:52:30 myserver001 snmpcollector: time="2017-11-27 08:52:30" level=error msg="influxdb write error:  {"error":"partial write: field type conflict: input field \"corpBP\" on measurement \"wireless\" is type integer, already exists as type float dropped=2"}

Also, an attempted Reload Configuration from the GUI causes the GUI to hang completely. I have to restart the application entirely to resolve.

**Comment by jasonyates** [comment]
I have another example of this the app stops sending all metrics including those not part of that measurement.

Nov 27 12:27:31 myserver001 snmpcollector: time="2017-11-27 12:27:31" level=error msg="influxdb write error:  {"error":"partial write: max-values-per-tag limit exceeded (100000/100000): measurement=\"cisco_ifMib\" tag=\"InputUtilization\" value=\"4475841\" dropped=2"}

**Comment by toni-moreno** [comment]
Hi @jasonyates we will review this limitation on the collector ASAP.  Thank you to report it!
