### ISSUE TITLE
Error with filter naming 

### ISSUE THREAD

**Issue by chappi6** [toni-moreno/snmpcollector#292]
Hi I have tried to collect some metric from my device. Actually there is a metric with voltage an i created a filter for selection only this metric but it doesn't seem to be supported.  How can i remove this filter or the name to the the programs running again? 

WARN[2017-12-04 16:55:00] No Output default found influxdb devices found !!
panic: regexp: Compile(`+12V`): error parsing regexp: missing argument to repetition operator: `+`
goroutine 6 [running]:
regexp.MustCompile(0xc4205ae630, 0x4, 0x13)
        /usr/local/go/src/regexp/regexp.go:237 +0x171
github.com/toni-moreno/snmpcollector/pkg/data/filter.(*OidFilter).Update.func1(0xc4201fa1b0, 0x21, 0x4, 0xafe380, 0xc4200ce4                                            e0, 0x113b760, 0xc4202394a0, 0xc4200958d8, 0xc420234120)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/filter/oidfilter.go:79 +0x164a
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).walk(0xc42035b0a0, 0xc4200a94a5, 0xc42069f900                                            , 0x1f, 0xc42069f9a0, 0x412da5, 0x5f631aed)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/walk.go:80 +0x2                                            bd
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk(0xc42035b0a0, 0xc42069f900, 0x1f, 0x                                            c42069f9a0, 0xc420086d01, 0xc42069f9a0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/gosnmp.go:359 +                                            0x4e
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk-fm(0xc42069f900, 0x1f, 0xc42069f9a0,                                             0x0, 0xc4201df0e0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:89 +0x48
github.com/toni-moreno/snmpcollector/pkg/data/filter.(*OidFilter).Update(0xc420086dc0, 0xc4205ae690, 0x1)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/filter/oidfilter.go:135 +0x189
github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).AddFilter(0xc4201f8cc0, 0xc420242900, 0x30, 0xc4200                                            efbd8)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:193 +0x63b
github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).InitDevMeasurements(0xc4201783c0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:275 +0x10c8
github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).startGatherGo(0xc4201783c0, 0x1185640)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:562 +0x305
created by github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).StartGather
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:530 +0x60

**Comment by toni-moreno** [comment]
I can see that collector crash after your new OID Condition  it seems the problem is in the regexp ( the `+` seems to be a problem ) , you can update the value from sql database by executing the database client ( assuming sqlite   "sqlite3 conf/snmpcollector.db" or "sqlite3 <the_complete_path_for_your_snmpcollector.db_file>")


````sql
select * from oid_condition_cfg;
update oid_condition_cfg set cond_value='.12V' where cond_value='+12V';
````
And restart again to see if everything ok. ( and I will build a fix trying to avoid a panic if any  other config mistake happens)

Anyway I would like   to know what exactly do you need, and what configuration are you doing to do what you wish?  Perhaps there is any other way to do it better.

**Comment by toni-moreno** [comment]
Hi @chappi6  I'm trying to reproduce the panic but I'm not able to  doit.

Could yo tell me the exact version are you running ( you can get by executing   snmpcollector -version ) and also show me your wrong configuration please!

**Comment by toni-moreno** [comment]
I've finally added some extra checks to avoid inserting wrong values in any OIDCondition.

![image](https://user-images.githubusercontent.com/5883405/33581216-4d0ff3d8-d950-11e7-9b74-df01d910a549.png)

**Comment by chappi6** [comment]
Hi toni, 
I have version 0.7.1  installed. 
Well my intention was to create a filter that filters out only sensor value from a fw which return me the value for a voltage thats is +12V . 
I can try to reproduce the error within a vm if you like. 

P.S 
Thx for the really fast support.
