### ISSUE TITLE
Bug - Error during build

### ISSUE THREAD

**Issue by mcaulifn** [toni-moreno/snmpcollector#293]
Please include this information:
- What SnmpCollector version are you using? 0.7.4
- What OS are you running snmpcollector on? Ubuntu 16.04.3 armhf
- What did you do? build
- What was the expected result? built package
- What happened instead? error during build

ERROR in /home/nmcauliffe/gocode/src/github.com/toni-moreno/snmpcollector/src/$$_gendir/common/spinner.ngfactory.ts (53,40): Property 'isDelayedRunning' is private and only accessible within class 'SpinnerComponent'.
ERROR in ng:///home/nmcauliffe/gocode/src/github.com/toni-moreno/snmpcollector/src/common/multiselect-dropdown.ts.MultiselectDropdown.html (4,59): Property 'isVisible' is protected and only accessible within class 'MultiselectDropdown' and its subclasses.
ERROR in /home/nmcauliffe/gocode/src/github.com/toni-moreno/snmpcollector/src/$$_gendir/common/multiselect-dropdown.ngfactory.ts (305,31): Property 'title' is protected and only accessible within class 'MultiselectDropdown' and its subclasses.
npm ERR! code ELIFECYCLE

**Comment by toni-moreno** [comment]
Hi @mcaulifn thank to report this bug We wil review ASAP
