### ISSUE TITLE
Bug docker run on arm fails

### ISSUE THREAD

**Issue by mcaulifn** [toni-moreno/snmpcollector#294]
Please include this information:
- What SnmpCollector version are you using? 0.7.4
- What OS are you running snmpcollector on? Ubuntu 16.04.3 armhf
- What did you do? docker run
- What was the expected result? start container
- What happened instead?

standard_init_linux.go:185: exec user process caused "exec format error"

**Comment by toni-moreno** [comment]
hi @mcaulifn sorry for my late response.

I've been investigating and seems that docker over arm are architecture dependant so the full container should be recreated on your arm linux box.

Could you try build by only changing the base image on the Dockerfile alpine by its arm version on other based architectures ( look correct image on one of these links)

https://github.com/docker-library/official-images#architectures-other-than-amd64

substitute "alpine:latest" by "armXXX/alpine:latest" 

https://github.com/toni-moreno/snmpcollector/blob/914eed4add6f5818428ef3d6147b3cc914c238e6/docker/Dockerfile#L1-L14

after you can build the image by running  build-docker.sh (comment fist the last 2 lines to not push the resulting file on the repository).

https://github.com/toni-moreno/snmpcollector/blob/914eed4add6f5818428ef3d6147b3cc914c238e6/docker/build-docker.sh#L29-L30

Let my know if the resulting docker image is running ok.

**Comment by mcaulifn** [comment]
@toni-moreno I did run build-docker.sh but had forgotten to modify the FROM line. It seems to have built fine.

**Comment by toni-moreno** [comment]
could you tell me what GOARCH an  GOOS are your runtime ?

you can see easily editing this little go script test.go
````golang
package main

import (
	"fmt"
	"runtime"
)

func main() {
	fmt.Printf("GOARCH %s\n",runtime.GOARCH)
	fmt.Printf("GOOS %s\n",runtime.GOOS)
}
````
and run it 

`go run test.go`

perhaps I could add a option to the build system to add cross platform container building system  to the github sources.

**Comment by mcaulifn** [comment]
e@srv02:~$ go run test.go
GOARCH arm
GOOS linux

**Comment by toni-moreno** [comment]
Hi @mcaulifn I've been reviewing how to create different images for different architectures, and not sure how to manage so by now I will only maintain the linux/amd64 architecture based image.
