### ISSUE TITLE
0.7.5 - segmentation violation on arm7/Linux

### ISSUE THREAD

**Issue by janchrillesen** [toni-moreno/snmpcollector#304]
I recently upgraded from 0.7.4 to 0.7.5. 0.7.4 was running fine, after fix from issue #268 

snmpcollector exits with the following:

Dec 19 12:14:37 blackie systemd[1]: Starting SnmpCollector Agent...
Dec 19 12:14:37 blackie systemd[1]: Started SnmpCollector Agent.
Dec 19 12:14:38 blackie snmpcollector[26453]: time="2017-12-19 12:14:38" level=warning msg="No Output default found influxdb devices found !!"
Dec 19 12:14:38 blackie snmpcollector[26453]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 19 12:14:38 blackie snmpcollector[26453]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x475c88]
Dec 19 12:14:38 blackie snmpcollector[26453]: goroutine 281 [running]:
Dec 19 12:14:38 blackie snmpcollector[26453]: github.com/toni-moreno/snmpcollector/pkg/agent/output.(*InfluxDB).GetResetStats(0x957520, 0x10c0f808)
Dec 19 12:14:38 blackie snmpcollector[26453]: /home/chrille/.go/src/github.com/toni-moreno/snmpcollector/pkg/agent/output/influx.go:52 +0x24
Dec 19 12:14:38 blackie snmpcollector[26453]: github.com/toni-moreno/snmpcollector/pkg/agent/selfmon.(*SelfMon).getOutDBStats(0x10db54f0)
Dec 19 12:14:38 blackie snmpcollector[26453]: /home/chrille/.go/src/github.com/toni-moreno/snmpcollector/pkg/agent/selfmon/selfmon.go:226 +0xa4
Dec 19 12:14:38 blackie snmpcollector[26453]: github.com/toni-moreno/snmpcollector/pkg/agent/selfmon.(*SelfMon).reportStats(0x10db54f0, 0x995af0)
Dec 19 12:14:38 blackie snmpcollector[26453]: /home/chrille/.go/src/github.com/toni-moreno/snmpcollector/pkg/agent/selfmon/selfmon.go:342 +0xf4
Dec 19 12:14:38 blackie snmpcollector[26453]: created by github.com/toni-moreno/snmpcollector/pkg/agent/selfmon.(*SelfMon).StartGather
Dec 19 12:14:38 blackie snmpcollector[26453]: /home/chrille/.go/src/github.com/toni-moreno/snmpcollector/pkg/agent/selfmon/selfmon.go:210 +0xc0
Dec 19 12:14:38 blackie systemd[1]: snmpcollector.service: main process exited, code=exited, status=2/INVALIDARGUMENT

snmpcollector v0.7.5 (git: b4f4214 ) built at [2017-12-17 09:39:47]
go version go1.8.3 linux/arm
Linux blackie.chrillesen.dk 4.13.14-sunxi #240 SMP Mon Nov 20 00:09:06 CET 2017 armv7l GNU/Linux

config is unchanged from 0.7.4

**Comment by toni-moreno** [comment]
Thank you to report the bug I will review ASAP

**Comment by toni-moreno** [comment]
This error will happens on all configurations which doesn't has a "default" influxdb definition... I will fix in some minutes..

**Comment by janchrillesen** [comment]
Thank you for a quick fix. I can confirm that it works now
