### ISSUE TITLE
[Feature request] Input validation in ExtraData field for SNMP metrics (or any other fields that can take expressions)

### ISSUE THREAD

**Issue by jensenja** [toni-moreno/snmpcollector#307]
I ran into an issue where I was missing a closing parentheses when I was coming up with the revised formula for Input/Output utilization. The web UI happily accepted the expression, but the missing closing paren caused the application to crash (the golang error was clear as to the reason why). But because my SNMP devices were active, I couldn't restart it until I went into the database by hand and did `update snmp_device_cfg set active = 0;` Some input validation should be used to prevent situations like this from occurring.

**Comment by toni-moreno** [comment]
Hi @jensenja we will review ASAP a way to add extra validation to these ExtraData fields.
