### ISSUE TITLE
[Bug] Login page and 403 forbidden error message

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#312]
- What SnmpCollector version are you using? 0.7.5
- What did you do?
   During opening of login page everytime I'm getting the following error message
![obraz](https://user-images.githubusercontent.com/12551929/34488890-77c8cc76-efda-11e7-8bf4-c4efda7c0ced.png)
 It appears like snmpcollector is trying to open main runtime window first and then returns to the login page with the above error message being displayed. Something has changed in the recent 0.7.5?

**Comment by toni-moreno** [comment]
Hi @pavleec thank you for the bug report we will review ASAP.
