### ISSUE TITLE
[Feature Request] Support writing metrics to > 1 Influx DB/Server

### ISSUE THREAD

**Issue by jackson-tim** [toni-moreno/snmpcollector#316]
Having support for writing metrics to more than 1 Influx server would be awesome.. We're currently using influx-relay, but the ability to just send metrics for a device to multiple back-ends or databases would make this way simpler.

**Comment by jackson-tim** [comment]
Adding to this, writing to Kafka instead of directly to InfluxDB would be even better.

**Comment by jchristopher327** [comment]
I'm able to add another influxDB server as a quick test thinking it would throw an error. Am I missing something? Will it accept a second server but not actually send metrics?

**Comment by jackson-tim** [comment]
There's no way to duplicate metrics to both servers at once.

**Comment by toni-moreno** [comment]
Hi I will close this FR because there is some ways to duplicate metrics with external tools , like ( telegraf https://github.com/influxdata/telegraf and also a smart relay https://github.com/toni-moreno/influxdb-srelay )
