### ISSUE TITLE
[Advice] Current ways to automate provisioning?

### ISSUE THREAD

**Issue by topranks** [toni-moreno/snmpcollector#319]
Apologies for posting this here - not a fault/bug just wanted an opinion if possible.

I have quite a lot of SNMP metrics I need to add to SnmpCollector.  Doing it via the Web GUI - while really good, would be cumbersome.

Looking at the potential to automate it I can think of:

- Creating JSON files to 'import' with all the required elements in them.
- Writing directly to the database.
- Using the internal API which seems to exist but we're unsure of exactly how to use.

I appreciate there is a good bit of information scattered around on all of these, but I'm wondering if you would have a reccomended approach?  Does the internal API use the same JSON formatting as can be seen when the export is run?

Many thanks,

Cathal.

**Comment by tardoe** [comment]
Hey Cathal,

I have a puppet module built for SNMPCollector which I used to add 50+ metrics to the collector. I’m in the process of open sourcing this but I’d be willing to have a few private testers before then. If this might be useful to you, let me know.

Otherwise, write yourself a script against the same POST HTTP endpoint that the web ui uses to create metrics in bulk.

Regards,

Tim Raphael

**Comment by topranks** [comment]
Hey Tim thanks for the info.

I'd be interested to look at your module if that were possible.  Our own automation is built on Ansible, so it may not be an exact fit for out environment.  Still I'd be happy to have a look and let you know if it's something we could test.

In the meantime I'll try to see if I can talk to the HTTP endpoint on the box directly and see how it goes.

Cathal.

**Comment by topranks** [comment]
Struggling a bit with the API for instance....  for instance doing this at the command line but getting a 403 forbidden back :(

```
root@resperf:~# curl -v -H "Content-Type: application/json" -X POST -d "{                   
    "Objects": [{                                                                           
            "ObjectTypeID": "snmpmetriccfg",                                                
            "ObjectID": "ciscoMemoryPoolName",                                              
            "Options": null,                                                                
            "ObjectCfg": {                                                                  
                "ID": "ciscoMemoryPoolName",                                                
                "FieldName": "ciscoMemoryPoolName",                                         
                "Description": "",                                                          
                "BaseOID": ".1.3.6.1.4.1.9.9.48.1.1.1.2",                                   
                "DataSrcType": "OCTETSTRING",                                               
                "GetRate": false,                                                           
                "Scale": 0,                                                                 
                "Shift": 0,                                                                 
                "IsTag": true,                                                              
                "ExtraData": ""                                                             
            },                                                                              
            "Error": ""                                                                     
        }                                                                                   
    ]                                                                                       
}" http://localhost:8090/api/cfg/metric                                                     
Note: Unnecessary use of -X or --request, POST is already inferred.                         
*   Trying ::1...                                                                           
* TCP_NODELAY set                                                                           
* Connected to localhost (::1) port 8090 (#0)                                               
> POST /api/cfg/metric HTTP/1.1                                                             
> Host: localhost:8090                                                                      
> User-Agent: curl/7.52.1                                                                   
> Accept: */*                                                                               
> Content-Type: application/json                                                            
> Content-Length: 1191                                                                      
> Expect: 100-continue                                                                      
>                                                                                           
< HTTP/1.1 403 Forbidden                                                                    
< Content-Type: application/json; charset=UTF-8                                             
< Set-Cookie: snmpcollector-sess-my_instance_cookie=2fce135e4396016f; Path=/; HttpOnly      
< Date: Mon, 29 Jan 2018 14:05:41 GMT                                                       
< Content-Length: 2                                                                         
< Connection: close                                                                         
<                                                                                           
* Curl_http_done: called premature == 0                                                     
* Closing connection 0                                                                      
```

This is also visible in the http_access.log file:
```
[Macaron] 2018-01-29 14:01:52: Started POST /api/cfg/metric for [::1]
[Macaron] 2018-01-29 14:01:52: Completed /api/cfg/metric 403 Forbidden in 403.791µs
```

I've tried curl with -u specifying the web user and password but get the same thing.  I guess I could try to send the cookie from my browser but I figure I'm doing something else wrong here?

Cathal.

**Comment by toni-moreno** [comment]
Hi @topranks I suggest play a bit with the export/import WEB-UI . 

![image](https://user-images.githubusercontent.com/5883405/35514938-1bfb9160-0508-11e8-91a0-401d20c0ac70.png)

After you can use the export WEB_UI to generate a Template and the import API to add any based templated generated with the import API (/api/cfg/import) 


Example with curl: ( you need a valid cookie got from the login process) 

```
curl --cookie "snmpcollector-sess-instance-cookie=XXXXXXXXXXX"  -F "auto_rename=false" -F "over_write=true" -F "export_file=@/path/where/the/file/is/exported_file.json" http://snmpcollector/api/cfg/import
````

**Comment by topranks** [comment]
Ok thanks Toni!

Looks like I'd been passing the wrong Cookie, I managed to work out what was going on by looking at the export JSON and also the interaction in wireshark.

All working for me now so I can go ahead and play with it.  As ever thanks for the help!

```
cmooney@AS-LT-33:~$ curl --cookie "snmpcollector-sess-my_instance_cookie=f533576b0f4e1f9e" -v -H "Content-Type: application/json" -X POST -d '{
  "ID": "ciscoMemoryPoolUsed",
  "FieldName": "ciscoMemoryPoolUsed",
  "DataSrcType": "Gauge32",
  "IsTag": false,
  "Description": "hey hey",
  "BaseOID": ".1.3.6.1.4.1.9.9.48.1.1.1.5"
}' http://172.17.4.187:8090/api/cfg/metric
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 172.17.4.187...
* Connected to 172.17.4.187 (172.17.4.187) port 8090 (#0)
> POST /api/cfg/metric HTTP/1.1
> Host: 172.17.4.187:8090
> User-Agent: curl/7.47.0
> Accept: */*
> Cookie: snmpcollector-sess-my_instance_cookie=f533576b0f4e1f9e
> Content-Type: application/json
> Content-Length: 189
>
* upload completely sent off: 189 out of 189 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Date: Mon, 29 Jan 2018 16:08:59 GMT
< Content-Length: 256
<
{
  "ID": "ciscoMemoryPoolUsed",
  "FieldName": "ciscoMemoryPoolUsed",
  "Description": "hey hey",
  "BaseOID": ".1.3.6.1.4.1.9.9.48.1.1.1.5",
  "DataSrcType": "Gauge32",
  "GetRate": false,
  "Scale": 0,
  "Shift": 0,
  "IsTag": false,
  "ExtraData": ""
* Connection #0 to host 172.17.4.187 left intact
}
```

**Comment by topranks** [comment]
I've created a little Python script to show how to use the API in case anyone else hits the issue's I've seen.  Very basic example of how it can be used anyway:

https://github.com/topranks/addsnmpcollectordevices

**Comment by tardoe** [comment]
To follow up on this one, the organisation I work for has recently open sourced the Puppet module we're using to automate SNMPCollector (https://github.com/ixaustralia/ixaustralia-snmpcollector). @toni-moreno please feel free to list this on your docs / wiki as we welcome users and contributions.

**Comment by toni-moreno** [comment]
Hi  Thank you both @topranks and @tardoe  we will update  the wiki with your contributions ASAP.

**Comment by toni-moreno** [comment]
Hi @topranks @tardoe , I've just updated the wiki with your links. Thanks again!

https://github.com/toni-moreno/snmpcollector/wiki/SnmpCollector-Automations
