### ISSUE TITLE
[Bug] npm prod build fails because of Angular AOT compiler

### ISSUE THREAD

**Issue by samaust** [toni-moreno/snmpcollector#323]
I'm building master from source on Debian Stretch. I did

go get -d github.com/toni-moreno/snmpcollector/...
cd $GOPATH/src/github.com/toni-moreno/snmpcollector
go run build.go setup
godep restore

I installed nodejs 8. I've got nodejs v8.9.4 et npm v5.6.0.

Then I did 

npm install
export PATH=$(npm bin):$PATH 
npm run build:prod

I'm getting the error 

ERROR in ng:///home/auss/go/src/github.com/toni-moreno/snmpcollector/src/common/table-list.component.ts.TableListComponent.html (27,48): Property 'editEnabled' is private and only accessible within class 'TableListComponent'.

From searching that error message on google, it looks like this happens because compiling with prod enables Angular AOT compiler and that requires all properties to be public.

**Comment by toni-moreno** [comment]
Hi @samaust , I've just commited a fix for this error. Could you pull and test again?

**Comment by samaust** [comment]
Hi. The fix worked. It compiles without errors.
