### ISSUE TITLE
[Bug] ENUM generates int64 field if it is not mapped on ExtraData

### ISSUE THREAD

**Issue by sbengo** [toni-moreno/snmpcollector#329]
Hi,

Testing last marged PR #327 , it seems that we missed the case when the field is set up with `IsTag = false`.

@simnv , can you review it please?

### Description

As it is shown on the following code snippet, if the value is not mapped on the `ExtraData` it will store the cooked value as an int64 and it will fail on writting to InfluxDB due to missmatching fieldKey type

https://github.com/toni-moreno/snmpcollector/blob/67dd19ea1f317250fc89ea9f292d8b8f115c5e1a/pkg/data/metric/snmpmetric.go#L326-L336

### Example:

ifType query returns: ` [6,24]`

Setting up a Field called ifType_ENUM with only the 24 mapped:

|ID |FieldName |BaseOID |DataSrcType |ExtraData | isTag
|----|------- | --------| ---------- | -------- |----
|ifType_ENUM|ifTtype_ENUM_Other|.1.3.6.1.2.1.2.2.1.3|ENUM|Test (24)|false

The measurements are trying to be built using the following values:
````
time="2018-03-02 11:44:50" level=debug msg="SETRAW ENUM map[24:Test(24)], RESULT Test(24)" 
time="2018-03-02 11:44:50" level=debug msg="SETRAW ENUM map[24:Test(24)], RESULT %!s(int64=6)" 
````

And InfluxDB client throws error due to missmatching type:
````
level=error msg="ERROR on Write batchPoint in DB default (2 points) | elapsed : 2.459507ms | Error: {"error":"field type conflict: input field \"ifTtype_ENUM_Other\" on measurement \"ifType_TEST_ENUM\" is type int64, already exists as type string"}
````

Thanks!

**Comment by simnv** [comment]
@sbengo Indeed, my bad. What do you think is better, to convert int64 to string or don't send anything if there is no matching enum? I think, string would be better.

**Comment by sbengo** [comment]
Hello @simnv !

I think it is better to convert it as STRING. If the user wants only to send the mapped values, it can be achieved using a Measurement filter!

Thanks for the prompt answer and for this feature!!
Regards
