### ISSUE TITLE
Convert Integer values

### ISSUE THREAD

**Issue by jasonyates** [toni-moreno/snmpcollector#331]
I'm not sure of the best way to describe this issue but if I poll an OID using the vendor supplied MIB the resulting Integer gets converted to a useful piece of text. When i'm polling with SNMPCollector that does not happen and the raw Integer gets reported to InfluxDB.

Is there any way to have SNMPCollector return the converted text too?

appRouteStatisticsLocalColor OBJECT-TYPE
    SYNTAX      INTEGER {default(1),mpls(2),metro-ethernet(3),biz-internet(4),public-internet(5),lte(6),threeG(7),red(8),green(9),blue(10),gold(11),silver(12),bronze(13),custom1(14),custom2(15),custom3(16),private1(17),private2(18),private3(19),private4(20),private5(21),private6(22)}
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION "Local TLOC color"
    ::= { appRouteStatisticsEntry 7 }

**Comment by sbengo** [comment]
Hello @jasonyates , if I have not misunderstood, what you need is to map the values ​​that are retrieved by SNMP and are defined as ENUM structure.

This was just implemented few days ago on PR  #327 but the version 0.7.7 is not released yet. If you need this feature on a short term, you can build SNMPCollector from source!

If you need more info about how to configure new ENUM metric, you can check the updated [WIKI](https://github.com/toni-moreno/snmpcollector/wiki/Component:-SNMP-Metrics#about-enum-metric-type)

Thanks,
Regards!

**Comment by jasonyates** [comment]
That's exactly what i'm after. Thanks! 

Any idea on when 0.7.7 will be released?

**Comment by sbengo** [comment]
Hello!

I'm afraid that it would be on few weeks from now. I recommend you to try to build from source and  test the new feature.

If you don't have any other question, can we close this issue?

Thanks,
Regards!

**Comment by jasonyates** [comment]
Yes thats fine.

Thanks
