### ISSUE TITLE
Unable to poll single device

### ISSUE THREAD

**Issue by jasonyates** [toni-moreno/snmpcollector#332]
I have an odd situation polling a Cisco Viptela vEdge device. I have an indexed Influx Measurement setup which works perfectly against one device, but fails against another. Both devices have the same hardware and software configuration. Enabling SNMP Debugging does not yield much useful data.

I don't see this being a problem with the end device as a manual walk of the device yields an exact same SNMP response. Any help would be appreciated.

**non-working device**
time="2018-03-09 07:54:24" level=info msg="SNMPDEVICE [czprg3-cve01] SNMP connection stablished Successfully for device  and measurement viptela_interfaces"
time="2018-03-09 07:54:24" level=info msg="MEASUREMENT [viptela_interfaces] Loading Indexed values"
time="2018-03-09 07:54:24" level=debug msg="MEASUREMENT [viptela_interfaces] Looking up column names .1.3.6.1.4.1.41916.12.2.1.3 "
time="2018-03-09 07:54:44" level=error msg="MEASUREMENT [viptela_interfaces] SNMP WALK error: Request timeout (after 5 retries)"
time="2018-03-09 07:54:44" level=error msg="MEASUREMENT [viptela_interfaces] Error while trying to load Indexed Labels on for measurement : for baseOid .1.3.6.1.4.1.41916.12.2.1.3 : ERROR: Request timeout (after 5 retries)"
time="2018-03-09 07:54:44" level=error msg="SNMPDEVICE [czprg3-cve01] Error on measurement initialization  Error: Request timeout (after 5 retries)"

**A manual walk of that OID for that device works fine.**
snmpwalk -v3 -l authNoPriv -u **** -a MD5 -A **** <my_device> .1.3.6.1.4.1.41916.12.2.1.3
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.5.103.101.50.47.48.0 = STRING: "xxx.xxx.xxx.234/30"
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.5.103.101.50.47.49.0 = STRING: "xxx.xxx.xxx.141/28"
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.6.115.121.115.116.101.109.0 = STRING: "xxx.xxx.xxx.9/32"
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.11.49.48.103.101.48.47.48.46.49.48.48.0 = STRING: "xxx.xxx.xxx.2/30"
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.11.49.48.103.101.48.47.48.46.50.48.48.0 = STRING: "xxx.xxx.xxx.6/30"
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.11.49.48.103.101.48.47.48.46.51.48.48.0 = STRING: "xxx.xxx.xxx.230/30"
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.11.49.48.103.101.48.47.48.46.52.48.48.0 = STRING: "xxx.xxx.xxx.222/30"

**Working device**
time="2018-03-09 08:06:53" level=info msg="MEASUREMENT [viptela_interfaces] Loading Indexed values"
time="2018-03-09 08:06:53" level=debug msg="MEASUREMENT [viptela_interfaces] Looking up column names .1.3.6.1.4.1.41916.12.2.1.3.0 "
time="2018-03-09 08:06:54" level=debug msg="MEASUREMENT [viptela_interfaces] received SNMP  pdu:{Name:.1.3.6.1.4.1.41916.12.2.1.3.0.5.103.101.49.47.50.0 Type:4 Value:[49 55 50 46 49 54 46 54 53 46 53 48 47 51 48] Logger:0xc4207a2320}"
time="2018-03-09 08:06:54" level=debug msg="MEASUREMENT [viptela_interfaces] received SNMP  pdu:{Name:.1.3.6.1.4.1.41916.12.2.1.3.0.6.115.121.115.116.101.109.0 Type:4 Value:[49 55 50 46 49 54 46 50 53 51 46 50 50 47 51 50] Logger:0xc4207a2320}"
time="2018-03-09 08:06:54" level=debug msg="MEASUREMENT [viptela_interfaces] received SNMP  pdu:{Name:.1.3.6.1.4.1.41916.12.2.1.3.0.9.103.101.49.47.55.46.49.48.48.0 Type:4 Value:[49 57 50 46 49 54 56 46 49 48 48 46 50 47 51 48] Logger:0xc4207a2320}"
time="2018-03-09 08:06:54" level=debug msg="MEASUREMENT [viptela_interfaces] received SNMP  pdu:{Name:.1.3.6.1.4.1.41916.12.2.1.3.0.9.103.101.49.47.55.46.51.48.48.0 Type:4 Value:[49 55 50 46 49 54 46 54 53 46 53 52 47 51 48] Logger:0xc4207a2320}"
time="2018-03-09 08:06:54" level=debug msg="MEASUREMENT [viptela_interfaces] Initialize OID measurement per label => map of metric object per field | OID array [ready to send to the walk device] | OID=>Metric MAP"
time="2018-03-09 08:06:54" level=debug msg="MEASUREMENT [viptela_interfaces] METRICTABLE: initializing [indexed] metric cfg for [5.103.101.49.47.50.0/5.103.101.49.47.50.0]"
time="2018-03-09 08:06:54" level=debug msg="MEASUREMENT [viptela_interfaces] METRICTABLE: initializing [indexed] metric cfg for [6.115.121.115.116.101.109.0/6.115.121.115.116.101.109.0]"
time="2018-03-09 08:06:54" level=debug msg="MEASUREMENT [viptela_interfaces] METRICTABLE: initializing [indexed] metric cfg for [9.103.101.49.47.55.46.49.48.48.0/9.103.101.49.47.55.46.49.48.48.0]"
time="2018-03-09 08:06:54" level=debug msg="MEASUREMENT [viptela_interfaces] METRICTABLE: initializing [indexed] metric cfg for [9.103.101.49.47.55.46.51.48.48.0/9.103.101.49.47.55.46.51.48.48.0]"

**A manual walk of working device**
snmpwalk -v3 -l authNoPriv -u **** -a MD5 -A **** <my_device> .1.3.6.1.4.1.41916.12.2.1.3
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.5.103.101.49.47.50.0 = STRING: "xxx.xxx.xxx.50/30"
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.6.115.121.115.116.101.109.0 = STRING: "xxx.xxx.xxx.22/32"
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.9.103.101.49.47.55.46.49.48.48.0 = STRING: "xxx.xxx.xxx.2/30"
SNMPv2-SMI::enterprises.41916.12.2.1.3.0.9.103.101.49.47.55.46.51.48.48.0 = STRING: "xxx.xxx.xxx.54/30"
SNMPv2-SMI::enterprises.41916.12.2.1.3.10.5.103.101.49.47.54.0 = STRING: "xxx.xxx.xxx.254/30"
SNMPv2-SMI::enterprises.41916.12.2.1.3.10.11.108.111.111.112.98.97.99.107.49.50.52.0 = STRING: "xxx.xxx.xxx.13/32"
SNMPv2-SMI::enterprises.41916.12.2.1.3.512.5.109.103.109.116.48.0 = STRING: "xxx.xxx.xxx.1/24"

**Comment by sbengo** [comment]
Hello @jasonyates 

First of all, a silly question: on your logs I see different OIDs: 
````
.1.3.6.1.4.1.41916.12.2.1.3.0 on working device
.1.3.6.1.4.1.41916.12.2.1.3 nonWorking.
````
Have you  configured both devices with the same `MeasGroup` and obviously, same `Measurement`?

We need more information to see whats happening on your device:

1. Can you tell us if its the only measurement that is having problems? Can you configure another measurement/metric in order to avoid connectivity problems?
2. Can you attach a Test connection modal query with the problematic OID and another OID (i.e: configured on "1")?

Thanks,
Regards!

**Comment by jasonyates** [comment]
Hi,

The difference in the OID's was just me changing the settings and copying the wrong logs. Neither OID works on the non-working device, both work on the working device.

Yes they are configured exactly the same. It is the only measurement that is having issues, I have 2 other measurements in the measurement group that are working perfectly fine against both devices.

Interestingly, if I use test connection and walk the OID, it works from both devices. 

<img width="1087" alt="screenshot 2018-03-09 22 18 43" src="https://user-images.githubusercontent.com/242483/37232703-1495231a-23e8-11e8-8808-1e58434ae1b5.png">

<img width="1091" alt="screenshot 2018-03-09 22 18 18" src="https://user-images.githubusercontent.com/242483/37232705-14c9ad06-23e8-11e8-9213-f91423c0a1f0.png">

Below is my measurement config:

{
  "ID": "viptela_interfaces",
  "Name": "viptela_interfaces",
  "GetMode": "indexed",
  "IndexOID": ".1.3.6.1.4.1.41916.12.2.1.3",
  "TagOID": "",
  "IndexTag": "interfaceIpAddress",
  "IndexTagFormat": "",
  "IndexAsValue": true,
  "Fields": [
    {
      "ID": "viptela_interfaceBandwidthDownstream",
      "Report": 1
    },
    {
      "ID": "viptela_interfaceBandwidthUpstream",
      "Report": 1
    },
    {
      "ID": "viptela_interfacePortType",
      "Report": 0
    },
    {
      "ID": "viptela_interfaceRxOctets",
      "Report": 1
    },
    {
      "ID": "viptela_interfaceTxOctets",
      "Report": 1
    },
    {
      "ID": "viptela_interfaceIfAdminStatus",
      "Report": 1
    },
    {
      "ID": "viptela_interfaceIfOperStatus",
      "Report": 1
    },
    {
      "ID": "viptela_interfaceDesc",
      "Report": 1
    },
    {
      "ID": "viptela_interfaceRxUsage",
      "Report": 1
    },
    {
      "ID": "viptela_interfaceTxUsage",
      "Report": 1
    }
  ],
  "Description": "Viptela Interface Polling"
}

**Comment by sbengo** [comment]
Hi!

Thanks for the info. Everything looks fine and as it is shown on your walk done in TestConnection modal, it seems to work fine when a simple poll is done.

I want you to make a new test:
- Can you change the `Max Repetitions = 10` on non working device?

If it works:
- Can you try to change it also on the working device and compare the polling time with `MaxRepetitions=50` and `MaxRepetitions=10`

**Comment by jasonyates** [comment]
Hi,

Interestingly, this fixes it. Reducing it to 10 on all non-working devices works perfectly.

Reducing the working device to 10 has no impact on the polling time, it takes just over 4 seconds in both configurations.

Why does that make such a difference?

Thanks

**Comment by sbengo** [comment]
Hello @jasonyates 

The SNMPCollector retrieves data using a snmpbulkwalk operations in order to be able to get a large amount of data.

Setting up a high MaxRepetitions seems that can saturate the device on large tables, so setting it at 10 reduces the number of internal snmp GETNEXT operations and the device is able answer correctly

As it seems that your devices are working after this change, can we close this issue?

**Comment by jasonyates** [comment]
Sure thing.

Is it worth adding a note to the documentation or app itself to suggest lowering if it issues are encountered?

**Comment by sbengo** [comment]
Yes @jasonyates , we have it on mind... we want to improve our WIKI and some UI tooltips!

Thanks
Regards!
