### ISSUE TITLE
[Bug]? Help with filtering "--Controlled" and "--Uncontrolled" IOS-XE interfaces from being polled.

### ISSUE THREAD

**Issue by jchristopher327** [toni-moreno/snmpcollector#333]
Hi,

I'm trying to get snmpcolletor to not bother with certain ports in IOS-XE that show up as` --Controlled` and `--Uncontrolled`. This adds necessary load and time spent which doesn't add anything of value. I tried using filters to try and accomplish with no luck.

- What SnmpCollector version are you using?
```
snmpcollector v0.7.4 (git: 304bb8d ) built at [2017-09-23 00:23:30]
```
- What OS are you running snmpcollector on?
```
CentOS Linux release 7.3.1611 (Core)
```
- What did you do?
I created an IOD condition to match (also tried notmatch) for `.*[C|Unc]ontrolled$`. I then referenced this in a measurement filter.

![screen shot 2018-03-13 at 2 27 40 pm](https://user-images.githubusercontent.com/17171652/37371000-2f15e752-26cb-11e8-8ebf-979e2fd5a292.png)

![screen shot 2018-03-13 at 2 28 23 pm](https://user-images.githubusercontent.com/17171652/37371007-33b6830c-26cb-11e8-8546-ef66463e3b02.png)

- What was the expected result?
The expected result is to prevent snmpcollector from polling any interfaces with `.*[C|Unc]ontrolled$`. Below is some SNMP output of such interfaces.
```
IF-MIB::ifDescr.25 = STRING: TenGigabitEthernet1/1--Uncontrolled
IF-MIB::ifDescr.26 = STRING: TenGigabitEthernet1/1--Controlled
IF-MIB::ifDescr.27 = STRING: TenGigabitEthernet1/2--Uncontrolled
IF-MIB::ifDescr.28 = STRING: TenGigabitEthernet1/2--Controlled
IF-MIB::ifDescr.29 = STRING: TenGigabitEthernet1/3--Uncontrolled
IF-MIB::ifDescr.30 = STRING: TenGigabitEthernet1/3--Controlled
```
- What happened instead?
Nothing happened. I still see those interfaces being polled when looking at the device through runtime.

**Comment by toni-moreno** [comment]
Hi   @jchristopher327  did you assign the Condition filter to the device  where you have previuoly defined "interface" as and indexed measurement  ?

**Comment by jchristopher327** [comment]
@toni-moreno :(

That was my issue. Thanks for pointing it out!
