### ISSUE TITLE
[Feature Request] Maximum increment setting for "COOKED" counters

### ISSUE THREAD

**Issue by topranks** [toni-moreno/snmpcollector#339]
Hey,

One thing that causes us issues sometimes (when graphing etc.) is what happens when our devices reset.

So for instance when one of our devices resets, when it comes back up the SNMP counters all start back at zero.  SNMP Collector, on next reading, thinks that the counter had hit 2^32 / 2^64 and rolled over, and calculates a wildly inaccurate rate.

With 64-bit counters this is particularly bad.  We end up with interface throughput graph showing 1 Ebps!  We use Grafana so this throws the auto-scaling off completely.  We could set the min and max in Grafana statically of course, but we'd rather leave it to auto scale.  

Could a setting be enabled on a SNMP Metric where you can state the maximum delta allowed for that measure?  So for instance if we have a 1G interface we could set it to that.  If a delta is calculated more than that it should not be written to the DB?

I can possibly even help with this if that's appreciated.  My Go is novice level but I suspect this wouldn't be too hard to add.

Cathal.

**Comment by sbengo** [comment]
Hello @topranks , sorry for the late response.

There are 2 ways that your issue/FR can be solved/achieved:

### COUNTERXX

Some time ago we had seen the same behaivour as you describe so we decided to create a new cooked metric called `COUNTERXX`. This counter doesn't send any value when detects that the `current_value<old_value` so it fits when the counter is reset or some strange behaviour happened.

### STRINGEVAL 
_Note: I did not test the following method, and I'm not sure  if it would cause some strange behaviour on SNMPCollector_

As it is explained on the [WIKI](https://github.com/toni-moreno/snmpcollector/wiki/Component:-SNMP-Metrics#about-stringeval-metrics), the library that evals the metrics allows to set up ternary expressions, so you can define a new metric based on the `COUNTER32/64` and set up an expression using the [ternary](https://github.com/Knetic/govaluate/blob/master/MANUAL.md#ternary-true-)

For example: 

````
Metric 1 - ifHCInOctets -  COUNTER64
Metric 2 - ifHCInOctets_nonNegative - STRINGEVAL - ifHCInOctets > <VALUE> ? ifHCInOctets : 0
````

**Comment by topranks** [comment]
Ok thank you very much for the detailed response.

I guess I should have checked the existing options in more detail.  I think the COUNTERXX will suit us, but I am also having ideas now that I've seen your conditional STRINGEVAL.  Lots of possibilities!

Thanks.
