### ISSUE TITLE
 [Feature request] import data with REST API

### ISSUE THREAD

**Issue by fri-it2** [toni-moreno/snmpcollector#340]
Hello!

I have test version of  SnmpCollectorand  more production versions
In the test version of SnmpCollector I exported data from different components.
Is it possible to import data in JSON format data via REST API for production version?

Best regards,
Tadeja

**Comment by toni-moreno** [comment]
Hi @fri-it2, you can do via API everything you can do with the WebUI, but there is not a good API documentation.

Anyway  I suggest you review this other issue , with one example on how to import data from a previously created export File. (https://github.com/toni-moreno/snmpcollector/issues/319#issuecomment-361276909)

**Comment by fri-it2** [comment]
Hi @toni-moreno!
Very helpfull.
Best regards,
Tadeja.
