### ISSUE TITLE
Need help with configuration

### ISSUE THREAD

**Issue by jensenja** [toni-moreno/snmpcollector#342]
Hi,

I'm not quite sure how to go about doing this, but I'm attempting to poll a specific oid on my Brocade equipment which essentially tells me the member VPLS of a given interface. The returned result is a table, but I'm basically only interested in the following:

`root@c821c0704953:~# snmpwalk -On -M .snmp/mibs -m +ALL -v2c -c public 10.4.2.20 FDRY-MPLS-L2VPN-MIB::fdryVplsEndPoint2VlanTagMode 2>/dev/null
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.1.90.1.0.287 = INTEGER: untagged(2)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.2.100.1.0.11 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.2.100.1.0.23 = INTEGER: untagged(2)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.2.100.1.0.24 = INTEGER: untagged(2)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.2.100.1.0.48 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.2.100.1.0.81 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.3.102.1.0.11 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.3.102.1.0.48 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.3.102.1.0.81 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.4.236.1.0.12 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.5.140.1.0.43 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.6.1283.1.0.83 = INTEGER: untagged(2)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.7.400.1.0.8 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.7.400.1.0.64 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.7.402.1.0.288 = INTEGER: tagged(1)
.1.3.6.1.4.1.1991.1.2.15.2.2.3.1.5.8.401.1.0.64 = INTEGER: tagged(1)`

I don't care about the value (whether it's tagged or untagged) but I do care about the parts of the OID at the following positions:

`-1` - the ifIndex
`-4` - the VPLS VLAN ID

How do I go about extracting those parts of the table info and pass them to the influx measurement, for other standard pieces I'm already collecting, ie ifHCInOctets, OutOctets, etc? I'm fine with creating duplicate measurements to do what I need to do.

**Comment by jensenja** [comment]
Hi @sbengo - thanks very much for the pointer. My next question is - will I be able to structure a hypothetical query as: "show me all ifHCInOctets for interfaces in VPLS VLAN 100" if the two measurements cannot be related?

**Comment by sbengo** [comment]
Hi @jensenja !

Directly, doing an InfluxDB query to obtain ifHCInOctets on `meas1` it is not possible to do a `WHERE` statement on your `VPLS VLAN ID` (stored on meas2) as it it not related with any series on your `meas1`...

Thanks,
Regards!
