### ISSUE TITLE
[Bug] Memory leak/time drift issue

### ISSUE THREAD

**Issue by TeraHz** [toni-moreno/snmpcollector#346]
- What SnmpCollector version are you using?
0.7.6
- What OS are you running snmpcollector on?
CentOS7/Docker 18.03.1-ce
- What did you do?
Review the data in Influx/Grafana
- What was the expected result?
To see up to date data
- What happened instead?
Data is slowly falling behind - the longer snmpcollector runs, the further back is the last data entry. 

I'm running it as a docker swarm service using the example in the wiki, mounting conf and log from the host.

I captured a packet about 8 hours into it being up and at 2018-05-11 20:37:38 the POST has a timestamp of 2018-05-11 20:35:00 - so roughly 2-3 minutes behind after 8 hours. 

Restarting the container fixes the drift immediately. Date in the container, host and influx server maintain synchronization. 

Initially I thought it was due to a single device taking more than 10 seconds to respond to the poll and had a 10 second poll frequency. After I changed the poll frequency to 30 seconds, I saw the same issue. In fact, over the last 16 hours, it has fallen behind almost 3 hours. The same drift applies to the internal snmpstats. The screenshot below was taken around 9:12 and the last entry was at 6:28.

![gvm](https://user-images.githubusercontent.com/1334076/40366293-c5fd9268-5da4-11e8-97cb-a3b827c7d56d.png)

It does look like the GVM is running out of memory, potentially, but I don't know why. 

What else can I look at to try and debug this better?

**Comment by toni-moreno** [comment]
Hi @TeraHz is really strange thing . 

The same collector has a debug tool in http://<your_server_url>/debug/profile/ . Click on "Dump memory profile" and a file will be created on your >base dir>/profile/mem-XXX.memprof

you can attach this  generated file to this issue. 

Also would be nice if you can show us how many devices / measurements and indexes for each indexed measurement are you gathering on each gathering period. And also what kind of measurements. 

If using filters also could be interesting inspect your filters.

**Comment by TeraHz** [comment]
@toni-moreno yeah, very odd. I think I managed to work around it by increasing the poll frequency on all devices to 30 seconds. It's been stable all day. I'll set it back to 10 seconds on the fast devices and 30 for the one slow device and leave it overnight to generate a dump. Sorry if I missed the debug/profile bits in the Troubleshooting pages in the wiki. I read them, I promise! :)

I'll give you the data tomorrow morning.

**Comment by TeraHz** [comment]
@toni-moreno  Here is a view of the metrics dashboard (when the collector is happy) and the memprof file from this morning with the issue reproduced.
![metrics](https://user-images.githubusercontent.com/1334076/40433713-9b628910-5e7a-11e8-97f6-32c813ba1d9a.png)
[mem-7.memprof.gz](https://github.com/toni-moreno/snmpcollector/files/2031682/mem-7.memprof.gz)

Just a note, the screenshot says we have 166 devices, but we actually have 86 SNMP devices. To give a better overview, there are about 80 switches, with a single measurement of 9 metrics - basically switch ports. Most switches are with 48 ports, one is with few hundred (the one that takes about 10 second). The rest of the SNMP devices are smaller random things (like ac/ups things).

And it seems like I have to keep the frequency time on all devices to be above the max cycle gather time to avoid the issue.

**Comment by toni-moreno** [comment]
Hi @TeraHz ,sorry  I'm just viewing some single stat values but not the  heap/memory consumption for some hours/days to see what exactly means "issue reproduced".

I can neither understand when you say "I have to keep the frequency time on all devices to be above the max cycle gather time to avoid the issue".
 
Could you show me please heap/memory/cpu evolution on both cases ?  ( and also memprof )

a) freq time >  max cycle gather (on all devices).
b) freq time  sometimes lower than the max cycle gather 

 Thank you very much and sorry for this issue.

**Comment by TeraHz** [comment]
Hi @toni-moreno I was out for a week so didn't get a chance until now. Here are the two cases.
a)[case1.tar.gz](https://github.com/toni-moreno/snmpcollector/files/2081138/case1.tar.gz)
b)[case2.tar.gz](https://github.com/toni-moreno/snmpcollector/files/2081137/case2.tar.gz)

**Comment by toni-moreno** [comment]
Hello @TeraHz , this is a very old issue from a very old version,. I hope you fixed then, if not please update to the last version and review if your issue has been fixed. I will close but feel free to reopen if needed.
