### ISSUE TITLE
Cisco QOS MIB monitoring

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#348]
Hi Toni,

Do you think if snmpcollector will be able to handle a little complicated Cisco QOS MIB polling, in a way as described here https://blog.sys4.de/monitoring-qos-cisco-routers-en.html for instance?
Regards,
PaVliK

**Comment by toni-moreno** [comment]
Hi @pavleec  we will review this document ASAP and  will answer you question

**Comment by sbengo** [comment]
Implemented on #459 !
