### ISSUE TITLE
[Feature Request] Add/Delete/Modify devices online ( without complete config reload) 

### ISSUE THREAD

**Issue by toni-moreno** [toni-moreno/snmpcollector#349]
Right now when any  configuration is changed it is saved on the config database, but nothing happens on the runtime gathering processing until a "reload config" is done ( from the web ui or with kill -HUP <pid> on the command line  --since 0.7.7 version--) , this reload process stop all device gathering goroutines , reload metrics/measurements/filters/etc on memory and after restart all device gathering goroutines again.

In order to improve device gathering uptime and also enabling device gathering automation would be nice if our snmpcollector could add/modify and also delete  new devices ( with already predefined measurements groups and also predefined filters) save this device in the configuration database and begin the snmp gathering process without a complete config reload as is needed now ( if there is no need to reload any new measurement config).

**Comment by sbengo** [comment]
Implemented on #358

**Comment by wurmrobert** [comment]
@sbengo are you sure that the `DeleteDeviceInRuntime` is working?

In the snmpdevice bus message [syncexit](https://github.com/toni-moreno/snmpcollector/blob/2ed85980ba75ccc16445f905949344fb31f6c66a/pkg/agent/device/snmpdevice.go#L748) you set the  `isStopped ` to true.

But the gathering loop doesn´t stop after the `syncexit` and therefore the device is not removed from the gathering process.
For me it looks like an infinite gathering loop.

Any ideas?
