### ISSUE TITLE
[Feature Request] Save both 'COOKED' and raw counter data to InfluxDB

### ISSUE THREAD

**Issue by topranks** [toni-moreno/snmpcollector#350]
Hey,

Would it be possible to add a switch so that when using 'COOKED' metrics for SNMP Counters, both the cooked value and the original counter value would be written to InfluxDB?

The field name could be the same as the standard one with a user-selectable suffix ("_counter" for example,) added to the one used for the original value.

We tend to use Cooked values, as this is most performant when graphing etc.  But there are occasions when access to the raw counter values can be useful, for instance to determine the absolute number of events, rather than only having the average number per second stored.

Cathal.

**Comment by topranks** [comment]
Any thoughts on this one?

**Comment by toni-moreno** [comment]
@topranks  I'm reviewing needs for new snmpcollector releases and this one seem not to have followers. I will close, but could be reopened if some other people think it could be a interesting feature for 2.0 snmpcollector.
