### ISSUE TITLE
Value conversation

### ISSUE THREAD

**Issue by chappi6** [toni-moreno/snmpcollector#351]
Hi,

Is it possible to parse a ocetestring to one Integer?
I have a cisco box which returns me the the number of droped packages as octetstring, but for processing with influxdb/grafana i need this value as int or gauge value. 
Thx for help.

**Comment by toni-moreno** [comment]
Hi @chappi6 we have plans to add type conversion feature for metrics, soon.

**Comment by chappi6** [comment]
Good to know! 
Is there for now a hack around ?
Or is version 0.8 not to far away ? 

Br

**Comment by sbengo** [comment]
Hi @chappi6 

It is actually possible and supported. It can be achieved using one of the following metric cooked types:

### STRINGPARSER

The string can be parsed with a regex and the result is sent as a float.
We are actually using it to retrieve information about temperature or the rpm of the fans.

Example:

Query OID | Type | Result
-- | -- | --
.1.3.6..... | OctetString | `FAN 5: 7985 RPM`

We want to  retrieve the number `7985` so we define a new metric of type STRINGPARSER:

FieldName|Type | Regex
--|-- | -- 
fan5_speed|STRINGPARSER | `FAN  5: *([0-9]+) RPM`

The output would be a field `fan5_speed` with the value 7985

### MULTISTRINGPARSER

In this case the MULTISTRINGPARSER allows you to get more than field from a simple query and using regex to define those fields/tags.

**Important: there  is a bug on 0.7.7 that you can not set the field as a float (but you can set it as an integer) already fixed on #353 , but not realeased yet. If you want to send the value as a float we recommend you to build from source**

Using the same example:

Query OID | Type | Result
-- | -- | --
.1.3.6....| OctetString | `FAN 5: 7985 RPM`

In this case, we want to  retrieve the number `7985` and also the fan number `FAN 5`, so we define a new metric of type MULTISTRINGPARSER:

FieldName|Type | Regex
--|-- | -- 
T\|fanNumber\|STR,F\|fan_speed\|INT|MULTISTRINGPARSER | `(.*): *([0-9]+) RPM`

The output would be:
- Tag `fanNumber` with value (string) `FAN 5`
- Field `fan_speed` with value (integer) `7985`

----

Thanks,
Best regards
