### ISSUE TITLE
[Bug] STRINGEVAL handling w/GoValuate & field names

### ISSUE THREAD

**Issue by jensenja** [toni-moreno/snmpcollector#356]
This all came about as I was trying to incorporate templates into a Grafana dashboard. Here is some background/context:

I have different Influx databases per "device class", and each database has a standard set of retention policies:

```> show retention policies on snmp_brcd
name    duration   shardGroupDuration replicaN default
----    --------   ------------------ -------- -------
autogen 0s         168h0m0s           1        false
30d     720h0m0s   24h0m0s            1        true
90d     2160h0m0s  24h0m0s            1        false
1y      8760h0m0s  168h0m0s           1        false
2y      17520h0m0s 168h0m0s           1        false
```

I have CQ's set up on each database to downsample data into the three non-default RP's:

* Keep per-minute data for 30 days (default RP).
* Roll-up the per-minute data to 5-minute data using `mean()` and store that for 90 days.
* Roll-up the per-minute data to 10-minute data using `mean()` and store that for 1 year.
* Roll-up the per-minute data to 15-minute data using `mean()` and store that for 2 years.

Influx CQ's by default prefix the aggregation function name to the field name when inserting the aggregated data into the RP (ie `ifHCInOctets` becomes `mean_ifHCInOctets` when inserted into the RP), unless you specify the `AS` keyword, in which case it will use whatever you give the `AS` keyword as a prefix. So given the field `ifHCInOctets` (or any other field name used when defining SNMP metrics):

`SELECT mean(*) AS "5m" INTO snmp_brcd."90d"`

will net you `5m_ifHCInOctets` being inserted into the `90d` RP.

This applies when using wildcards. I'm aware that you can get around this by individually listing out each field name with multiple `AS` keywords, but if I'm collecting potentially hundreds of different OIDs across just as many devices, this isn't going to work for creating CQ's. So I have my `AS` prefixes set as the time buckets, eg `5m_`, `10m_`, `15m_`.

Cool, so now I can change the `group_by` time by altering the RP in the Grafana graph via template variable. "But now how can I select the default of `1m` if my default RP field names don't have a prefix?" - I went into the snmpcollector Web UI to change my field names from `$metric` to `1m_$metric` (ie `ifHCInOctets` to `1m_ifHCInOctets`) but quickly ran into a problem with STRINGEVAL metrics (assuming it's because in Go variables can't start with a number, so GoValuate was causing snmpcollector to crash). My STRINGEVAL for `InputUtilization` looked something like:

`( ( 1m_ifHCOutOctets * 8 ) / ( ifHighSpeed * 1000000 ) ) * 100`

Which resulted in

`time="2018-06-07 02:46:59" level=warning msg=" This computed Metric has Variable errors!! please review its definition%!(EXTRA *errors.errorString=Error on Get Variables on Metric InputUtilization ERROR: Cannot transition token types from NUMERIC [1] to VARIABLE [m_ifHCInOctets])"`

My field names aren't Go variables and shouldn't be subject to the same limitations - is there a workaround for this? In other words, can the value assigned to the field name be directly passed to GoValuate instead of being passed to GoValuate as a variable?

**Comment by jensenja** [comment]
I suppose an easy workaround is to just change my field names to something like `x1m_` instead of `1m` etc but I'm curious if this is able to be accounted for in the code as well.

**Comment by jensenja** [comment]
Thanks @sbengo as always - this can be closed out!!!!

**Comment by sbengo** [comment]
Perfect, thanks @jensenja
