### ISSUE TITLE
[Feature Request] Influx Server Buffering

### ISSUE THREAD

**Issue by tardoe** [toni-moreno/snmpcollector#359]
I currently deploy SNMPCollector alongside influxdb-relay(https://github.com/influxdata/influxdb-relay) which allows me to perform hitless upgrades on my InfluxDB instances while metrics are buffered at the collector.

Including this functionality *within* the collector would simplify the deployment and make the collector work much like Telegraf - Influx Data's own collector (not as good).

**Comment by toni-moreno** [comment]
Hi @tardoe , we are already doing buffering but , rith now it is hardcoded.

https://github.com/toni-moreno/snmpcollector/blob/712e21e4400fa59364407fdd5ccca6f9c333e307/pkg/agent/output/influx.go#L195

Add a new config option "buffer size"  in the Influx Server could be easily done into the next release.

**Comment by tardoe** [comment]
Awesome, I did not know this!

It would also be good to expose the buffer statistics via the API as well.
It would be useful to then monitor that endpoint to know when a collector is unable to reach the upstream datastore.

Cheers,

Tim

**Comment by topranks** [comment]
Yeah this works really well, we've had issues with Influx before but thanks to SNMP Collector we lost no data at all!

**Comment by toni-moreno** [comment]
Hi @tardoe @topranks I've finally added new option to set the bufferSize for each output backend.

![issue_359_form](https://user-images.githubusercontent.com/5883405/44252293-fab79a80-a1fb-11e8-8f78-33fa9f04c812.png)

And also added a new output metric  "buffer_percent_used" on the selfmon_outdb_stats measurement to get the state for each buffer.

Thank you for your great idea!
