### ISSUE TITLE
BUG - Go variables not set in build-docker.sh

### ISSUE THREAD

**Issue by mcaulifn** [toni-moreno/snmpcollector#360]
Please prefix your title with [Bug] or [Feature request].

Please include this information:
- What SnmpCollector version are you using? 0.7.7
- What OS are you running snmpcollector on? Ubuntu
- What did you do? run build-docker.sh
- What was the expected result? build container
- What happened instead? script failed do to not having go variables set 

`
nmcauliffe@srv02:~/go/src/github.com/toni-moreno/snmpcollector$ ./docker/build-docker.sh
++ cat package.json
++ grep version
++ awk -F: '{print $2}'
++ tr -d '", '
+ VERSION=0.7.7
++ git rev-parse --short HEAD
+ COMMIT=712e21e
+ '[' '!' -f dist/snmpcollector-0.7.7-712e21e_linux_amd64.tar.gz ']'
…
+ export VERSION
+ export COMMIT
+ cp dist/snmpcollector-0.7.7-712e21e_linux_amd64.tar.gz docker/snmpcollector-last.tar.gz
cp: cannot stat 'dist/snmpcollector-0.7.7-712e21e_linux_amd64.tar.gz': No such file or directory
nmcauliffe@srv02:~/go/src/github.com/toni-moreno/snmpcollector$ cd dist/
nmcauliffe@srv02:~/go/src/github.com/toni-moreno/snmpcollector/dist$ ls
snmpcollector-0.7.7-712e21e_linux_arm.tar.gz  snmpcollector-0.7.7-712e21e_linux_arm.tar.gz.sha1
nmcauliffe@srv02:~/go/src/github.com/toni-moreno/snmpcollector/dist$ echo $GOARCH

nmcauliffe@srv02:~/go/src/github.com/toni-moreno/snmpcollector/dist$
`

**Comment by toni-moreno** [comment]
I can see that GOARH is not set !!

Could you copy and paste the output of this command ?

```bash
# go tool dist env
```

**Comment by mcaulifn** [comment]
```
nmcauliffe@srv02:~$ go tool dist env
CC="gcc"
CC_FOR_TARGET="gcc"
GOROOT="/usr/lib/go-1.6"
GOBIN="/usr/lib/go-1.6/bin"
GOARCH="arm"
GOOS="linux"
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_arm"
GOARM="7"
```
