### ISSUE TITLE
BUG - Directory missing while attempting to build package

### ISSUE THREAD

**Issue by mcaulifn** [toni-moreno/snmpcollector#361]
Please include this information:
- What SnmpCollector version are you using? 0.7.7
- What OS are you running snmpcollector on? Ubuntu
- What did you do? go run build.go build package 
- What was the expected result? Build deb package
- What happened instead?

```cp: cannot stat '/home/nmcauliffe/go/src/github.com/toni-moreno/snmpcollector/public': No such file or directory```

Seems to be from: func createFpmPackage

**Comment by toni-moreno** [comment]
Hi @mcaulifn have you compiled first with the npm command?

The correct sequence to compile and after build all packages is.

``` bash
#> npm run build:prod

#> go run build.go latest
````
latest will build rpm  packages but you will need a lot of pfm dependencies first , be sure you have rpm and dpkg tools.
