### ISSUE TITLE
[Bug] Using Cooked HWADDR causes panic

### ISSUE THREAD

**Issue by cullorblind** [toni-moreno/snmpcollector#362]
- What SnmpCollector version are you using? 0.7.7
- What OS are you running snmpcollector on? Tested on both Docker and CentOS test VMs.
- What did you do?  Set Data Source Type to Cooked HWADDR for an SNMP Metric.
![image](https://user-images.githubusercontent.com/4873651/43219863-1874bdbe-900e-11e8-9081-333a979cc1d6.png)

MIB:
```
mtxrWl60GRemote OBJECT-TYPE
    SYNTAX MacAddress
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION ""
    ::= { mtxrWl60GEntry 5 }
```

```
snmpget -v2c -cpublic 172.16.135.234 .1.3.6.1.4.1.14988.1.1.1.8.1.5.1
With mib: MIKROTIK-MIB::mtxrWl60GRemote.1 = STRING: 30:7:4d:81:d4:9e
Without mib: SNMPv2-SMI::enterprises.14988.1.1.1.8.1.5.1 = Hex-STRING: 30 07 4D 81 D4 9E
```

- What was the expected result?
Metric query should return MAC Address.
- What happened instead?
Crash
- If related with process panics.
  - Include the related log files indicated in the troubleshooting guide.(snmpcollector.log `<deviceid>.log`)

snmpcollector.log is not found in log directory.
This is from journalctl -u snmpcollector
```
Jul 25 12:10:12 snmpcollector1.dc.prwn.net systemd[1]: Starting SnmpCollector Agent...
Jul 25 12:10:13 snmpcollector1.dc.prwn.net snmpcollector[14746]: time="2018-07-25 12:10:13" level=warning msg="No Output default found influxdb devices found !!"
Jul 25 12:10:13 snmpcollector1.dc.prwn.net snmpcollector[14746]: panic: interface conversion: interface {} is string, not []uint8
Jul 25 12:10:13 snmpcollector1.dc.prwn.net snmpcollector[14746]: goroutine 21 [running]:
Jul 25 12:10:13 snmpcollector1.dc.prwn.net systemd[1]: snmpcollector.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 25 12:10:13 snmpcollector1.dc.prwn.net systemd[1]: Unit snmpcollector.service entered failed state.
Jul 25 12:10:13 snmpcollector1.dc.prwn.net systemd[1]: snmpcollector.service failed.
```

**Comment by toni-moreno** [comment]
Hi @cullorblind , thank you to report this bug , we will review ASAP.

Anyway the per device generated log  <deviceid>.log   file will  help us to have more data to debug  this bug. Could you review the contents of this file and attach to this issue?

**Comment by cullorblind** [comment]
Here's the log.   Just as a side note, if I change it to 8 bit/octet string, it pulls data fine, but in the wrong format.
[mikrotik-wAP60G0-norahsln-AP.log](https://github.com/toni-moreno/snmpcollector/files/2233085/mikrotik-wAP60G0-norahsln-AP.log)

**Comment by toni-moreno** [comment]
Hi @cullorblind there is not enough info in this log to understand what is happening in your setup.  

Could you set log level to debug( both at device level and per process in  the config.toml) , and restart again your snmpcollector with this HWADDR  type snmpmetric please? be sure you upload again both files.

Thank you very much !!

**Comment by cullorblind** [comment]
I wiped all previous logs and got fresh logs with debug enabled.

[snmpcollector.log](https://github.com/toni-moreno/snmpcollector/files/2242019/snmpcollector.log)
[mikrotik-wAP60G0-norahsln-AP.log](https://github.com/toni-moreno/snmpcollector/files/2242014/mikrotik-wAP60G0-norahsln-AP.log)

**Comment by toni-moreno** [comment]
Hi @cullorblind  I'm again reviewing your issue, ( sorry for this elapsed time), I will give you some feedback ASAP

**Comment by toni-moreno** [comment]
Hi @cullorblind I'm finally found the issue, next 0.8 released binaries   will have the fix ,  or you can just download and build yourself if you need.

Thank you for reporting this bug and for your patience

**Comment by cullorblind** [comment]
Thank you.. I'll keep an eye out for the update.
