### ISSUE TITLE
question on composite indexes

### ISSUE THREAD

**Issue by jensenja** [toni-moreno/snmpcollector#363]
Not sure if this is related to https://github.com/toni-moreno/snmpcollector/issues/252 or https://github.com/toni-moreno/snmpcollector/issues/324 but I'm attempting to get CPU utilization metrics from some Brocade devices. These OIDs are in a table called snAgentCpuUtilTable and they're indexed like so:

```
snAgentCpuUtilEntry     OBJECT-TYPE
        SYNTAX  SnAgentCpuUtilEntry
        MAX-ACCESS      not-accessible
        STATUS  current
        DESCRIPTION
                "A row in the CPU utilization table."
        INDEX   {
                snAgentCpuUtilSlotNum,
                snAgentCpuUtilCpuId,
                snAgentCpuUtilInterval
        }
        ::= { snAgentCpuUtilTable 1 }
```

My goal here is to only get the 60s values, and `snmpwalk`s only return the OID suffixed with the following:

BaseOID.snAgentCpuUtilSlotNum.snAgentCpuUtilCpuId.snAgentCpuUtilInterval = value

ie:

```
root@6c6b3b66aa1b:~# snmpwalk -On -v2c -c XXXX 10.3.3.53 snAgentCpuUtilPercent 2>/dev/null
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.1.1.1 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.1.1.5 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.1.1.60 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.1.1.300 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.2.1.1 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.2.1.5 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.2.1.60 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.2.1.300 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.15.1.1 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.15.1.5 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.15.1.60 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.15.1.300 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.16.1.1 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.16.1.5 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.16.1.60 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.16.1.300 = Gauge32: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.17.1.1 = Gauge32: 3
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.17.1.5 = Gauge32: 4
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.17.1.60 = Gauge32: 3
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.17.1.300 = Gauge32: 3
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.18.1.1 = Gauge32: 0
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.18.1.5 = Gauge32: 0
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.18.1.60 = Gauge32: 0
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.18.1.300 = Gauge32: 0
```

I can't do an `snmpget` against any of these unless I fully qualify the OID using the slot/cpu/interval:

```
root@6c6b3b66aa1b:~# snmpget -On -v2c -c XXXX 10.3.3.53 snAgentCpuUtilPercent 2>/dev/null
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5 = No Such Instance currently exists at this OID
root@6c6b3b66aa1b:~# snmpget -On -v2c -c XXXX 10.3.3.53 snAgentCpuUtilPercent.1 2>/dev/null
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.1 = No Such Instance currently exists at this OID
root@6c6b3b66aa1b:~# snmpget -On -v2c -c XXXX 10.3.3.53 snAgentCpuUtilPercent.1.1 2>/dev/null
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.1.1 = No Such Instance currently exists at this OID
root@6c6b3b66aa1b:~# snmpget -On -v2c -c XXXX 10.3.3.53 snAgentCpuUtilPercent.1.1.60 2>/dev/null
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.1.1.60 = Gauge32: 1
root@6c6b3b66aa1b:~#
```

I figured out how to create a measurement and apply the IndexTagFormat so that I can do:

    ${IDX1|DOT[0:0]|STRING}

Which gives me the slot number, but this means that `$VAL1` belongs to any combination of CPU ID or utilization interval (1,5,60,300).

Further complicating this is that even if I walk a subset of the index OID values (ie snAgentCpuUtilCpuId), I still get the same suffix returned but the base OID is different:

```
root@6c6b3b66aa1b:~# snmpwalk -On -v2c -c XXXX 10.3.3.53 snAgentCpuUtilCpuId 2>/dev/null
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.1.1.5 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.1.1.60 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.1.1.300 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.2.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.2.1.5 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.2.1.60 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.2.1.300 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.15.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.15.1.5 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.15.1.60 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.15.1.300 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.16.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.16.1.5 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.16.1.60 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.16.1.300 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.17.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.17.1.5 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.17.1.60 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.17.1.300 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.18.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.18.1.5 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.18.1.60 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.18.1.300 = INTEGER: 1
```

How do I make it so that I only get the 60s GAUGE32 value for any given slot for any given CPU ID? Using OID conditions don't really seem to be an option here because of the different base OIDs, unless I'm totally missing something.

**Comment by jensenja** [comment]
Hi @sbengo - thanks for the response as always! Sure, here is the output (the suffixes again are the same):

```
root@eb4468f99611:~# snmpwalk -On -v2c -c XXXX 10.3.3.53 snAgentCpuUtilInterval 2>/dev/null
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.1.1.5 = INTEGER: 5
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.1.1.60 = INTEGER: 60
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.1.1.300 = INTEGER: 300
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.2.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.2.1.5 = INTEGER: 5
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.2.1.60 = INTEGER: 60
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.2.1.300 = INTEGER: 300
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.15.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.15.1.5 = INTEGER: 5
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.15.1.60 = INTEGER: 60
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.15.1.300 = INTEGER: 300
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.16.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.16.1.5 = INTEGER: 5
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.16.1.60 = INTEGER: 60
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.16.1.300 = INTEGER: 300
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.17.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.17.1.5 = INTEGER: 5
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.17.1.60 = INTEGER: 60
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.17.1.300 = INTEGER: 300
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.18.1.1 = INTEGER: 1
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.18.1.5 = INTEGER: 5
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.18.1.60 = INTEGER: 60
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.18.1.300 = INTEGER: 300
```

**Comment by sbengo** [comment]
Thats quite interesting!

Actually I think you can make the following workaround to retrieve the desired metrics using OID Conditions!

As the index composition of `snAgentCpuUtilInterval` seems to be the same as `snAgentCpuUtilPercent`, you can make the following:

**0. Configure your measurement as indexed, with your desired tagFormat and attach your desired metric on it:**
```
ID: snAgentCpuUtilTable
Type: indexed
Index OID: <any of the table entries>
TagFormat <whatever you want to keep>
Fields: snAgentCpuUtilPercent
````

**1. Create a OID condition +  based on numerical equal than the desired interval:**
```
ID: 60intervalCondition
OID - .1.3.6.1.4.1.1991.1.1.2.11.1.1.3 (snAgentCpuUtilInterval)
Condition  neq --> 60 (or desired interval)
```

**2. Create a Measurement filter based on the OID condition to filter only the outputs with the 60 as interval and the related measurement with the metric**
```
Type: OID condition
Filter Name: 60intervalCondition
Measurement: snAgentCpuUtilTable
```

If everything works as expected, the filter would take only the configured interval and will retrieve your value!

Thanks,
Best regards!

**Comment by jensenja** [comment]
Thanks for the suggestion @sbengo !

So the composition for `snAgentCpuUtilInterval` and `snAgentCpuUtilPercent` are slightly different - will the OID condition still work? Below are the OIDs for 60sec on slot 17, CPU ID 1 on 10.3.3.53:

```
.1.3.6.1.4.1.1991.1.1.2.11.1.1.3.17.1.60
                               ^ snAgentCpuUtilInterval
.1.3.6.1.4.1.1991.1.1.2.11.1.1.5.17.1.60
                               ^ snAgentCpuUtilPercent
```

**Comment by sbengo** [comment]
Yes, the index measurement creates a map with the indexes, so the filter will match  the condition based on the same indexes map. The only requirement is that they must share the same index (same SNMP table) and the OID that is set up must be before the index.

As an example:  set up OID condition and indexed measurement with the OID: 
`snAgentCpuUtilInterval- .1.3.6.1.4.1.1991.1.1.2.11.1.1.3`

Could you test it?

Thanks,
Regards!

**Comment by jensenja** [comment]
Hi @sbengo,

I tested against a single device and sure enough it worked. But I'm still confused as to how, since the base OIDs are different. Could you explain how the mapping functionality works in a little more detail? Sorry for all the questions. :-)

**Comment by sbengo** [comment]
Hi @jensenja , I'm glad that you could retrieve your data!

As we have seen, most  of the  SNMP Tables are made,  following your example constructed by 3 different OIDs:

```
.1.3.6.1.4.1.1991.1.1.2.11.1.1.2.1.1.1

TABLE_OID=.1.3.6.1.4.1.1991.1.1.2.11.1.1
METRIC_OID=[1,2,3,4,5]
INDEX= [.1.1.1, .1.1.5, .1.1.60, .1.1.300, 
        .2.1.1., .2.1.5, .2.1.60, .2.1.300, 
        .15.1.1, .15.1.5 ,.15.1.60, .15.1.300
        ... ]
```

When you configure a `indexed measurement` the SNMPCollector is creating a map  with only the index (`INDEX`) part in order to identify all metrics results (`TABLE_OID+METRIC_OID` walk results) that belongs on a single table (`TABLE_OID`). This map allows to create (within `TagFormat`) unique series.

When you configure a `measurement filter with a condition OID` it filters the map created on the `indexed measurement` with only the desired `INDEX`, based on some condition

That's why the `Base OID` can be different but they must belong on the same `SNMP Table`.

Thanks,
Regards!

**Comment by jensenja** [comment]
Thanks @sbengo that clears things up a bit. Closing this. Thanks as always for your help.
