### ISSUE TITLE
[BUG] MULTISTRINGPARSER doesn't convert values to floating point

### ISSUE THREAD

**Issue by jensenja** [toni-moreno/snmpcollector#365]
SNMPCollector version 0.7.7 running in Docker.

I'm attempting to gather optical power level metrics for my devices. The table is `snIfOpticalMonitoringInfoTable`. The indexes are the `ifIndex` values for the interfaces. The data returned by querying the table is usually always `OCTETSTRING` and looks like so:

```
snIfOpticalMonitoringTemperature.1 = STRING: "   29.1484 C: Normal"
snIfOpticalMonitoringTemperature.2 = STRING: "      N/A    "
snIfOpticalMonitoringTemperature.3 = STRING: "      N/A    "
snIfOpticalMonitoringTemperature.4 = STRING: "      N/A    "
```
I've defined an OID condition to inverse match on `N\/A` to filter interfaces that don't have optics inserted. That works fine.

I've defined a `MULTISTRINGPARSER` metric to try to gather data on `snIfOpticalMonitoringTemperature`.

```
ID: iw_snIfOpticalMonitoringTemperature
FieldName: F|snIfOpticalMonitoringTemperature|FP,F|snIfOpticalMonitoringTemperatureStatus|STR
BaseOID: .1.3.6.1.4.1.1991.1.1.3.3.6.1.1
DataSrcType: MULTISTRINGPARSER
ExtraData: ^\s+(\d+\.\d+)\sC\:\s(Normal|Low-Alarm|High-Alarm)
```

The problem is that the Celsius temp values don't appear to get converted to Floating Point. I can see that the regex is matching them in debug logs, but the value that gets sent to the field is always `nil`.

```
time="2018-08-02 23:18:00" level=debug msg="MEASUREMENT [iw_optical_monitoring] generating influx point for indexed 65"
time="2018-08-02 23:18:00" level=debug msg="MEASUREMENT [iw_optical_monitoring] IDX :&{Valid:false Data:map[iw_snIfOpticalMonitoringTemperature:0xc4206aa4b0 ifName:0xc4206aa1e0]}"
time="2018-08-02 23:18:00" level=debug msg="DEBUG METRIC  CONFIG &{ID:ifName FieldName:ifName Description: BaseOID:.1.3.6.1.2.1.31.1.1.1.1 DataSrcType:OCTETSTRING GetRate:false Scale:0 Shift:0 IsTag:true ExtraData: Names:map[]}"
time="2018-08-02 23:18:00" level=debug msg="REPORT is FALSE in METRIC ID [ifName] from MEASUREMENT[ iw_optical_monitoring ] won't be reported to the output backend"
time="2018-08-02 23:18:00" level=debug msg="DEBUG METRIC  CONFIG &{ID:iw_snIfOpticalMonitoringTemperature FieldName:F|snIfOpticalMonitoringTemperature|FP,F|snIfOpticalMonitoringTemperatureStatus|STR Description: BaseOID:.1.3.6.1.4.1.1991.1.1.3.3.6.1.1 DataSrcType:MULTISTRINGPARSER GetRate:false Scale:0 Shift:0 IsTag:false ExtraData:^\s+(\d+\.\d+)\sC\:\s(Normal|Low-Alarm|High-Alarm) Names:map[]}"
time="2018-08-02 23:18:00" level=debug msg="Parsing Metric iw_snIfOpticalMonitoringTemperature MULTISTRING 0 value    33.8554 C: Normal (part 33.8554)"
time="2018-08-02 23:18:00" level=debug msg="Parsing Metric iw_snIfOpticalMonitoringTemperature MULTISTRING 1 value    33.8554 C: Normal (part Normal)"
time="2018-08-02 23:18:00" level=debug msg="MEASUREMENT [iw_optical_monitoring] FIELDS:map[snIfOpticalMonitoringTemperatureStatus:Normal snIfOpticalMonitoringTemperature:<nil>] TAGS:map[city:$REDACTED metro:$REDACTED role:$REDACTED ifIndex:65 device:$REDACTED site:$REDACTED]"
time="2018-08-02 23:18:00" level=debug msg="MEASUREMENT [iw_optical_monitoring] GENERATED INFLUX POINT[optmon] index [65]: optmon,city=$REDACTED,device=$REDACTED,ifIndex=65,metro=$REDACTED,role=$REDACTED,site=$REDACTED snIfOpticalMonitoringTemperature=,snIfOpticalMonitoringTemperatureStatus="Normal" 1533251880002215709"
```

Any idea on what the issue could be?

In addition, the measurement isn't making it into InfluxDB either, and I'm not sure if that's another symptom of this issue or if something else is afoot.

**Comment by toni-moreno** [comment]
Hi @jensenja I'm not sure what happening , your configuration  seems to be  ok. There is any related error or warning message to the main snmpcollector.log ?

**Comment by jensenja** [comment]
Hi @toni-moreno 

My `stdout.log` is empty, and my `stderr.log` is indeed showing that it can't write 3 points to InfluxDB (the `MULTISTRINGPARSER` metric is generating 3 points, so I can only assume it's these 3):

```
time="2018-08-03 11:18:18" level=error msg="ERROR on Write batchPoint in DB snmp-east-brocade (3 points) | elapsed : 26.284032ms | Error: {"error":"unable to parse points"}
 "
```

Also when I go to the single device's runtime view, it's not showing any errors under:

```
OID With Errors
Metric Sent Errors
Measurement Sent Errors
```

I would expect at least one of these to be incrementing based on the output of `stderr.log`.

**Comment by jensenja** [comment]
As a troubleshooting step, I changed the conversion type from `FP` to `INT` and the device log generated these errors:

```
time="2018-08-03 12:44:00" level=warning msg="Error for Metric iw_snIfOpticalMonitoringTemperature MULTISTRINGPARSER  Field [F|snIfOpticalMonitoringTemperature|INT] Coversion  from  [32.7226] error: strconv.ParseInt: parsing "32.7226": invalid syntax"
time="2018-08-03 12:44:00" level=warning msg="Error for Metric iw_snIfOpticalMonitoringTemperature MULTISTRINGPARSER  Field [F|snIfOpticalMonitoringTemperature|INT] Coversion  from  [28.6367] error: strconv.ParseInt: parsing "28.6367": invalid syntax"
time="2018-08-03 12:44:00" level=warning msg="Error for Metric iw_snIfOpticalMonitoringTemperature MULTISTRINGPARSER  Field [F|snIfOpticalMonitoringTemperature|INT] Coversion  from  [33.5117] error: strconv.ParseInt: parsing "33.5117": invalid syntax"
```

**Comment by jensenja** [comment]
Changing the conversion type to STR yields properly formatted metrics (but only of type `STRING`) and the values are sent to InfluxDB:

```
name: optmon
fieldKey                               fieldType
--------                               ---------
snIfOpticalMonitoringTemperature       string
snIfOpticalMonitoringTemperatureStatus string
```

**Comment by toni-moreno** [comment]
I'm reviewing the code and no reason sdem
 , I will  do some tests with the same configuration . ASAP

**Comment by jensenja** [comment]
Hi,

Any luck with reproducing? Is there anything I can do to assist?

**Comment by toni-moreno** [comment]
Hi @jensenja , I'm sorry but I can not reproduce your issue, all is ok for me. Let me show you what I did. And  Please try to do exactly the same with your snmpcollector version to compare results.

 I've configured my snmpd ( in my linux box)  with an extension which returns the exact string you are getting from your device ( as in this link http://net-snmp.sourceforge.net/wiki/index.php/Tut:Extending_snmpd_using_shell_scripts)

``` 
extend a /bin/echo  "   29.1484 C: Normal"
```
after this config change I can get this string with this command

```bash
$ snmpwalk -v2c -c public localhost  nsExtendOutput1
.1.3.6.1.4.1.8072.1.3.2.3.1.1.1.97 = STRING:    29.1484 C: Normal
.1.3.6.1.4.1.8072.1.3.2.3.1.2.1.97 = STRING:    29.1484 C: Normal
.1.3.6.1.4.1.8072.1.3.2.3.1.3.1.97 = INTEGER: 1
.1.3.6.1.4.1.8072.1.3.2.3.1.4.1.97 = INTEGER: 0
````

Then Configured SNMPCollector as you did.

![issue_365_snmpmetric](https://user-images.githubusercontent.com/5883405/44191804-0ab47900-a12d-11e8-811d-6b0eaad65f21.png)

As you can see I've getting the correct values:

![issue_365_result](https://user-images.githubusercontent.com/5883405/44191926-a940da00-a12d-11e8-959a-dac9a301e2b6.png)

Could you do this exact test with your snmpcollector version , please?

**Comment by jensenja** [comment]
Out of curiosity, your snmpwalks against your test agent are showing no double quote characters in the output, while snmpwalks against my devices are. Do you think this could be part of the problem?

**Comment by jensenja** [comment]
@toni-moreno sounds good. I'll see about getting a debugging environment with a custom SNMP agent working today.

**Comment by toni-moreno** [comment]
Hi @jensenja it seems you already fixed this issue. I'm going to Close now. Feel free to reopen it if needed
