### ISSUE TITLE
Unable to build project with build-docker.sh

### ISSUE THREAD

**Issue by RaLazo** [toni-moreno/snmpcollector#367]
## Specs
+ ubuntu 16.04 LTS
+ SnmpCollector 0.7.7

## Question 
We want to build a docker-image by using the script `build-docker.sh`

## What we did

We checkout your project and run `./docker/build-docker.sh`
During the build process a text editor opens:

![snmp_collector build text editor](https://user-images.githubusercontent.com/29118677/44705829-0a5a9d00-aaa0-11e8-8b96-c91c0d1eda6a.png)

Do we have to put any special arguments in this file?

After putting any text in this editor we get this error:

![snmp_collector error](https://user-images.githubusercontent.com/29118677/44705935-54dc1980-aaa0-11e8-9731-749abb00df73.png)

Any help from your side would be great.

**Comment by toni-moreno** [comment]
You should fist build the ptoject as in

https://github.com/toni-moreno/snmpcollector/blob/master/README.md#building-frontend-and-backend-in-production-mode

After you can run the docker script

**Comment by RaLazo** [comment]
Thanks for the quick reply. Now the `build-docker.sh`work as aspected.

**Comment by toni-moreno** [comment]
Ok.
