### ISSUE TITLE
Loading... new install stuck at loading.

### ISSUE THREAD

**Issue by JohnMetalXGit** [toni-moreno/snmpcollector#373]
Installed deb package, successfully installed but I get an error Loading... when opening the default webpage.  

From IE
SCRIPT438: Object doesn't support property or method 'assign'
vendor.7ada1f03640edacd22ec.bundle.js (1,600531)

From Chrome
Uncaught ReferenceError: Map is not defined "from the same file"

Appears to be
e=encodeURIComponent(e)

**Comment by toni-moreno** [comment]
Hi @JohnMetalXGit this sounds really strange. nobody reported before this kind of problem.

Has you tested the rpm or the docker image as well?

I will release a new version soon. When done  I will  test the debian package  contents.

Thank you to report.

**Comment by toni-moreno** [comment]
Hello @JohnMetalXGit please update to the last released version and test again. I'm going to close now. Feel free to reopen it if needed
