### ISSUE TITLE
ability to tune # of GETs in SNMPv1 PDU?

### ISSUE THREAD

**Issue by jensenja** [toni-moreno/snmpcollector#378]
Hi,

I'm running 0.7.6 in Docker. I have some PDI RPP's that only support either SNMPv1 or SNMPv3. There are 168+ OIDs that I need to poll on them, and the MIBs have no tables, only single `INTEGER` scalars. snmpcollector seems to group up single GETs in groups of 60 per PDU, and the SNMP agent on these devices returns TooBig errors in response. Is there a place where one can tune the number of GET's that are sent in a single PDU at the device level?

Thanks!

**Comment by toni-moreno** [comment]
Hi @jensenja did you see this other related issue https://github.com/toni-moreno/snmpcollector/issues/161. ?
Most of toobig errors should be fixed by decreasing the MaxRepetition option.

 You can also change online from the device runtime view to test what value is good for your device.

Let me know if this was also your issue.

**Comment by jensenja** [comment]
Hi,

Since MaxReps is associated with a GetBulk request (and thus not something that’s really applicable to SNMPv1) I wasn’t sure that this was the right parameter to look at. Also the default MaxReps is 50 and in my logs I’m seeing that snmpcollector is attempting 60 GETs at a time. Can you comment on how the MaxReps parameter impacts SNMPv1 and single GETs on scalar INTEGER’s? Thanks.

**Comment by toni-moreno** [comment]
Hi @jensenja you are right snmp v1 doens't use MaxReps and request groups by 60  has to be with this constant..

https://github.com/toni-moreno/snmpcollector/blob/9e2519afbd4cd0d7e2b39145feb97ec8975b4329/pkg/data/snmp/snmp.go#L473-L475

And this is the code where we have the request.

https://github.com/toni-moreno/snmpcollector/blob/9e2519afbd4cd0d7e2b39145feb97ec8975b4329/pkg/data/measurement/measurement.go#L442-L480 

Anyway I don't know why your device is returning this error.

I suggest to open an Issue direct o the [GoSnmp project ]( https://github.com/soniah/gosnmp/issues ). You can also compile your own snmpcollector version with MaxOids with lower number ( perhaps 10 or 5) and test if this solve your issue..

**Comment by jensenja** [comment]
Thanks Toni - I may look into forking the code and customizing that constant. When I reduce the # of metrics in the measurement to 10 it seems fine, so it will take some experimentation on my end to find the max # of GETs that the devices will support.

**Comment by jensenja** [comment]
Feel free to close.

**Comment by toni-moreno** [comment]
@jensenja anyway if this MaxOids change has solved your issue SnmpCollector should have a way to tune this parameter also. 

Please let me know what kind of device are you working on and what number of MaxOid's is working fine. When done we will add new this new feature. 

Thank you to report

**Comment by jensenja** [comment]
Hi @toni-moreno - these are remote power panels made by PDI

https://www.pdicorp.com/products/distribute/remote-power-panels

I'll be experimenting today to determine how many GETs per PDU that these devices support and will report back here. Being able to tune this per SNMP device would be great. Thanks!

**Comment by jensenja** [comment]
So on these devices, 32 metrics in a single measurement seems to trigger the TooBig errors, so 31 metrics per measurement is the max that I can do on these (31 GETs in a single PDU)
