### ISSUE TITLE
[Bug] Conversion metric settings is not working

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#379]
- What SnmpCollector version are you using? 0.8.0
- What OS are you running snmpcollector on? CentOS 7
- What did you do? Tried to change conversion type from INTEGER to FLOAT for one of my metrics
- What was the expected result? Properly saved conversion type
- What happened instead? Change has no effect - it's always stored as INTEGER.

![image](https://user-images.githubusercontent.com/12551929/48274020-ac084e00-e442-11e8-8cbc-25bb7b88a8a7.png)

**Comment by toni-moreno** [comment]
Hi @pavleec  could you attach the device and also generic snmpcollector log files when you did the type conversion change?

**Comment by toni-moreno** [comment]
Hi @pavleec review please your config , if you set data send as tag conversion won't be done , tags are sent always as strings.

**Comment by mastier** [comment]
I noticed something similar. It used to work on the same version of snmpcollector (nothing changed).
I change, submit  and got back still says INTEGER
After the sent change I see that request output is little strange

![screen shot 2018-11-13 at 18 30 46](https://user-images.githubusercontent.com/1609672/48432532-e2acd400-e774-11e8-8f8a-69b826c9f581.png)

**Comment by hyberdk** [comment]
I have the same issue with the latest commit (3c62474). Whenever I change a data field (not tag), to Float, it changes it in the database, but its not reflected in the GUI.. 

Was is already fixed? If so, I think there might still be an issue.

Esben
