### ISSUE TITLE
[Question] scaling values by 0.1

### ISSUE THREAD

**Issue by jensenja** [toni-moreno/snmpcollector#380]
Hi,

This is also related to the PDI remote power panel devices that I'm polling. Due to the limited nature of the MIBs + the SNMP agent on the devices, all values returned are `INTEGER` scalar types. It's up to the client to convert these integer values to decimal/floating point values. I'm accomplishing this by scaling the returned metrics by 0.1 so that, for example, `63` becomes `6.3`.

It would seem that internally when this is done that the precision on certain values is set quite high. For example, some of the values that are being stored in Influx are:

```
> select Panel1CB4Current from cb_current limit 15
name: cb_current
time                Panel1CB4Current
----                ----------------
1541709240000000000 14
1541709300000000000 13
1541709360000000000 14
1541709420000000000 14     <----- stored pre-metric scaling by 0.1
1541709480000000000 1.3
1541709540000000000 1.3
1541709600000000000 1.4000000000000001
1541709660000000000 1.3
1541709720000000000 1.4000000000000001
1541709780000000000 1.4000000000000001
1541709840000000000 1.3
1541709900000000000 1.4000000000000001
1541709960000000000 1.4000000000000001
1541710020000000000 1.4000000000000001
1541710080000000000 1.4000000000000001
```

I'm wondering if this behavior is unavoidable due to the way that Go handles floating point arithmetic (this is just a shot in the dark, as I'm not quite sure) ? Is there a different way to go about scaling integers to try to convert them to floats/decimals that I should try? Thanks.

**Comment by toni-moreno** [comment]
sorry for the big delay @jensenja , just working with unit test I've seen this behaviour but it seems to be related o how floating point operations are done.

This is another example about floating point precision : https://play.golang.org/p/E_VQv8U7ha

Here more about this precision issue on floating point numbers 

* https://floating-point-gui.de
* https://dev.to/juliaferraioli/testing-in-go-testing-floating-point-numbers-4i0a
* https://www.reddit.com/r/golang/comments/5rwywn/float64_precision/
