### ISSUE TITLE
[Feature Request] Option to bind webui to a specific interface (e.g. 127.0.0.1)

### ISSUE THREAD

**Issue by mobitux** [toni-moreno/snmpcollector#387]
It would be nice to add a config option to bind the webui to a specific port (e.g. 127.0.0.1). The goal is to use a reverse proxies with ssl support. Direct access without ssl should not be possible over the network.

**Comment by jensenja** [comment]
While this doesn't directly address the issue, I'll offer up a possible solution (and it's the one that I use in production):

1. Use Docker
2. Create a user-defined network for the snmpcollector container and the database (I use `mysql:5` but you could also get away with doing sqlite in the container itself). This allows for snmpcollector to talk to the database via the user-defined network and doesn't require exposing 3306 to the host machine. It also doesn't require exposing port 8090 to the host machine.
3. Use an `haproxy` container that will use Docker's built-in DNS resolver to resolve container names to internal Docker container IP addresses. You can find an example here: https://github.com/gesellix/docker-haproxy-network
4. Connect the haproxy container to the user-defined network for snmpcollector.
5. Configure your haproxy container to terminate the SSL for the HTTP frontend and pass the HTTP on to the backend, via the user-defined network on port 8090.

**Comment by toni-moreno** [comment]
closed by #440 

from 0.8.1 config option will be "listen"  = ":XXX" // "127.0.0.1:8080" // X.Y.Z.W:8080" better than "port" ( still valid but deprecated)
