### ISSUE TITLE
[Feature request] Add signed integer on convert field

### ISSUE THREAD

**Issue by sbengo** [toni-moreno/snmpcollector#393]
Hi,

Actually the current INTEGER field converts the value into uint64.

As InfluxDB, by default, it is not provided with this option, we should check actual configuration and set up a new SIGNED INTEGER as convert option and rename the currrent to UNSIGNED INTEGER

Thanks,
Regards!

**Comment by toni-moreno** [comment]
Closed after lots of fixes about metric conversion
