### ISSUE TITLE
Only 1 measurement filter being applied to device at runtime

### ISSUE THREAD

**Issue by adrianalcalde** [toni-moreno/snmpcollector#396]
Only a single measurement filter is being applied to a device, even though multiple are applied to SNMP device.  

Thanks

**Comment by adrianalcalde** [comment]
Usually it's only the first in the MeasFilters array:

 {
  "ID": "<device name>",
  "Host": "10.23.86.49",
  "Port": 161,
  "SystemOIDs": null,
  "Retries": 5,
  "Timeout": 20,
  "Repeat": 0,
  "Active": true,
  "SnmpVersion": "2c",
  "Community": "<snmp community string>",
  "V3SecLevel": "",
  "V3AuthUser": "",
  "V3AuthPass": "",
  "V3AuthProt": "",
  "V3PrivPass": "",
  "V3PrivProt": "",
  "V3ContextEngineID": "",
  "V3ContextName": "",
  "DisableBulk": false,
  "MaxRepetitions": 50,
  "Freq": 300,
  "UpdateFltFreq": 12,
  "ConcurrentGather": true,
  "OutDB": "influxdb_local",
  "LogLevel": "info",
  "LogFile": "",
  "SnmpDebug": false,
  "DeviceTagName": "device",
  "DeviceTagValue": "id",
  "ExtraTags": [
    "system_address=192.168.162.179",
    "mgmt_ip=10.23.86.49"
  ],
  "DeviceVars": null,
  "Description": "",
  "MeasurementGroups": [
    "Device Interfaces"
  ],
  "MeasFilters": [
    "tmnxPortMode_measurement_filter_2",
    "tmnxPortMode_measurement_filter_3",
    "ifType=6_filter",
    "ifType=161_filter",
    "ifName!=A",
    "ifName!=B"
  ]
}

**Comment by sbengo** [comment]
Hi @adrianalcalde , thanks for submitting this!

As you have seen, when you create a `Measurement Filter`, you have to relate it to a `Measurement`.
It allows to set up Devices with different filters but it is expected to be `1 MF by 1 Measurement`.

As I can see in in your device definition and to exemplify it you want to filter all interfaces that are equal than `6` and `161`; this can be achieved using multiple `OID Conditions` and defining a single `Measurement Filter`, you can find an example of how create multiple `OID Conditions` [HERE](https://github.com/toni-moreno/snmpcollector/wiki/Component:-OID-Conditions#a-creating-new-multiple-oid-condition)

Let us know if you have any trouble!

Thanks,
Greetings!!

**Comment by adrianalcalde** [comment]
Hi @sbengo , thanks for the answer, worked perfect.  This is my multifilter:
(tmnxPortMode_condition_2 || tmnxPortMode_condition_3) && (ifType_6 || ifType_161) && ifName_not_A && ifName_not_B
Had to rename a few of the filters, it did not like the '=' in the oid condition names.
