### ISSUE TITLE
[Feature Request] Override snmp collection frequency in "Influx Measurements"

### ISSUE THREAD

**Issue by hyberdk** [toni-moreno/snmpcollector#404]
Its great that you can select the snmp collection frequency per device, but sometime you want to collect different metrics on the same device with different frequency.

An example for me is that I would like to collect interface statistics every 60sec, but some of the switches also have IPSLA enabled. These are only updated every 5mins (in my environment), this means that I collect 5 identical samples which is a waste of resources primarily on the switch

What I would like is to override the collection frequency in the "Influx Measurements" section where I build the groups of OIDs I want to collect.

This would mean that I can collect different metrics from the same device at different intervals.

Let me know what you think and if it makes sense.

Esben

**Comment by CommanderKagome** [comment]
I have a similar case on a NAS system.
Some Storageinformations are updated only every minute - some are updated in realtime.
Is it possible to add the device twice with different frequency?

**Comment by toni-moreno** [comment]
Resolved on #509
