### ISSUE TITLE
[Feature Request] Suppress newline in snmp data.

### ISSUE THREAD

**Issue by hyberdk** [toni-moreno/snmpcollector#405]
When SNMP data returns values that contains newlines, it somehow screws up inserting it into the influxdb.

If Influxdb does not support strings that contains "\r\n", snmpcollector should suppress/remove it.

For reference see:  #400 time and tags not inserted into Influxdb.

**Comment by toni-moreno** [comment]
Hello @hyberdk , beginning working on this issue with @sbengo and myself designing a new feature on the "OCTECSTRING" datasource type collected data.

We would like to add new parameter on "Extradata" field for the OCTECSTRING

![image](https://user-images.githubusercontent.com/5883405/95964381-08333400-0e09-11eb-9569-17287f654f1e.png)

Where we can add any of this 4 "trimming" options.

* trimright('xyz'): removes trailing characters defined by 'xyz' 
* trimleft('xyz'): removes leading characters defined by 'xyz'
* trim('xyz'): removes trailing and leading characters defined by 'xyz'
* trimspace : remove all leading and  trailing tabs, whitespaces, newlines and return carriage this is (\t \n\r)

Hope this  new feature could solve your needs.
