### ISSUE TITLE
[QUESTION] Using MULTISTRINGPARSER

### ISSUE THREAD

**Issue by hoosee** [toni-moreno/snmpcollector#417]
I have an OID index which I can use to query device name. For measurements I have base-OID but it does not fully match with the index but it's the <DEVICE_OID> . <RADIO_INDEX> so I presume I have to use MULTISTRINGPARSE-type to capture the DEVICE_OID so I can match that with the index and then capture <RADIO_INDEX> part and post that as a TAG.

Wiki tells that I have configure FieldName- and ExtraData-fields but when I change the metric type to MULTISTRINGPARSE, only ExtraData -field is visible. Am I missing something?

![Capture](https://user-images.githubusercontent.com/37834057/69726999-532d5580-112a-11ea-9011-940b796ae496.PNG)

I'm using 0.8.0

**Comment by toni-moreno** [comment]
Hello @hoosee , sorry for the big delay , as you can see in your own screenshot , when MULTI-STRINGPARSER Selected on the DataSrcType , both "extradata" and "FieldName is shown in your UI. you can follow then the wiki instructions as well.
Closing this issue, and feel free to reopen it if needed.
