### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by robitmoh** [toni-moreno/snmpcollector#421]
Hi
I want to get cable modem data from arris cmts
docsIf3CmtsCmUsStatusSignalNoise.188.721433 = INTEGER: 37.6 TenthdB
The oids
.1.3.6.1.4.1.4491.2.1.20.1.4.1.4.188.721433 = INTEGER: 35.4 TenthdB
.1.3.6.1.4.1.4491.2.1.20.1.4.1.4.188.721441 = INTEGER: 33.3 TenthdB
.1.3.6.1.4.1.4491.2.1.20.1.4.1.4.188.721449 = INTEGER: 35.5 TenthdB
_Split the oid_
SignalNoise Oid   .1.3.6.1.4.1.4491.2.1.20.1.4.1.4.
Cablemodem ID:  188.
Cablemodem Interface ID: 721457 
Value: = INTEGER: 32.9 TenthdB

The cablemodem id is always change when the modem is reboot.

I made snmpmetric from this oid (.1.3.6.1.4.1.4491.2.1.20.1.4.1.4.)
And 
One Influx measurment from this oid and the prev snmpmetric. the IndexTag is a Cablemodem ID (188)
But this not usable 
I need the following format:
SignalNoise Oid   .1.3.6.1.4.1.4491.2.1.20.1.4.1.4.
Cablemodem ID:  188.    --> TAG
Cablemodem Interface ID: 721457  ---> TAG
Value: = INTEGER: 32.9 TenthdB ---> Field

I see the MULTISTRINGPARSER but (If I correct understand) this only split the values

**Comment by wurmrobert** [comment]
I have implemented that feature as discussed in #324, and we are monitoring many CMTS  and CPEs with that functionality.
But until yet i didn't had time to create a pull request.

**Comment by sbengo** [comment]
Hi guys, thanks for submitting this!

@robitmoh I will try to review the issue, but if its the same case, @wurmrobert , any chance to see a PR or your code in a fork?

Thanks,
Regards!

**Comment by robitmoh** [comment]
Hi guys,
Wurmrobert that's great news
I hope you can take a time to create pull request.
Or you can publish the source tree? (I not found in forks)

Thanks
Robit

**Comment by toni-moreno** [comment]
@robitmoh please could you send us a simulation snapshot ?.

You could do it by following the next commands.

```
# git clone https://github.com/etingof/snmpsim.git`
# cd snmpsim
# sudo python3 setup.py install
# mkdir sim_data
# snmpsim-record-commands --protocol-version 2c --community <your_comunity> --agent-udpv4-endpoint=<your_cisco_with_qos_device>:161 --output-file=./sim_data/cisco_class_based_qos_data
# tar zcvf sim_data_<DATE>.tar.gz sim_data

**Comment by sbengo** [comment]
As you have seen @robitmoh , you can use MultiIndex Measurement to retrieve those tags
Closing this since the case is discussed on #466 . If you have some doubts, please, keep discussing on the other issue
