### ISSUE TITLE
[Bug] - Docker Problem with Volumes

### ISSUE THREAD

**Issue by MisterBaz** [toni-moreno/snmpcollector#425]
Please include this information:
- **What SnmpCollector version are you using?** - latest from Docker Hub.
- **What OS are you running snmpcollector on?** - Docker on Ubuntu 18.04
- **What did you do?** - Running Docker-compose with mapping /snmp_data/:/opt/snmpcollector/.  I copied the config.toml to snmp_data/conf/ and cofigured it appropriately.
- **What was the expected result?**  SNMPCollector loads correctly.
- **What happened instead?**  SNMPCollector would not load.  Error was it couldn't find ./bin/snmpcollector from the start.sh.
I then created the bin directory (snmp_data/bin/) and copied over the snmpcollector file.  Container runs, but it doesn't generate all of the necessary log files or web files for the public directory.  SNMPCollector WILL run if I don't declare any persistent volumes.  That being said, I would really like to have all of my settings and SNMP mappings, database mappings, all saved.

**Comment by deejaypro** [comment]
Hey,
you need to mount each folder to the docker individually.
Example:
```
docker run -d -p 8090:8090 --name snmpcollector \
-v /opt/snmpcollector/:/opt/snmpcollector/ \
-v /opt/snmpcollector/bin/:/opt/snmpcollector/bin \
-v /opt/snmpcollector/conf/:/opt/snmpcollector/conf \
-v /opt/snmpcollector/log/:/opt/snmpcollector/log \
-v /opt/snmpcollector/public/:/opt/snmpcollector/public \
tonimoreno/snmpcollector
```

**Comment by MisterBaz** [comment]
I did exactly as suggested.  I'm using docker-compose, so it is quite easy to implement the changes.
Even after restarting from a blank slate, I'm getting "/start.sh: line 2: ./bin/snmpcollector: not found" in  /opt/snmpcollector/log/stderr.log
I copied the example config.toml file and edited it appropriately and placed it in the /opt/snmpcollector/config/ directory.  
Is there another file or script I need to run before firing off docker for the first time?

**Comment by deejaypro** [comment]
Okay i see.
The first thing i did was to run it without any volumes.
Then i copied the folder /opt/snmpcollector from the running to my host system with:
`docker cp snmpcollector:/opt/snmpcollector/ /opt/snmpcollector/`

Then i ran the docker container again with the volumes attached.

**Comment by MisterBaz** [comment]
Did exactly as you suggested.  Works great!  Could you update the docker hub page with these docker instructions, please?  Thanks!

**Comment by deejaypro** [comment]
You're welcome :)
Unfortunately i'm not the owner of the docker hub page. I'm just someone who needed this aswell.

**Comment by MisterBaz** [comment]
> You're welcome :)
> Unfortunately i'm not the owner of the docker hub page. I'm just someone who needed this aswell.

Ah, gotcha!  Thanks anyway!

**Comment by toni-moreno** [comment]
Hello @MisterBaz  I will update in a few days a new release with improved  docker image and features that could help you to play with snmpcollector

**Comment by MisterBaz** [comment]
> 
> 
> Hello @MisterBaz I will update in a few days a new release with improved docker image and features that could help you to play with snmpcollector

That sounds fantastic.  Thanks for the update!

**Comment by toni-moreno** [comment]
@MisterBaz I will close this issue , reopen it if needed
