### ISSUE TITLE
[Bug] Tags not being added to a measurement

### ISSUE THREAD

**Issue by gavmckee80** [toni-moreno/snmpcollector#427]
Please prefix your title with [Bug] or [Feature request].

Please include this information:
- What SnmpCollector version are you using?
`
snmpcollector v0.8.0 (git: 9e2519a ) built at [2018-11-04 23:11:36]
`
- What OS are you running snmpcollector on?
Ubuntu Linux 18.04 LTS

- What did you do?
I added SNMP metrics as tag values.
![image](https://user-images.githubusercontent.com/17826993/77360574-d5a9d880-6d0a-11ea-844c-ade3315fb76d.png)

- What was the expected result?
I would have expected these TAG fields to be output as tags for a given measurement.
![image](https://user-images.githubusercontent.com/17826993/77360801-43560480-6d0b-11ea-9c50-9b1b8e912bc7.png)

- What happened instead?
The tags are not being added.
```
> show tag keys
name: interface_counters
tagKey
------
hostname
ifName
serial
type

```

**Comment by gavmckee80** [comment]
Uploading a debug file
[900mtv-corp-fw-01a-debug.log.zip](https://github.com/toni-moreno/snmpcollector/files/4371816/900mtv-corp-fw-01a-debug.log.zip)

**Comment by sbengo** [comment]
HI @gavmckee80 , sorry for the late answer.

First of all, thanks for the detailed issue

As I could see on provided logs, there are some errors related with metric type on `IfIndex` and `IfOperStatus` when the tag is being set on measurement.

When a metric is set as `IsTag = true` we force the metric conversion to string, as it is expected by tag definition.

We will try to repro the case and will see why seems the metric is not being converted to string type

```
time="2020-03-23 13:38:40" level=debug msg="ERROR wrong type int64 for ID [ifOperStatus] from MEASUREMENT[ ifMIB ] won't be reported to the output backend" 
...
time="2020-03-23 13:38:40" level=debug msg="ERROR wrong type int64 for ID [ifIndex] from MEASUREMENT[ ifMIB ] won't be reported to the output backend" 
```

Thanks,
Regards!

**Comment by gavmckee80** [comment]
@sbengo , thanks for picking up and looking at the issue.
