### ISSUE TITLE
custom tags

### ISSUE THREAD

**Issue by jjess** [toni-moreno/snmpcollector#428]
Hi:

Is it possible to define custom tags for every metric in influxdb as telegraf is able to with:

[[inputs.snmp]]
  agents = [ "x.x.x.x"  ]
  version = 2
  community = "whatever"
  # interval in seconds
  interval = "600s"
  timeout = "10s"
  retries = 3

  [inputs.snmp.tags]
    mycustomtag = "my_custom_value"

The purpose of this is to be able to build dynamic dashboards in Grafana because we can group by or filter by this tag.

Thanks in advance,

Jes

**Comment by sbengo** [comment]
Hi @jjess 

When you define a `SNMP Device` there is a field called `Extra Tags`
You can set there all desired tags and all metrics gathered on this device will inherit all those tags (+ the device ID or host)

Example:

```
Device ID: mydevice
Extra Tags: group=lan,location=home
```

Setting up custom tags only on wanted metrics can be achieved:

1. Configure a new variable catalog as STRING (this will be your desired tag value).
The variable catalog value are inherit by *all* devices and can be used on measurements and metrics. **On each device config, the value can be override**

![image](https://user-images.githubusercontent.com/13196237/78127287-265cb800-7414-11ea-90a2-b884f872bc9f.png)

2. Configure new metric of type STRINGEVAL and name it as your desired tagKey
As var catalog are available on metrics, we can refer it on STRINGEVAL metric. Remember that on ExtraData expression, we can play with other metrics

![image](https://user-images.githubusercontent.com/13196237/78127500-8fdcc680-7414-11ea-88c1-a8c66127a6da.png)

3. Add this new metric on your desired measurement, and all metrics will inherit this new tag, as it is sent on the same time:

![image](https://user-images.githubusercontent.com/13196237/78127541-a1be6980-7414-11ea-808c-2546285e49b3.png)

4. Reload config and check runtime

The new tag will appear only on the metrics on previous measurement
![image](https://user-images.githubusercontent.com/13196237/78127644-d4686200-7414-11ea-89c4-d476164a7c82.png)

**Comment by jjess** [comment]
Perfectly clear. Thank you very much.
