### ISSUE TITLE
"No measurements associated with the device. Couldn't retrieve metric runtime info" - IOS-XR/Ubuntu 19.10

### ISSUE THREAD

**Issue by brunoonovais** [toni-moreno/snmpcollector#429]
Hi Toni

I've been setting up snmpcollector on ubuntu 19.10 and following the following example:

https://github.com/toni-moreno/snmpcollector/wiki/Example:-Configuring-Cisco-Catalyst-Switch

I only setup the CPU data for now, but for some reason while manual polling works, config-based polling with same settings as the example are not producing any results so the influxdb doesn't have the measurements.
I can't tell if the snmpcollector is getting the data or not based on the logs, but manual polling via the snmpcollector itself works fine.

Here's a set of 3 attempts:

time="2020-04-14 17:31:00" level=info msg="First SNMP connection to host  10.8.70.3 stablished with MaxRepetitions set to 50" 
time="2020-04-14 17:31:00" level=info msg="Got basic system info snmp.SysInfo{SysDescr:"Cisco IOS XR Software (NCS-5500), Version 6.6.3  Copyright (c) 2013-2019 by Cisco Systems, Inc.", SysUptime:2043000000000, SysContact:"", SysName:"II11-5502SE-Arya", SysLocation:""} " 
time="2020-04-14 17:31:00" level=info msg="SNMPDEVICE [arya] SNMP connection stablished Successfully for device  and measurement init" 
time="2020-04-14 17:31:00" level=info msg="SNMPDEVICE [arya] snmp INIT runtime measurements/filters took [5.531µs] " 
time="2020-04-14 17:31:00" level=info msg="Waiting 59.996655519s to round until nearest interval... (Cycle = 60 seconds)" 
time="2020-04-14 17:32:00" level=info msg="SNMPDEVICE [arya] Init gather cycle mode Concurrent [ true ]" 
time="2020-04-14 17:32:00" level=info msg="STATS SNMP GET: snmp polling took [0.000001 seconds] SNMP: Gets [0] , Processed [0], Errors [0]" 
time="2020-04-14 17:32:00" level=info msg="STATS SNMP FILTER: filter polling took [0.000000 seconds] " 
time="2020-04-14 17:32:00" level=info msg="STATS INFLUX: influx send took [0.000000 seconds]" 
time="2020-04-14 17:33:00" level=info msg="SNMPDEVICE [arya] Releasing snmp connection for init" 
time="2020-04-14 17:33:00" level=info msg="SNMPDEVICE [arya] Beginning SNMP connection for measurement init" 
time="2020-04-14 17:33:00" level=info msg="First SNMP connection to host  10.8.70.3 stablished with MaxRepetitions set to 50" 
time="2020-04-14 17:33:00" level=info msg="Got basic system info snmp.SysInfo{SysDescr:"Cisco IOS XR Software (NCS-5500), Version 6.6.3  Copyright (c) 2013-2019 by Cisco Systems, Inc.", SysUptime:2163000000000, SysContact:"", SysName:"II11-5502SE-Arya", SysLocation:""} " 
time="2020-04-14 17:33:00" level=info msg="SNMPDEVICE [arya] SNMP connection stablished Successfully for device  and measurement init" 
time="2020-04-14 17:33:00" level=info msg="SNMPDEVICE [arya] snmp INIT runtime measurements/filters took [4.786µs] " 
time="2020-04-14 17:33:00" level=info msg="Waiting 59.994698014s to round until nearest interval... (Cycle = 60 seconds)" 

This is running snmpv2c, rudimentary config on ios-xr router. 
Debug on the router displays the following:

RP/0/RP0/CPU0:Apr 14 14:55:45.371 EDT: snmpd[1002]: t8089 snmp_queue_request_for_processing: NMS = 10.8.137.9 found in DB
RP/0/RP0/CPU0:Apr 14 14:55:45.371 EDT: snmpd[1002]: t8426  Time Insert 6651 sec, 197255873 nsec, Cur 6651 Sec 197338673 nsec, Delta 0 Sec 82800 nsec
RP/0/RP0/CPU0:Apr 14 14:55:45.371 EDT: snmpd[1002]: t8426 Processing PDU from 10.8.137.9-22746 req_id = 2985922060, 0 ms_on_q, type 160, cur_time 0
RP/0/RP0/CPU0:Apr 14 14:55:45.371 EDT: snmpd[1002]: t8426 snmp_engine: Invoking SR agent for request# 2985922060
RP/0/RP0/CPU0:Apr 14 14:55:45.371 EDT: snmpd[1002]: t8426 get_free_pending_reqQ_elem: free slot found in 0 iteration
RP/0/RP0/CPU0:Apr 14 14:55:45.371 EDT: snmpd[1002]: t8426 DO-GET: NEW REQ: Type:160 req_id: -1309045236 nvbs:5limit:1464 N:5 M:0 R:0
RP/0/RP0/CPU0:Apr 14 14:55:45.371 EDT: snmpd[1002]: t8426 DO-GET: v1_failed_pos: 4 
RP/0/RP0/CPU0:Apr 14 14:55:45.371 EDT: snmpd[1002]: t8426 DO-GET: [0] OID:1.3.6.1.2.1.1.1.0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-OID: sr_map_index:157 pos:0 repeat:1
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-OID: Q oid: cli:0x200 oid:1.3.6.1.2.1.1.1.0 map_index:157 next_bound:163
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 DO-GET: [1] OID:1.3.6.1.2.1.1.3.0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-OID: sr_map_index:159 pos:1 repeat:1
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-OID: Q oid: cli:0x200 oid:1.3.6.1.2.1.1.3.0 map_index:159 next_bound:163
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 DO-GET: [2] OID:1.3.6.1.2.1.1.4.0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-OID: sr_map_index:160 pos:2 repeat:1
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-OID: Q oid: cli:0x200 oid:1.3.6.1.2.1.1.4.0 map_index:160 next_bound:163
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 DO-GET: [3] OID:1.3.6.1.2.1.1.5.0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-OID: sr_map_index:161 pos:3 repeat:1
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-OID: Q oid: cli:0x200 oid:1.3.6.1.2.1.1.5.0 map_index:161 next_bound:163
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 DO-GET: [4] OID:1.3.6.1.2.1.1.6.0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-OID: sr_map_index:162 pos:4 repeat:1
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-OID: Q oid: cli:0x200 oid:1.3.6.1.2.1.1.6.0 map_index:162 next_bound:163
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 snmp_oidreq_process_req_async: Start processing request serial number# 20177, reqid# 2985922060
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 snmp_oidreq_process_get_req_async: Get: client_id:0x200 noids:5
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 OIDREQ-DISPATCH_ASYNC: Dispatching request with serial number# 20177 reqid# 2985922060
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 snmp_oidreq_process_get_resp_async: Processing response for serial number 20177, clientid 0x200.
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-PROC-RESP: client_id:0x200 noids:5 repeats:5
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-RESP: pos:0 nvbs:1 first:1.3.6.1.2.1.1.1.0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-RESP: pos:1 nvbs:1 first:1.3.6.1.2.1.1.3.0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-RESP: pos:2 nvbs:1 first:1.3.6.1.2.1.1.4.0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-RESP: pos:3 nvbs:1 first:1.3.6.1.2.1.1.5.0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-ADD-RESP: pos:4 nvbs:1 first:1.3.6.1.2.1.1.6.0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-PROC-RESP: end-of-resp. nvbinfo:5
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-PROC-RESP: total_repeats:0 size:194 limit:1464
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 snmp_oidreq_process_get_resp_async: Response complete for reqid# 20177
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-SORT-RESP: Rearranging resp for 5 oids
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 GET-SORT-RESP: Total nvbs in resp:5. rc:0x0
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 free_oidreq_handle_internals. Clearing pending mibmgr: client_id:0x200
RP/0/RP0/CPU0:Apr 14 14:55:45.372 EDT: snmpd[1002]: t8426 OIDREQ-DISPATCH_ASYNC: Dispatch done for serail number# 0, reqid# 2985922060, clientid# 0xfb165ca6

I captured the snmp packets on the server and I only see the snmpcollector sending getrequest to:

1.3.6.1.2.1.1.1.0
1.3.6.1.2.1.1.3.0
1.3.6.1.2.1.1.4.0
1.3.6.1.2.1.1.5.0
1.3.6.1.2.1.1.6.0

So we don't seem to be requesting anything else but sys stuff.
Did I miss something basic? I can show any extra info you need.

Thanks
Bruno Novais

**Comment by brunoonovais** [comment]
![image](https://user-images.githubusercontent.com/42840196/79269052-d21cf380-7e69-11ea-980c-4545fc099dcf.png)

capture above.
below the json for the device and measurements:

 {
  "ID": "arya",
  "Host": "10.8.70.3",
  "Port": 161,
  "SystemOIDs": [
    ""
  ],
  "Retries": 5,
  "Timeout": 20,
  "Repeat": 0,
  "Active": true,
  "SnmpVersion": "2c",
  "Community": "public",
  "V3SecLevel": "",
  "V3AuthUser": "",
  "V3AuthPass": "",
  "V3AuthProt": "",
  "V3PrivPass": "",
  "V3PrivProt": "",
  "V3ContextEngineID": "",
  "V3ContextName": "",
  "DisableBulk": true,
  "MaxRepetitions": 50,
  "Freq": 60,
  "UpdateFltFreq": 60,
  "ConcurrentGather": true,
  "OutDB": "cvt-snmp-server-2",
  "LogLevel": "info",
  "LogFile": "",
  "SnmpDebug": false,
  "DeviceTagName": "router",
  "DeviceTagValue": "id",
  "ExtraTags": [
    ""
  ],
  "DeviceVars": null,
  "Description": "arya",
  "MeasurementGroups": [
    "basic_measurement_group"
  ],
  "MeasFilters": null,
  "IsRuntime": true
} 


 {
  "ID": "ciscoprocessmib",
  "Name": "ciscoprocessmib",
  "GetMode": "indexed_it",
  "IndexOID": ".1.3.6.1.4.1.9.9.109.1.1.1.1.2",
  "TagOID": ".1.3.6.1.2.1.47.1.1.1.1.7",
  "IndexTag": "physIndex",
  "IndexTagFormat": "$VAL2-$IDX1",
  "IndexAsValue": false,
  "Fields": [
    {
      "ID": "cpmCPUTotal1minRev",
      "Report": 1
    }
  ],
  "Description": ""
} 


 {
  "conversion": 1,
  "ID": "cpmCPUTotal1minRev",
  "FieldName": "cpuUsed",
  "Description": "cpmCPUTotal1minRev",
  "BaseOID": ".1.3.6.1.4.1.9.9.109.1.1.1.1.7",
  "DataSrcType": "Gauge32",
  "GetRate": false,
  "Scale": 0,
  "Shift": 0,
  "IsTag": false,
  "ExtraData": "",
  "Conversion": 1
} 

 {
  "ID": "basic_measurement_group",
  "Measurements": [
    "ciscoprocessmib"
  ],
  "Description": "basic measurement group"
} 

 {
  "ID": "cvt-snmp-server-2",
  "Host": "127.0.0.1",
  "Port": 8086,
  "DB": "SNMP",
  "User": "lab",
  "Password": "<hidden>",
  "Retention": "autogen",
  "Precision": "s",
  "Timeout": 30,
  "UserAgent": "snmpcollector",
  "EnableSSL": false,
  "SSLCA": "",
  "SSLCert": "",
  "SSLKey": "",
  "InsecureSkipVerify": true,
  "BufferSize": 65535,
  "Description": ""
}

**Comment by sbengo** [comment]
Hi @brunoonovais , thanks for submitting this.

Seems that, in some way, config is not loaded on runtime

In order to review it deeply:

- Did you `Reload Config` after setting up the metric/meas/measgroup/device?
- Can you attach an image from `Runtime`?

Thanks,
Regards!

**Comment by brunoonovais** [comment]
sometimes it just takes an expert to know the screw haha i did a reload
config and it is working now :) i didn't know i had to reload the config
after the changes.

thanks. Toni!!

**Comment by toni-moreno** [comment]
Tranks @sbengo  ( Sergio !! ) 😉

**Comment by sbengo** [comment]
Great @brunoonovais ! Closing this issue, feel free to reopen if needed

Thanks,
Regards!
