### ISSUE TITLE
[Bug] Cannot use an OID as a conditon value for an OID condition

### ISSUE THREAD

**Issue by mcassaniti** [toni-moreno/snmpcollector#433]
Please include this information:
- What SnmpCollector version are you using: 0.8.0-9e2519a
- What OS are you running snmpcollector on: Docker image
- What did you do: Created an OID condition as follows:
    - ID: HR Fixed Disk
    - Is Multiple: False
    - OID: .1.3.6.1.2.1.25.2.3.1.2
    - CondType: (match)
    - CondValue: .1.3.6.1.2.1.25.2.1.4

- What was the expected result: The filter would match and some values would pass through
- What happened instead: No values for the associated measurement. I do still get values for other measurements, so I know everything else is working.

**Comment by mcassaniti** [comment]
The issue seems to be [here](https://github.com/toni-moreno/snmpcollector/blob/6e0a8a9d42d94bd19d92a9a813f9975412fa4f44/pkg/data/filter/oidfilter.go#L91)

```go
case of.TypeCond == "match":
	//m.log.Debugf("PDU: %+v", pdu)
	str := snmp.PduVal2str(pdu)
	re, err := regexp.Compile(of.ValueCond)
```

This should probably be `snmp.PduVal2Cooked(pdu)` rather than `snmp.PduVal2str(pdu)`. It will also affect the `notmatch` case above it. I'm willing to test it and see what comes out, but I also wanted to get some feedback first.

**Comment by sbengo** [comment]
Hi @mcassaniti , thanks for submitting this.

First of all, as you said, `OID Conditions` are used to filter based on returned values from `OID` so I will not consider this issue as a bug

`OID Condtions` are based on filtering `OIDs` that matches (or not) with defined conditions, based on values.
When retrieving data from measurement, the `OIDs` that matches with conditions are filtered (or not), so: the `OID Conditions` must be based on the same table (`OID`) that is used on `Measurements`

I would like to figure if we can solve this in some way, so, can you provide us the following info:
- What is your usecase?
- What values do you want to filter?

Thanks,
Regards!

**Comment by mcassaniti** [comment]
My devices support the HOST-RESOURCES MIB. I'm filtering the [hrStorageTable](http://www.net-snmp.org/docs/mibs/host.html#hrStorageTable) on the hrStorageType OID. The output of this OID is another OID rather than an enum or a string. Correct values are in [RFC2790](https://tools.ietf.org/html/rfc2790#page-36). This matches the details above for the OID conditions I listed.

Just so I'm as clear as I can possibly be, if I do an SNMP walk on `1.3.6.1.2.1.25.2.3.1.2` I will get back something like `.1.3.6.1.2.1.25.2.1.4` which is an OID. I won't get back `hrStorageFixedDisk` or `4`. Those would've been nicer to work with. I'm after some way to check that the string equivalent of the returned OID matches what I expect.

I also very much appreciate your software. It is the go to package for SNMP monitoring when using InfluxDB. I've naturally got some corner cases that won't make it a perfect fit, but I'm keen to see how many fit perfectly the first time, because I don't think there will be many that I can't get working properly.

**Comment by sbengo** [comment]
Oh! I see @mcassaniti , sorry for missunderestanding, I thought you wanted to filter an specific OID from OIDs retrieved from a Measurement walk.

As you can see, it is trying to compile a regex, so, I not entirely sure, but I think you need to scape those `dots .`

Can you try the following expression:
```
CondValue: "\.1\.3\.6\.1\.2\.1\.25\.2\.1\.4"
```

Thanks,
Regards!

**Comment by mcassaniti** [comment]
I did try that one too, but thanks for the feedback. I also enabled debugging and found something interesting in the logs.

```
time="2020-05-26 22:55:00" level=debug msg="OIDFILTER [.1.3.6.1.2.1.25.2.3.1.2] received SNMP  pdu:{Name:.1.3.6.1.2.1.25.2.3.1.2.1010 Type:6 Value:.1.3.6.1.2.1.25.2.1.1 Logger:0xc000298690}"
time="2020-05-26 22:55:00" level=debug msg="OIDFILTER [.1.3.6.1.2.1.25.2.3.1.2] Evaluated match condition  value:  | filter: .1.3.6.1.2.1.25.2.1.4 | result : false"
```

It's this piece from the log that is the problem: `Evaluated match condition  value:  |`. That is in `pkg/data/filter/oidfilter.go` just after the `case of.TypeCond == "match":` statement. If I'm reading it correctly, the returned value is coming back empty after the `snmp.PduVal2str(pdu)` conversion. This is why I asked if `snmp.PduVal2Cooked(pdu)` might be a better choice.

**Comment by sbengo** [comment]
Apologies for the late answer @mcassaniti 

I revieiwed what you said and you are right, in case that the retrieved OID is an object it should be treated as one.
I'm not sure about using the generic `snmp.PduVal2Cooked(pdu)`, it would need a later type validation as regex expects a string...

@mcassaniti , would you make a PR with this please ?

Thanks,
Regards!

**Comment by mcassaniti** [comment]
I've been slow on this too. A PR is coming.

**Comment by mcassaniti** [comment]
So I'm new to the go language and suddenly understand what you mean about type validation. Instead I've extended `PduVal2str()` with type assertions.
