### ISSUE TITLE
Potential case-insensitive import collision: import path should be updated

### ISSUE THREAD

**Issue by KateGo520** [toni-moreno/snmpcollector#438]
## Background
1. As [sirupsen/logrus README](https://github.com/sirupsen/logrus/blob/v1.2.0/README.md) of logrus said, `github.com/Sirupsen/logrus` is the old path, anything using it should be updated to import and require `github.com/sirupsen/logrus`.

> Some environments experienced problems with the upper-case variant, so the lower-case was decided. Everything using `logrus` will need to use the lower-case: `github.com/sirupsen/logrus`. Any package that isn't, should be changed.

2. The repo `github.com/Unknwon/com` already renamed to github.com/unknwon/com in the version v1.0.0.
https://github.com/unknwon/com/blob/v1.0.0/example_test.go
```
package com_test
import (
	"github.com/unknwon/com"
	…
)
```
The `github.com/Unknwon/com` is the old path, any repos using it should be updated to import and require `github.com/unknwon/com`. Or this may take some potential problems.

## Solution
Replace all the import paths, change `"github.com/Sirupsen/logrus"` to `"github.com/sirupsen/logrus"`.
Where did you import it: https://github.com/toni-moreno/snmpcollector/search?q=github.com%2FSirupsen%2Flogrus&unscoped_q=github.com%2FSirupsen%2Flogrus

Replace all the import paths, change `"github.com/Unknwon/com"` to `"github.com/unknwon/com"`.
Where did you import it: https://github.com/toni-moreno/snmpcollector/search?q=github.com%2FUnknwon%2Fcom&unscoped_q=github.com%2FUnknwon%2Fcom

**Comment by KateGo520** [comment]
@toni-moreno  @sbengo  Could you help me review this issue? Thx :p

**Comment by toni-moreno** [comment]
@KateGo520 sorry for the late response. I have a PR  https://github.com/toni-moreno/snmpcollector/pull/439 ready to fix this issue.  @sbengo could you please review it
