### ISSUE TITLE
[Bug] Scale is not working for all DataSrcTypes like INTEGER, Integer32

### ISSUE THREAD

**Issue by ciberp** [toni-moreno/snmpcollector#446]
Please include this information:
- What SnmpCollector version are you using? 
 Version: 0.8.1, Commit: f56ef9f, Build Date: 2020/10/6 08:21:41
- What OS are you running snmpcollector on?
 Ubuntu 19.10
- What did you do?
 Added snmp metrics with DataSrcType INTEGER and set Scale 0.01
- What was the expected result?
 Scaling is not working for DataSrcType INTEGER or Integer32. It works fot other DataSrcType like Gauge32, Counter64, ...
- What happened instead?
 It keeps same number, not scaled as expected.

Scale for DataSrcType INTEGER or Integer32 is working in older versions Version: 0.7.7, Commit: a242240, Build Date: 2018/5/28 08:04:19 or older, but not in later versions.

It think that problem is in pkg/data/metric/snmpmetric.go in function func (s *SnmpMetric) Init(c *config.SnmpMetricCfg) error {
in case:

			switch v := s.CookedValue.(type) {
			case uint64:
				//should return Integer
				val := (s.cfg.Scale * float64(s.CookedValue.(uint64))) + s.cfg.Shift
				s.CookedValue = uint64(math.Round(val))
			case float64:
				//should return float
				s.CookedValue = float64((s.cfg.Scale * float64(s.CookedValue.(float64))) + s.cfg.Shift)
			case string:
				s.log.Errorf("Error Trying to  Scale Function from non numbered STRING type value : %s ", s.CookedValue)
			default:
				s.log.Errorf("Error Trying to  Scale Function from unknown type %T value: %#+v", v, s.CookedValue)
			}
If I am correct than I am supposed to see "Error Trying to  Scale Function from unknown type %T value:" in logs but I don't. 
Than I comment out all the case code and use only this:

	if s.cfg.Scale != 0.0 || s.cfg.Shift != 0.0 {
		s.Scale = func() {
      s.CookedValue = 1234567
		}
	} else {
		s.Scale = func() {
		}  

And then vars with DataSrcType INTEGER or Integer32 with scale set all get value 1234567 which is correct. 

But I can't figure out exactly what is wrong with code that only fails to Scale for DataSrcType INTEGER, Integer32. It seems like data type problem/issue.

**Comment by ciberp** [comment]
Just found out that var DataSrcType INTEGER in this function is var type as int64, so I have partial solution:

	if s.cfg.Scale != 0.0 || s.cfg.Shift != 0.0 {
		s.Scale = func() {
			switch v := s.CookedValue.(type) {
			case uint64:
				//should return Integer
				val := (s.cfg.Scale * float64(s.CookedValue.(uint64))) + s.cfg.Shift
				s.CookedValue = uint64(math.Round(val))
                               //s.log.Info("unit64 type %T value: %#+v scale: %#+v", v, s.CookedValue, s.cfg.Scale)
			case float64:
				//should return float
				s.CookedValue = float64((s.cfg.Scale * float64(s.CookedValue.(float64))) + s.cfg.Shift)
                                //s.log.Errorf("float64 type %T value: %#+v scale: %#+v", v, s.CookedValue, s.cfg.Scale)
			case int64:
                                s.CookedValue = int64((s.cfg.Scale * float64(s.CookedValue.(int64))) + s.cfg.Shift)
			case string:
				s.log.Errorf("Error Trying to  Scale Function from non numbered STRING type value : %s ", s.CookedValue)
			default:
				s.log.Errorf("Error Trying to  Scale Function from unknown type %T value: %#+v", v, s.CookedValue)
			}

**Comment by toni-moreno** [comment]
Hello @ciberp thank you for the detailed review. 

I'm still trying to remember why we put Scale() before Convert()  in all cases. 

As yourself have pointed i other types Gauge32/Gauge64" is working fine. The main reason should be ensure the correct type at the end of the process. ( needed to insert data in the influxdb with the correct type)

even though this fix is working for you I would like maintain logical order and review the code again 

Could you please send me the original  logs  (before your fix) ?

I will test ASAP and review your logs and your fix.

Thank you very much!

**Comment by toni-moreno** [comment]
I've review and as I said before the problem was leak for int64 conversion here 

https://github.com/toni-moreno/snmpcollector/blob/f56ef9fc5181e96260a91ba473d5aa2ab059614b/pkg/data/metric/snmpmetric.go#L286-L301

```
time="2020-10-09 18:34:00" level=error msg="Error Trying to  Scale Function from unknown type int64 value: 
```

I will review and release a fix ASAP.

**Comment by ciberp** [comment]
Hello @toni-moreno, thank you for your quick reply and checking the issue.
I removed all my edits from the code and repeted some tests (git reset --hard origin/master HEAD is now at f56ef9f released 0.8.1):

| SnmpWalkValue  | DataSrcType | Conversion | Scale | Output |ExpectedOutput |
| ------------- | ------------- |------------- | ------------- | ------------- |  ------------- |
| -18478 | INTEGER |  FLOAT | 0.001 | -18478 | -18.478 |
| -18478 | INTEGER |  INTEGER | 0.001 | -18478 | -18.478 |
| 3363 | Gauge32 |  INTEGER | 0.001 | 3| 3 |
| 3363 | Gauge32 |  FLOAT | 0.001 | 3| 3.363 |

I think if you first do the Scale and then Conversion then in the case when source is integer and Conversion is set to Float you never get the float since this information is lost in Scale function. And result is always integer, seen in table last row. If I undserstand the code correctly.

**Comment by ciberp** [comment]
Hello @toni-moreno, just switched to the latest commit 71efeaa and repeated some tests. All results are good. I think your fix resolves this bug/issue. Thank you for your quick response. Will this fix be included in the current version or in the next?


| SnmpWalkValue  | DataSrcType | Conversion | Scale | Output |ExpectedOutput |
| ------------- | ------------- |------------- | ------------- | ------------- |  ------------- |
| -18465 | INTEGER |  FLOAT | 0.001 | -18.465 ✔| -18.465 |
| -18465 | INTEGER |  INTEGER | 0.001 | -18 ✔| -18 |
| 8875 | Counter64 | INTEGER | 0.1 | 888 ✔| 888 |
| 8875 | Counter64 | FLOAT | 0.1 | 887.5 ✔| 887.5 |
| 3364 | Gauge32 |  INTEGER | 0.01 | 34 ✔| 34 |
| 3364 | Gauge32 |  FLOAT | 0.01 | 33.64 ✔| 33.64 |
| 28 | Counter32 |  INTEGER | 0.1 | 3 ✔| 3 |
| 28 | Counter32 |  FLOAT | 0.1 | 2.8000000000000003 ✔| 2.8 |

**Comment by toni-moreno** [comment]
Hello again @ciberp , thank you for your fast review. 

still needs to add some more conversion unit tests and merge the `fix/#446` branch, this fix will be included in the 0.8.2 version. there is no planned date to do it , so I expect you can use your self made binary in your platform until then.

**Comment by toni-moreno** [comment]
Hello @ciberp , while working in adding CounterXX tests,  I've noted you are working with raw Counter32/Counter64 . Did you test their cooked type COUNTER32/COUNTER64 ? IMHO is one of the main features of the snmpcollector allowing  you working with real data at the DB backend instead of raw counters.

**Comment by ciberp** [comment]
Hello @toni-moreno, this raw Counter32/Counter64 was used just to test if Scale is also working properly for counters. Yes in prod we are using COUNTER32/COUNTER64/CounterXX and GetRate function. 

Otherwise, this is one of the best snmp collectors, before that we were using collectd but was lack of bulk and api function, if I am not mistaken. We are still using it for getting data from python scripts via devices show commands where there is not other way to get specific metrics.
