### ISSUE TITLE
[Question] Pooling snmp v1 equipments Exemys

### ISSUE THREAD

**Issue by yoleonet** [toni-moreno/snmpcollector#454]
I can't poling snmp v1 exemys
verify that the code does the check to all the equipments that are added with the OID
.1.3.6.1.2.1.1.1.0
.1.3.6.1.2.1.1.3.0
.1.3.6.1.2.1.1.4.0
.1.3.6.1.2.1.1.5.0
.1.3.6.1.2.1.1.6.0
is there a way to avoid this check? because we notice that if I can't make this check, you can't scan it. i would appreciate your answer. thank you

Greetings.

**Comment by toni-moreno** [comment]
These OID's give basic info for a lot of devices. But you could configure an "Alternate System OID's" ( any valid OID) on device config if these OID's does not  exist. 

You can read device config info here. https://github.com/toni-moreno/snmpcollector/wiki/Component:-SNMP-Devices

**Comment by yoleonet** [comment]
Thank you very much for your prompt response. 
I had tried to enter some alternative OID. but I can't find the format in which I should enter it.
When I enter it, I get the "Invalid format" sign. Must be key=value, separated by commas" you will have some example please. 

Cordial greetings.

**Comment by yoleonet** [comment]
Ready Toni, I was able to solve it.
with STRING=1.3.6.1.2.1.1.0
Thank you very much for the help.

Cordial greetings
