### ISSUE TITLE
[Question] Using StringEval Metric to convert integer to boolean not working as expected

### ISSUE THREAD

**Issue by ciberp** [toni-moreno/snmpcollector#455]
Please include this information:
- What SnmpCollector version are you using?  
   Version: 0.8.1, Commit: 2ce0d07, Build Date: 2020/10/14 07:41:11
- What OS are you running snmpcollector on? 
   CentOS Linux release 7.8.2003 (Core)
- What did you do?
  Convert oid integer to boolean, if oid integer = 1, then return True, else return False
  If I do that, I get expected result but I don't want to have `operstate` included in measurement. But without that conversion is not working?

![image](https://user-images.githubusercontent.com/23559198/98223187-0bc26280-1f52-11eb-88ca-71a956238bb2.png)
![image](https://user-images.githubusercontent.com/23559198/98226162-f64f3780-1f55-11eb-80ab-56f9e9784d38.png)
![image](https://user-images.githubusercontent.com/23559198/98226343-30b8d480-1f56-11eb-9165-2eb6428b6eb5.png)

If I want to remove `operstate` from influx measurement, I get error:

![image](https://user-images.githubusercontent.com/23559198/98223881-04e81f80-1f53-11eb-9883-42da39047b99.png)

If I somehow remove `operstate` from influx measurement in a way to manipulate SNMP metrics entries, than conversion is not working:

![image](https://user-images.githubusercontent.com/23559198/98223187-0bc26280-1f52-11eb-88ca-71a956238bb2.png)
![image](https://user-images.githubusercontent.com/23559198/98224266-92c40a80-1f53-11eb-84ea-86a06fc060d9.png)
![image](https://user-images.githubusercontent.com/23559198/98226533-71b0e900-1f56-11eb-876b-52dc8096d8a8.png)

I don't understand what am I doing wrong?

And another question. Is this information on wiki page correct?
Source = https://github.com/toni-moreno/snmpcollector/wiki/Component:-SNMP-Metrics

![image](https://user-images.githubusercontent.com/23559198/98224920-5fce4680-1f54-11eb-97ef-b8948fbff28f.png)

Thank you for your answers.

**Comment by sbengo** [comment]
Hi @ciberp , first of all, thanks for the detailed explanation

`STRINGEVAL` metrics uses the already queried ones to make operations between them, so, as you have said, the metric used on `STRINGEVAL` must be included on the measurement

When you define a measurement, you can modify the `Report Field` section to choose the report behaviour (https://github.com/toni-moreno/snmpcollector/wiki/Component:-Measurements#configuration-parameters - Config parameters -> Fields) 

![image](https://user-images.githubusercontent.com/13196237/98228402-d40ae900-1f58-11eb-863b-52ee3c3c7d75.png)

On your case, if you don't want the `ifOperStatus | operstatus`, just pick the option `Never Report` and it won't be reported on InfluxDB.

Can you try it please?

Thanks,
Greetings!

**Comment by ciberp** [comment]
Wau, thank you for your quick reply and solution. I tried and it works like a charm.

![image](https://user-images.githubusercontent.com/23559198/98235753-8c895a80-1f62-11eb-84ad-01f1f7bf8e9e.png)
![image](https://user-images.githubusercontent.com/23559198/98235791-9f9c2a80-1f62-11eb-9a5b-da6e5313a51e.png)

Thank you.
