### ISSUE TITLE
[Bug] Device Not Connected

### ISSUE THREAD

**Issue by DBurgers** [toni-moreno/snmpcollector#468]
- SnmpCollector v0.9.0
- Docker/Ubuntu 20.10
- What did you do?
       Added SNMP device, added SNMP Metric. "Test Connection" on SNMP Devices page is successful.
- What was the expected result?
       Device on Device status page to show connected.
- What happened instead?
       Filter "Warning 1 device trying to connect..." is displayed at top of Device status page. Viewing device on status page shows it is not connected.
No log files are being created. Portainer logs for SNMPCollector show "Failed to write to log, invalid argument", "level=warning msg='Error on create debug file : open log/snmpdebug_Freezer_init.log: permission denied '".

If I need to supply any additional info please let me know, thanks.

**Comment by DBurgers** [comment]
At the bottom of the view device page under Device status it says "No measurements associated with the device. Couldn't retrieve metric runtime info". As far as I can tell I've configured the measurement, but I'm obviously missing something.

I also just installed the deb version and set the device back up in it. Exact same issue. Logs work on the deb version but I didn't see anything myself in the logs that seemed related.

**Comment by toni-moreno** [comment]
Hello @DBurgers . coud be nice if you also give us information about what you did. 

About the connection error:  Could you attach here some screenshots with hour, snmp Device , measurements, metrics , configuration please ? 

About permission for log files .  Could you please attach you docker command (if deployed from cli), docker-compose.yml  ( if deployed with docker-composer), stack file ( if deployed on swarm) ,  or deployment , configmaps , etc ( if deployed in kubernetes) ?

Why do you think this could be a bug ?

Thank you very much!

**Comment by DBurgers** [comment]
Hey @toni-moreno 
This is the docker command I used 
`docker run -d --name=snmpcol_instance00 -p 80:8090 -v /mylocal/conf:/opt/snmpcollector/conf -v /mylocal/log:/opt/snmpcollector/log tonimoreno/snmpcollector`
I don't feel the configuration error is a bug, that's probably just me not fully understanding what I'm tasked with.
Here are screenshots of my configuration: [https://imgur.com/a/x8kz4HW](https://imgur.com/a/x8kz4HW)
The log files not writing seemed to me like a bug however, because I used the docker command provided in the wiki to install.

Here is a section of my docker container log:
```
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
time="2021-02-04 17:30:40" level=info msg="get runtime data from id Freezer"
[Macaron] 2021-02-04 17:30:40: Completed GET /api/rt/device/info/Freezer 200 OK in 9.978678422s
[Macaron] 2021-02-04 17:30:40: Started GET /api/rt/device/info/Freezer for 192.168.1.108
time="2021-02-04 17:30:40" level=info msg="get runtime data from id Freezer"
[Macaron] 2021-02-04 17:30:40: Completed GET /api/rt/device/info/Freezer 200 OK in 241.039µs
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
[Macaron] 2021-02-04 17:30:50: Started GET /api/rt/device/info/Freezer for 192.168.1.108
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
[Macaron] 2021-02-04 17:30:52: Started PUT /api/rt/device/status/deactivate/Freezer for 192.168.1.108
time="2021-02-04 17:31:00" level=info msg="get runtime data from id Freezer"
[Macaron] 2021-02-04 17:31:00: Completed GET /api/rt/device/info/Freezer 200 OK in 9.987769524s
time="2021-02-04 17:31:00" level=info msg="deactivating runtime on device  Freezer"
[Macaron] 2021-02-04 17:31:00: Completed PUT /api/rt/device/status/deactivate/Freezer 200 OK in 7.966934294s
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
Failed to write to log, invalid argument
[Macaron] 2021-02-04 17:31:00: Started GET /api/rt/device/info/Freezer for 192.168.1.108
time="2021-02-04 17:31:00" level=info msg="get runtime data from id Freezer"
[Macaron] 2021-02-04 17:31:00: Completed GET /api/rt/device/info/Freezer 200 OK in 221.911µs
[Macaron] 2021-02-04 17:31:00: Started GET /api/rt/device/info/Freezer for 192.168.1.108
time="2021-02-04 17:31:00" level=info msg="get runtime data from id Freezer"
[Macaron] 2021-02-04 17:31:00: Completed GET /api/rt/device/info/Freezer 200 OK in 186.804µs

```

**Comment by toni-moreno** [comment]
@DBurgers

in one hand:  in order to use volumes from 0.9 release you should  first let user with UID/GID=472  write in you shared volume.

```
sudo mkdir /mylocal
sudo chown 472:472 /mylocal
docker run -d --name=snmpcol_instance00 -p 80:8090 -v /mylocal/conf:/opt/snmpcollector/conf -v /mylocal/log:/opt/snmpcollector/log tonimoreno/snmpcollector
```
In the other hand:

What kind of device is "Freezer", snmpcollector by default check if set  thes OID's , availables on most of devices.

```	// SysDescr     .1.3.6.1.2.1.1.1.0
	// sysUpTime    .1.3.6.1.2.1.1.3.0
	// SysContact   .1.3.6.1.2.1.1.4.0
	// SysName      .1.3.6.1.2.1.1.5.0
	// SysLocation  .1.3.6.1.2.1.1.6.0
```

if not available in your device, you can setup  an alternate OID to check for existence.

![image](https://user-images.githubusercontent.com/5883405/106940496-e6481f00-6721-11eb-8d7a-e6861db8e3f4.png)

let me know if you can get working your snmpcollector with these indications.

**Comment by DBurgers** [comment]
Running the commands provided still didn't fix the logging, same issue. I can live without the logs if needed.
I checked and the device [(Vertiv Watchdog 15)](https://www.vertiv.com/en-us/products-catalog/monitoring-control-and-management/monitoring/watchdog-15/) does have all four of those OIDs. I found that after restarting the Docker container, every now and then the device will start up and show as running. But, after making any changes and redeploying it, it returned to "Device is not connected" on the status page.
Here are the additional changes I made: [https://imgur.com/a/FwLPLSZ](https://imgur.com/a/FwLPLSZ)
When the device was showing as connected, it still did not seem to be gathering data. Thanks for the help, I seriously appreciate it.

**Comment by toni-moreno** [comment]
Ohk wait.. test these other commands please... 

```
sudo mkdir -p /mylocal/log
sudo chown -R 472:472 /mylocal
sudo docker run -d --name=snmpcol_instance00 -p 80:8090  -v /mylocal/log:/opt/snmpcollector/log tonimoreno/snmpcollector:latest
```
connect to `http://localhost`  and you can see now logs in `/mylocal/log` dir

**Comment by toni-moreno** [comment]
@DBurgers  I've reviewed the uploaded images on https://imgur.com and I miss the snmp device config.  ( by the way: you can attach files here better than external site).

**Comment by DBurgers** [comment]
@toni-moreno Sorry about that, I somehow didn't notice you could do that. I've added the device config now. Now that I've reinstalled the container with the run command you provided the device seems to be connecting as well. It isn't however sending the data it gathers to the Influx server.
![DeviceStatus](https://user-images.githubusercontent.com/78175757/107068215-f1dd2980-67a5-11eb-9881-260d8110fdbd.png)
![Device](https://user-images.githubusercontent.com/78175757/107065849-dae90800-67a2-11eb-931c-1c80e9998f9e.png)
![InfluxMeasurements](https://user-images.githubusercontent.com/78175757/107065851-dae90800-67a2-11eb-9e66-67116d3878ba.png)
![influxServer](https://user-images.githubusercontent.com/78175757/107068453-454f7780-67a6-11eb-8874-2f1c39ebde00.png)
![MeasurementGroups](https://user-images.githubusercontent.com/78175757/107065853-db819e80-67a2-11eb-8c86-6799749bd2da.png)
![SNMPMetrics](https://user-images.githubusercontent.com/78175757/107068436-3ec10000-67a6-11eb-8d3d-d4d0bc228ebe.png)

**Comment by toni-moreno** [comment]
Snmpcolector is working fine. What about logs? Any error message?

**Comment by DBurgers** [comment]
@toni-moreno Sorry for the late reply. I've attached my log files. I cut off a big chuck of Freezer.log and snmpdebug_Freezer_TempSensor.log as tehy were several hundred MBs. I did notice when going through the logs again that it mentioned my Influx DB "snmp" did not exist. As far as I can tell the Influx server is configured in SNMP collector correctly. The Influx server is already gathering data from Telegraf into a separate DB. When I show the measurements in Influx for my snmp DB, here is the response:
```
root@502b71614e51:/# influx
Connected to http://localhost:8086 version 1.8.3
InfluxDB shell version: 1.8.3
> use snmp
Using database snmp
> show measurements
name: measurements
name
----
TempMain
TempSensor
```
Which tells me that SNMP Collector did manage to communicate with Influx at some point.
[Freezer.log](https://github.com/toni-moreno/snmpcollector/files/5947440/Freezer.log)
[http_access.log](https://github.com/toni-moreno/snmpcollector/files/5947441/http_access.log)
[snmpcollector.log](https://github.com/toni-moreno/snmpcollector/files/5947442/snmpcollector.log)
[snmpdebug_Freezer_init.log](https://github.com/toni-moreno/snmpcollector/files/5947443/snmpdebug_Freezer_init.log)
[snmpdebug_Freezer_TempSensor.log](https://github.com/toni-moreno/snmpcollector/files/5947444/snmpdebug_Freezer_TempSensor.log)

**Comment by sbengo** [comment]
Hi @DBurgers , 

Your `Freezer.log` has only information about 2 polling periods: `2021-02-08 22:56:40` and `2021-02-08 22:56:50` (`Freq=10`)

As the log says, it seems that data has been retrieved and processed:

```
time="2021-02-08 22:56:40" level=debug msg="MEASUREMENT [TempSensor] GENERATED INFLUX POINT[TempSensor] value: TempSensor,TempSensor=FreezerBackTemp,device=Freezer DewPointMain=-161i,HumidityMain=70i,TempMain=-92i 1612825000003031811"
```
```
time="2021-02-08 22:56:50" level=debug msg="MEASUREMENT [TempSensor] GENERATED INFLUX POINT[TempSensor] value: TempSensor,TempSensor=FreezerBackTemp,device=Freezer DewPointMain=-161i,HumidityMain=70i,TempMain=-92i 1612825010000452408"
```

At this time, SNMPCollector logs doesn't seems to log any error, so everything seems to work as expected.

In order to see what is happening:
- Are you sure that data is not being sent into InfluxDB? Can you do a simple query to check if the data has been retrieved?

- If your data has not been sent into InfluxDB, can you put please, change the SNMPCollector loglevel into debug? (logs related with sending data into InfluxDB seems to be available in debug loglevel)
  --> You can set it directly form config file `[general] - loglevel = "debug"` or directly with environment var: `SNMPCOL_GENERAL_LOG_LEVEL=debug"

**Comment by toni-moreno** [comment]
Hello @DBurgers , I will close this Issue as it seems snmpcollector working fine. Feel free to reopen it if you hava more evidences as @sbengo ask you some days ago.

Thank you.
