### ISSUE TITLE
[Feature request] snmpcollector not able to send data to external influxdb when behind corp. proxy

### ISSUE THREAD

**Issue by fredma** [toni-moreno/snmpcollector#473]
- What SnmpCollector version are you using?
0.8.1

- What OS are you running snmpcollector on?

rehl7.8

- What did you do?

We have snmpcollector running in docker container and I defined the env var for HTTP_PROXY and HTTPS_PROXY

            "Env": [
                "HTTP_PROXY=http://myproxy:80/",
                "HTTPS_PROXY=http://myproxy:80/",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PATHS_HOME=/opt/snmpcollector/",
                "SNMPCOL_GENERAL_DATA_DIR=/opt/snmpcollector//data/",
                "SNMPCOL_GENERAL_LOG_DIR=/opt/snmpcollector//log/"
            ],

- What was the expected result?

snmp collector runs inside a corp network and it is configured to send data to external influxdb endpoint (outside of corp network)

The expected result should be a successful connection to external influxdb endpoint. 

- What happened instead?

snmpcollector is not able to connect and the below error show in the snmpcollector.log

time="2021-02-22 10:41:23" level=error msg="ERROR on Write batchPoint in DB default (3 points) | elapsed : 30.000279439s | Error: Post https://<EXTERNAL_INFLUXDB_FQDN>:443/write?consistency=&db=snmp&precision=s&rp=autogen: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) "

To verify this is an issue in snmpcollector, I ran a curl command within the container and it was able to use the proxy defined in HTTPS_PROXY to reach external endpoint e.g. google.co.uk

**Comment by fredma** [comment]
I believe this is using the influxdb client and a ticket has been raised for this for influxdb
https://github.com/influxdata/telegraf/issues/1588
It looks like the fix has already been merged in https://github.com/influxdata/telegraf/pull/3212/files#diff-596f6f5130a1742072db3bbd1eda995f79c89a5cb7200f5a0204227cace857b5R56
and possibly snmpcollector would need to use the latest influxdb client?

**Comment by fredma** [comment]
Hi, I managed to fix the issue by applying the following patch on the 0.9.0 version.

[http_proxy.patch.txt](https://github.com/toni-moreno/snmpcollector/files/6024315/http_proxy.patch.txt)

Can you please review and let me know if it is good to merge upstream?

Thanks,

Fred

**Comment by toni-moreno** [comment]
Hello @fredma  Could you please, fork the repo and  send a PR with these changes please?

**Comment by fredma** [comment]
Thanks @toni-moreno, I will do that.

**Comment by fredma** [comment]
Here you go

https://github.com/toni-moreno/snmpcollector/pull/474

**Comment by fredma** [comment]
Sorry, I was on holidays.
Thanks for the merge.
