### ISSUE TITLE
FR: add pagination size on runtime tables.

### ISSUE THREAD

**Issue by toni-moreno** [toni-moreno/snmpcollector#489]
Could be fine if we can select the maximum number of rows in the runtime tables when paginating.
Somehing like 

![image](https://user-images.githubusercontent.com/5883405/114511120-c9572d00-9c37-11eb-82ea-330f2e73a692.png)

**Comment by sbengo** [comment]
In runtime, its not really clear as it is next to base and filters labels over the selected measurement, but all the tables have pagination enabled and a selector!

![image](https://user-images.githubusercontent.com/13196237/117407805-5f1c6a00-af0f-11eb-9878-807001bcb795.png)
