### ISSUE TITLE
[Feature Request] Add subIndexOID on measurements go get index descriptors

### ISSUE THREAD

**Issue by sbengo** [toni-moreno/snmpcollector#67]
To explain this feature let me show you an example.

On Cisco Switches, the CPU Base OID (table) is: ```.1.3.6.1.4.1.9.9.109.1.1.1.1.7``` giving as ouptut the different CPU usage according to the physical devices.

**CPU Query**
```
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.7.22 = Gauge32: 2
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.7.23 = Gauge32: 1
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.7.24 = Gauge32: 18
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.7.25 = Gauge32: 23
```
The table indexes are: 22,23,24,25.
According to Cisco docs, the indexes are defined on physicalIndex table: ```.1.3.6.1.2.1.47.1.1.1.1.7```, giving as output all indexes:

**PhysicalIndex Query**
```
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.2.22 = INTEGER: 22
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.2.23 = INTEGER: 23
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.2.24 = INTEGER: 24
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.2.25 = INTEGER: 25
````

As you can see this is not returning related names of the physical devices so indexName bound with the device would be:

| key              	| value 	|
|------------------|--------	|
| cpuphysicalIndex 	| 22    	|
| cpuphysicalIndex 	| 23    	|
| cpuphysicalIndex 	| 24    	|
| cpuphysicalIndex 	| 25    	|

To get the real name (descriptor) assigned to each physDevice the following OID must be used to index: ```.1.3.6.1.2.1.47.1.1.1.1.7```
**PhysicalDescriptors Query**
```
SNMPv2-SMI::mib-2.47.1.1.1.1.7.10 = STRING: "Fabric Stack Root"
SNMPv2-SMI::mib-2.47.1.1.1.1.7.22 = STRING: "Supervisor Module-2"
SNMPv2-SMI::mib-2.47.1.1.1.1.7.23 = STRING: "Supervisor Module-2"
SNMPv2-SMI::mib-2.47.1.1.1.1.7.24 = STRING: "10 Gbps Ethernet Module"
SNMPv2-SMI::mib-2.47.1.1.1.1.7.25 = STRING: "1/10 Gbps Ethernet Module"
SNMPv2-SMI::mib-2.47.1.1.1.1.7.149 = STRING: "Nexus7000 C7004 (4 Slot) Chassis"
SNMPv2-SMI::mib-2.47.1.1.1.1.7.214 = STRING: "SupSlot-1"
```

So, in this case, the correct way to do it would be index by PhysicalDescriptors... but... **the index 22 and 23 has the same name, so on our measurement only 1 of both would be generated!!**

| key              	| value 	|
|------------------|--------	|
| cpuphysicalIndex 	| Supervisor Module-2 	|
| cpuphysicalIndex 	| 10 Gbps Ethernet Module	|
| cpuphysicalIndex 	| 1/10 Gbps Ethernet Module   	|

To solve that would be great if we could make a second OID indexer to get the name querying only the indexes got by indexOID query. Following with the example above:

Base OID: ```.1.3.6.1.4.1.9.9.109.1.1.1.1.7 {22,23,24,25}```
IndexOID:  ```.1.3.6.1.2.1.47.1.1.1.1.7  {22,23,24,25}```
Name Index: 
```
SNMPv2-SMI::mib-2.47.1.1.1.1.7.22 = STRING: "Supervisor Module-2"
SNMPv2-SMI::mib-2.47.1.1.1.1.7.23 = STRING: "Supervisor Module-2"
SNMPv2-SMI::mib-2.47.1.1.1.1.7.24 = STRING: "10 Gbps Ethernet Module"
SNMPv2-SMI::mib-2.47.1.1.1.1.7.25 = STRING: "1/10 Gbps Ethernet Module"
```
And compose the indexName with the indexOID and NameIndex:

| key              	| value 	|
|------------------|--------	|
| cpuphysicalIndex 	| 22 - Supervisor Module-2 	|
| cpuphysicalIndex 	| 23 - Supervisor Module-2  	|
| cpuphysicalIndex 	| 24  - 10 Gbps Ethernet Module	|
| cpuphysicalIndex 	| 25 - 1/10 Gbps Ethernet Module   	|

**Comment by sbengo** [comment]
To add more info on the feature request, we must take care with some special cases on indexing.
On the example above, the OID wich is returning value indexes assigned on description table has 'zero' as a special value. The zero does not appear as an entry:

`If the CPU statistics in this entry correspond to more than one physical entity (or to no physical entity), or if the entPhysicalTable is not supported on the SNMP agent, the value of this object must be zero`

**Full OID description:**

```
Détails
OID	1.3.6.1.4.1.9.9.109.1.1.1.1.2
Module	CISCO-PROCESS-MIB (CISCO)
Nom	cpmCPUTotalPhysicalIndex
Acces	readonly
Status	current
Description	The entPhysicalIndex of the physical entity for which the CPU statistics in this entry are maintained. The physical entity can be a CPU chip, a group of CPUs, a CPU card etc. The exact type of this entity is described by its entPhysicalVendorType value. If the CPU statistics in this entry correspond to more than one physical entity (or to no physical entity), or if the entPhysicalTable is not supported on the SNMP agent, the value of this object must be zero.
Syntaxe	EntPhysicalIndexOrZero (CISCO-TC)
```

**Comment by toni-moreno** [comment]
I've created a New Indexed With Indirect TAG with allow us to add another OID to get the tag name

![image](https://cloud.githubusercontent.com/assets/5883405/21455039/8067dfaa-c91d-11e6-93d9-7bf37e28686a.png)

Waitting to some more test before to send a PR
