### ISSUE TITLE
[Feature Request] Add a Collection Jitter parameter to distribute load on time 

### ISSUE THREAD

**Issue by toni-moreno** [toni-moreno/snmpcollector#70]
As Telegraf does, could be interesting add a collection Jitter to avoid all devices querying  at once.

https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf#L48

**Comment by tardoe** [comment]
+1 on this one, my devices would thank you!

**Comment by toni-moreno** [comment]
Hi @tardoe after some years working we think this is not an important Issue. Please reopen is you miss
