### ISSUE TITLE
[Feature Request] Parse strings fields to create booleans

### ISSUE THREAD

**Issue by sbengo** [toni-moreno/snmpcollector#92]
After the implementation of stringParser there is one case that we are missing from #51 

The following example shows some metris that are completely strings.
```
1.3.6.1.4.1.7779.3.1.1.2.1.10.1.3.36 = Power1 (AC) OK
1.3.6.1.4.1.7779.3.1.1.2.1.10.1.3.37 = Power2 (AC) KO
```
It could be done with a new metric type allowing the user create some regex and transform them into booleans depending on the capturing group rule:

Base OID: ```1.3.6.1.4.1.7779.3.1.1.2.1.10.1.3.3X```
Type: ```Boolean stringParser```
True : ```.*OK$```
False: ```.*KO$```

So the result would be:
Power1 : ```1```
Power2 :  ```0```

**Comment by toni-moreno** [comment]
Closed in favor of https://github.com/toni-moreno/snmpcollector/issues/165
